# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
from openai import APIConnectionError, APIError, APITimeoutError, RateLimitError

from app.config import OPENAI_MODEL
from app.extensions import openai_client


PORTION_SANITY_RULE = (
    " Kalori/makro değerlerini ASLA tüm bir tarifin, tencerenin veya devasa "
    "porsiyonun toplamı olarak verme. Her zaman makul TEK porsiyon (≈200-350g) "
    "veya net 100g bazında hesapla; bir insanın tek oturuşta yiyebileceği makul "
    "sınırların dışına çıkma."
)


def _openai_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7):
    """Merkezi LLM sohbet çağrısı (OpenAI Chat Completions).

    `messages` Anthropic ile uyumlu [{"role","content"}] listesidir; system_prompt
    varsa başa bir system mesajı olarak eklenir. Hata durumunda kullanıcı-dostu bir
    RuntimeError fırlatır; çağıranlar bunu kendi try/except fallback'leriyle yakalar.
    """
    full_messages = []
    if system_prompt:
        full_messages.append({"role": "system", "content": system_prompt})
    full_messages.extend(messages)
    try:
        resp = openai_client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=full_messages,
            max_tokens=max_tokens,
            temperature=temperature,
        )
        return resp.choices[0].message.content
    except RateLimitError:
        raise RuntimeError("AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (APITimeoutError, APIConnectionError):
        raise RuntimeError("AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except APIError as e:
        raise RuntimeError(f"AI servisi hatası: {e}")
