# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import logging
import threading
from dataclasses import dataclass

try:
    import anthropic  # Bedrock Messages (Sonnet and Haiku)
except Exception:  # paket yoksa Bedrock zaten BEDROCK_ENABLED ile kapalı kalır
    anthropic = None

from app.config import BEDROCK_ENABLED, BEDROCK_MAX_TOKENS, BEDROCK_MODEL
from app.extensions import bedrock_client
from app.services import ai_provider_call, ai_recovery
from app.services.ai_model_policy import haiku_policy, sonnet_policy
from app.services.ai_recovery import TransientAIError
from app.services.ai_spend_guard import AISpendLimitExceeded

logger = logging.getLogger(__name__)
_completion_tls = threading.local()


@dataclass(frozen=True)
class ChatCompletion:
    """Provider text plus finish metadata. Existing chat helpers still return str."""

    text: str
    truncated: bool = False
    finish_reason: str | None = None
    provider: str = "unknown"
    fallback_used: bool = False


def _remember_completion(result: "ChatCompletion") -> "ChatCompletion":
    _completion_tls.last = result
    return result


# WS4: şablon app/prompts/nutrition.py'ye taşındı; eski import yolu
# (meallog/ai_nutrition `from app.services.ai import PORTION_SANITY_RULE`) korunur.
from app.prompts.nutrition import PORTION_SANITY_RULE  # noqa: E402,F401 (re-export)

# Same Bedrock client as Sonnet. Tests may replace this name without replacing
# the heavy client, so a Sonnet failure can be scripted apart from Haiku.
light_client = bedrock_client


def _anthropic_messages(messages, system_prompt):
    sys_parts = [system_prompt] if system_prompt else []
    convo = []
    for message in messages:
        if message.get("role") == "system":
            sys_parts.append(message.get("content", ""))
        else:
            convo.append(message)
    system = "\n\n".join(part for part in sys_parts if part)
    return system, convo


def _text_from_anthropic(resp):
    for block in getattr(resp, "content", None) or []:
        if getattr(block, "type", None) == "text" and getattr(block, "text", None):
            return block.text
    return ""


def _anthropic_chat(policy, messages, system_prompt=None, max_tokens=1024,
                    temperature=0.7, feature="other", *, client, clamp=False):
    """One Messages API call. ``client`` is the Bedrock messages client."""
    if anthropic is None:
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")
    system, convo = _anthropic_messages(messages, system_prompt)
    capped = min(max_tokens, BEDROCK_MAX_TOKENS) if clamp else max_tokens
    try:
        kwargs = dict(model=policy.model_id, max_tokens=capped,
                      messages=convo, temperature=temperature)
        if system:
            kwargs["system"] = system
        gate = "bedrock"
        with ai_provider_call.admit(feature=feature, provider=gate, payload=kwargs) as call:
            resp = call.create(client.messages.create)
        finish_reason = getattr(resp, "stop_reason", None)
        truncated = finish_reason == "max_tokens"
        if truncated:
            logger.warning(
                "Claude yanıtı max_tokens=%s sınırında kesildi (stop_reason=max_tokens)",
                capped)
        text = _text_from_anthropic(resp)
        _remember_completion(ChatCompletion(
            text=text, truncated=truncated, finish_reason=finish_reason,
            provider=policy.logical_model))
        return text
    except AISpendLimitExceeded:
        raise
    except anthropic.RateLimitError:
        raise TransientAIError(
            "AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise TransientAIError(
            "AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except anthropic.APIError as exc:
        logger.warning("Claude/Bedrock APIError: %s", exc)
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")


def _openai_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7,
                 feature="other"):
    """Light chat. The name is the historical entry point.

    Implementation is Claude Haiku 4.5 on Bedrock EU Geo. There is no direct
    OpenAI transport. Feature max_tokens is preserved (not clamped to the
    Sonnet ceiling); the provider door still refuses an over-cap request.
    """
    return _anthropic_chat(
        haiku_policy(), messages, system_prompt=system_prompt,
        max_tokens=max_tokens, temperature=temperature, feature=feature,
        client=light_client, clamp=False)


def _light_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7,
                feature="other"):
    return _openai_chat(
        messages, system_prompt=system_prompt, max_tokens=max_tokens,
        temperature=temperature, feature=feature)


def _claude_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7,
                 feature="other"):
    """Ağır görev LLM çağrısı (Claude Sonnet 4.5 — Amazon Bedrock, Messages API).

    `_openai_chat` ile AYNI imzayı taşır; OpenAI-stili argümanları Anthropic'e çevirir:
      • system_prompt ve messages içindeki her {"role":"system"} üst düzey `system=`
        paramına taşınır (Anthropic system rolünü messages içinde kabul etmez).
      • max_tokens, Anthropic'in zorunlu kıldığı sınır için BEDROCK_MAX_TOKENS'a clamp'lenir.
      • Yanıt, ilk text content bloğunun metnidir.
    Hata durumunda `_openai_chat` ile birebir aynı Türkçe RuntimeError'ları fırlatır;
    çağıran (_heavy_chat) bunları yakalayıp OpenAI'ya düşer.
    """
    sys_parts = [system_prompt] if system_prompt else []
    convo = []
    for m in messages:
        if m.get("role") == "system":
            sys_parts.append(m.get("content", ""))
        else:
            convo.append(m)
    system = "\n\n".join(p for p in sys_parts if p)
    capped = min(max_tokens, BEDROCK_MAX_TOKENS)
    try:
        kwargs = dict(model=BEDROCK_MODEL, max_tokens=capped,
                      messages=convo, temperature=temperature)
        if system:
            kwargs["system"] = system
        with ai_provider_call.admit(feature=feature, provider="bedrock",
                                    payload=kwargs) as call:
            resp = call.create(bedrock_client.messages.create)
        finish_reason = getattr(resp, "stop_reason", None)
        truncated = finish_reason == "max_tokens"
        if truncated:
            logger.warning("Claude yanıtı max_tokens=%s sınırında kesildi (stop_reason=max_tokens)", capped)
        text = ""
        for block in resp.content:
            if getattr(block, "type", None) == "text":
                text = block.text
                break
        _remember_completion(ChatCompletion(
            text=text, truncated=truncated, finish_reason=finish_reason,
            provider="bedrock"))
        return text
    except AISpendLimitExceeded:
        raise
    except anthropic.RateLimitError:
        # Geçici: kurtarma katmanı yeniden dener (TransientAIError, RuntimeError alt sınıfı).
        raise TransientAIError("AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise TransientAIError("AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except anthropic.APIError as e:  # APIStatusError bunun alt sınıfıdır — tek except yeter
        logger.warning("Claude/Bedrock APIError: %s", e)
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")


def _image_block(image_bytes, media_type):
    import base64
    if media_type not in ("image/jpeg", "image/png", "image/webp", "image/gif"):
        media_type = "image/jpeg"
    return {
        "type": "image",
        "source": {
            "type": "base64",
            "media_type": media_type,
            "data": base64.b64encode(image_bytes).decode("utf-8"),
        },
    }


def _bedrock_image_message(content, max_tokens, temperature, feature="vision"):
    try:
        payload = dict(model=BEDROCK_MODEL,
                       max_tokens=min(max_tokens, BEDROCK_MAX_TOKENS),
                       messages=[{"role": "user", "content": content}],
                       temperature=temperature)
        with ai_provider_call.admit(feature=feature, provider="bedrock",
                                    payload=payload) as call:
            resp = call.create(bedrock_client.messages.create)
        for block in resp.content:
            if getattr(block, "type", None) == "text":
                return block.text
        return ""
    except AISpendLimitExceeded:
        raise
    except anthropic.RateLimitError:
        raise RuntimeError("AI servisi \u015fu an yo\u011fun (rate limit). L\u00fctfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise RuntimeError("AI servisine ula\u015f\u0131lamad\u0131 (zaman a\u015f\u0131m\u0131). L\u00fctfen tekrar deneyin.")
    except anthropic.APIError:
        logger.warning("bedrock_image_request_failed")
        raise RuntimeError("AI servisi hatas\u0131. L\u00fctfen tekrar deneyin.")


def _bedrock_compare_images(
        baseline_bytes, baseline_media_type,
        current_bytes, current_media_type, prompt,
        max_tokens=1200, temperature=0.0, feature="vision"):
    content = [
        {"type": "text", "text": prompt},
        {"type": "text", "text": "Image A \u2014 baseline"},
        _image_block(baseline_bytes, baseline_media_type),
        {"type": "text", "text": "Image B \u2014 current"},
        _image_block(current_bytes, current_media_type),
    ]
    return _bedrock_image_message(content, max_tokens, temperature, feature=feature)


def _bedrock_validate_image(image_bytes, media_type, prompt, max_tokens=400, temperature=0.0,
                            feature="vision"):
    """Bedrock (Claude Sonnet) çok-kipli doğrulama: bir görsel + metin promptu gönderir,
    modelin ham metin yanıtını (genelde katı JSON) string olarak döndürür.

    Anthropic Messages API GÖRSEL BLOĞU kullanır — OpenAI'ın `image_url`'ü DEĞİL:
        {"type":"image","source":{"type":"base64","media_type":..., "data": <b64>}}
    Yalnızca BEDROCK_ENABLED ve anthropic paketi mevcutken çağrılmalı (çağıran kontrol
    eder). Hata durumunda _claude_chat ile aynı Türkçe RuntimeError'ları fırlatır;
    çağıranlar fail-open/fallback için yakalar."""
    import base64
    if media_type not in ("image/jpeg", "image/png", "image/webp", "image/gif"):
        media_type = "image/jpeg"
    b64 = base64.b64encode(image_bytes).decode("utf-8")
    content = [
        {"type": "text", "text": prompt},
        {"type": "image", "source": {"type": "base64", "media_type": media_type, "data": b64}},
    ]
    try:
        payload = dict(model=BEDROCK_MODEL,
                       max_tokens=min(max_tokens, BEDROCK_MAX_TOKENS),
                       messages=[{"role": "user", "content": content}],
                       temperature=temperature)
        with ai_provider_call.admit(feature=feature, provider="bedrock",
                                    payload=payload) as call:
            resp = call.create(bedrock_client.messages.create)
        for block in resp.content:
            if getattr(block, "type", None) == "text":
                return block.text
        return ""
    except AISpendLimitExceeded:
        raise
    except anthropic.RateLimitError:
        raise RuntimeError("AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise RuntimeError("AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except anthropic.APIError as e:
        logger.warning("Bedrock görsel doğrulama APIError: %s", e)
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")


def _completion_from_text(text, *, fallback_used=False):
    meta = getattr(_completion_tls, "last", None)
    if isinstance(meta, ChatCompletion) and meta.text == text:
        return ChatCompletion(
            text=text,
            truncated=meta.truncated,
            finish_reason=meta.finish_reason,
            provider=meta.provider,
            fallback_used=fallback_used,
        )
    return ChatCompletion(text=text or "", fallback_used=fallback_used)


def _heavy_complete(messages, system_prompt=None, max_tokens=1024, temperature=0.7,
                    feature="other"):
    """Like `_heavy_chat` but keeps finish/truncation metadata for generation."""
    _completion_tls.last = None
    lg_key = ai_recovery.lastgood_key(
        "heavy_chat", BEDROCK_MODEL, system_prompt or "", messages, max_tokens)
    fallback_used = False
    if BEDROCK_ENABLED and anthropic is not None:
        try:
            reply = ai_recovery.call_with_recovery(
                lambda: _claude_chat(messages, system_prompt=system_prompt,
                                     max_tokens=max_tokens, temperature=temperature,
                                     feature=feature),
                feature="heavy_chat.bedrock")
            logger.info("[AI] sağlayıcı: Bedrock (Claude Sonnet)")
            ai_recovery.remember_last_good(lg_key, reply)
            return _completion_from_text(reply, fallback_used=False)
        except AISpendLimitExceeded:
            # A spend ceiling is not a provider failure: falling back to OpenAI
            # would keep spending after the boundary said stop.
            raise
        except Exception as e:
            fallback_used = True
            logger.warning("Bedrock/Claude çağrısı başarısız, Haiku'ya düşülüyor: %s: %s",
                           type(e).__name__, e)
    try:
        logger.info("[AI] sağlayıcı: Bedrock Haiku (light)")
        reply = ai_recovery.call_with_recovery(
            lambda: _openai_chat(messages, system_prompt=system_prompt,
                                 max_tokens=max_tokens, temperature=temperature,
                                 feature=feature),
            feature="heavy_chat.haiku")
        ai_recovery.remember_last_good(lg_key, reply)
        return _completion_from_text(reply, fallback_used=fallback_used)
    except AISpendLimitExceeded:
        raise
    except Exception:
        cached = ai_recovery.recall_last_good(lg_key)
        if cached is not None:
            logger.warning("[AI] her iki sağlayıcı da başarısız — son-iyi (last-good) yanıt sunuldu")
            return ChatCompletion(
                text=cached, truncated=False, finish_reason="last_good",
                provider="cache", fallback_used=True)
        raise


def _heavy_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7,
                feature="other"):
    """Ağır görev yönlendiricisi: Bedrock açıksa Claude Sonnet'e gider, aksi halde veya
    herhangi bir hatada OpenAI'ya şeffafça düşer. İmza `_openai_chat` ile aynıdır, böylece
    çağrı noktaları yalnızca `_openai_chat(` → `_heavy_chat(` rename'iyle taşınır.
    Hangi sağlayıcının cevap verdiğini `[AI]` etiketli INFO satırıyla loglar (gözlemlenebilirlik).

    WS9 kurtarma: her sağlayıcı çağrısı geçici hatalarda (TransientAIError)
    sınırlı jitter'lı yeniden denenir (call_with_recovery); Bedrock kalıcı hatada
    OpenAI'ya düşer; HER İKİSİ de düşerse son-iyi (last-good) yanıt döner, o da
    yoksa dostça RuntimeError yükselir (çağıranın mevcut fallback'i)."""
    return _heavy_complete(
        messages, system_prompt=system_prompt,
        max_tokens=max_tokens, temperature=temperature, feature=feature).text
