# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import logging

from openai import APIConnectionError, APIError, APITimeoutError, RateLimitError

try:
    import anthropic  # Bedrock/Claude (ağır görevler)
except Exception:  # paket yoksa Bedrock zaten BEDROCK_ENABLED ile kapalı kalır
    anthropic = None

from app.config import BEDROCK_ENABLED, BEDROCK_MAX_TOKENS, BEDROCK_MODEL, OPENAI_MODEL
from app.extensions import bedrock_client, openai_client
from app.services import ai_recovery
from app.services.ai_gate import model_concurrency_slot
from app.services.ai_recovery import TransientAIError

logger = logging.getLogger(__name__)


# WS4: şablon app/prompts/nutrition.py'ye taşındı; eski import yolu
# (meallog/ai_nutrition `from app.services.ai import PORTION_SANITY_RULE`) korunur.
from app.prompts.nutrition import PORTION_SANITY_RULE  # noqa: E402,F401 (re-export)


def _openai_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7):
    """Merkezi LLM sohbet çağrısı (OpenAI Chat Completions).

    `messages` Anthropic ile uyumlu [{"role","content"}] listesidir; system_prompt
    varsa başa bir system mesajı olarak eklenir. Hata durumunda kullanıcı-dostu bir
    RuntimeError fırlatır; çağıranlar bunu kendi try/except fallback'leriyle yakalar.
    """
    full_messages = []
    if system_prompt:
        full_messages.append({"role": "system", "content": system_prompt})
    full_messages.extend(messages)
    try:
        # Slot yalnızca gerçek ağ çağrısını sarar — retry/backoff uykular ve
        # sağlayıcı geçişi slotsuz kalır (triage 2026-07-19 #3, ai_coach deseni).
        with model_concurrency_slot("openai"):
            resp = openai_client.chat.completions.create(
                model=OPENAI_MODEL,
                messages=full_messages,
                max_tokens=max_tokens,
                temperature=temperature,
            )
        # `choices` içerik filtresinde boş, `message.content` ise refuse/length
        # durumlarında None olabilir. Çağıranların çoğu dönüşe doğrudan .strip()
        # uyguluyor; ham IndexError/None'ı buraya hapsedip her zaman str döndür.
        if not resp.choices:
            logger.warning("OpenAI yanıtı boş choices döndürdü (içerik filtresi olası)")
            return ""
        choice = resp.choices[0]
        if getattr(choice, "finish_reason", None) == "length":
            # Yanıt max_tokens sınırında kesildi: çıktı eksik/bozuk olabilir.
            # Sessizce yutulmasın — çağıranların parse hataları bu uyarıyla
            # ilişkilendirilebilsin (docs/menu-extraction-truncation-risk.md).
            logger.warning("OpenAI yanıtı max_tokens=%s sınırında kesildi (finish_reason=length)", max_tokens)
        return choice.message.content or ""
    except RateLimitError:
        # Geçici: kurtarma katmanı (call_with_recovery) yeniden dener. Metin
        # dostça ve RuntimeError alt sınıfı → mevcut çağıran fallback'leri korunur.
        raise TransientAIError("AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (APITimeoutError, APIConnectionError):
        raise TransientAIError("AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except APIError as e:
        # Ham sağlayıcı hatası kullanıcıya sızmasın (iç ayrıntı/anahtar metası
        # içerebilir); detayı logla, kullanıcıya jenerik mesaj dön.
        logger.warning("OpenAI APIError: %s", e)
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")


def _claude_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7):
    """Ağır görev LLM çağrısı (Claude Sonnet 4.5 — Amazon Bedrock, Messages API).

    `_openai_chat` ile AYNI imzayı taşır; OpenAI-stili argümanları Anthropic'e çevirir:
      • system_prompt ve messages içindeki her {"role":"system"} üst düzey `system=`
        paramına taşınır (Anthropic system rolünü messages içinde kabul etmez).
      • max_tokens, Anthropic'in zorunlu kıldığı sınır için BEDROCK_MAX_TOKENS'a clamp'lenir.
      • Yanıt, ilk text content bloğunun metnidir.
    Hata durumunda `_openai_chat` ile birebir aynı Türkçe RuntimeError'ları fırlatır;
    çağıran (_heavy_chat) bunları yakalayıp OpenAI'ya düşer.
    """
    sys_parts = [system_prompt] if system_prompt else []
    convo = []
    for m in messages:
        if m.get("role") == "system":
            sys_parts.append(m.get("content", ""))
        else:
            convo.append(m)
    system = "\n\n".join(p for p in sys_parts if p)
    capped = min(max_tokens, BEDROCK_MAX_TOKENS)
    try:
        kwargs = dict(model=BEDROCK_MODEL, max_tokens=capped,
                      messages=convo, temperature=temperature)
        if system:
            kwargs["system"] = system
        with model_concurrency_slot("bedrock"):
            resp = bedrock_client.messages.create(**kwargs)
        if getattr(resp, "stop_reason", None) == "max_tokens":
            logger.warning("Claude yanıtı max_tokens=%s sınırında kesildi (stop_reason=max_tokens)", capped)
        for block in resp.content:
            if getattr(block, "type", None) == "text":
                return block.text
        return ""
    except anthropic.RateLimitError:
        # Geçici: kurtarma katmanı yeniden dener (TransientAIError, RuntimeError alt sınıfı).
        raise TransientAIError("AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise TransientAIError("AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except anthropic.APIError as e:  # APIStatusError bunun alt sınıfıdır — tek except yeter
        logger.warning("Claude/Bedrock APIError: %s", e)
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")


def _image_block(image_bytes, media_type):
    import base64
    if media_type not in ("image/jpeg", "image/png", "image/webp", "image/gif"):
        media_type = "image/jpeg"
    return {
        "type": "image",
        "source": {
            "type": "base64",
            "media_type": media_type,
            "data": base64.b64encode(image_bytes).decode("utf-8"),
        },
    }


def _bedrock_image_message(content, max_tokens, temperature):
    try:
        with model_concurrency_slot("bedrock"):
            resp = bedrock_client.messages.create(
                model=BEDROCK_MODEL,
                max_tokens=min(max_tokens, BEDROCK_MAX_TOKENS),
                messages=[{"role": "user", "content": content}],
                temperature=temperature,
            )
        for block in resp.content:
            if getattr(block, "type", None) == "text":
                return block.text
        return ""
    except anthropic.RateLimitError:
        raise RuntimeError("AI servisi \u015fu an yo\u011fun (rate limit). L\u00fctfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise RuntimeError("AI servisine ula\u015f\u0131lamad\u0131 (zaman a\u015f\u0131m\u0131). L\u00fctfen tekrar deneyin.")
    except anthropic.APIError:
        logger.warning("bedrock_image_request_failed")
        raise RuntimeError("AI servisi hatas\u0131. L\u00fctfen tekrar deneyin.")


def _bedrock_compare_images(
        baseline_bytes, baseline_media_type,
        current_bytes, current_media_type, prompt,
        max_tokens=1200, temperature=0.0):
    content = [
        {"type": "text", "text": prompt},
        {"type": "text", "text": "Image A \u2014 baseline"},
        _image_block(baseline_bytes, baseline_media_type),
        {"type": "text", "text": "Image B \u2014 current"},
        _image_block(current_bytes, current_media_type),
    ]
    return _bedrock_image_message(content, max_tokens, temperature)


def _bedrock_validate_image(image_bytes, media_type, prompt, max_tokens=400, temperature=0.0):
    """Bedrock (Claude Sonnet) çok-kipli doğrulama: bir görsel + metin promptu gönderir,
    modelin ham metin yanıtını (genelde katı JSON) string olarak döndürür.

    Anthropic Messages API GÖRSEL BLOĞU kullanır — OpenAI'ın `image_url`'ü DEĞİL:
        {"type":"image","source":{"type":"base64","media_type":..., "data": <b64>}}
    Yalnızca BEDROCK_ENABLED ve anthropic paketi mevcutken çağrılmalı (çağıran kontrol
    eder). Hata durumunda _claude_chat ile aynı Türkçe RuntimeError'ları fırlatır;
    çağıranlar fail-open/fallback için yakalar."""
    import base64
    if media_type not in ("image/jpeg", "image/png", "image/webp", "image/gif"):
        media_type = "image/jpeg"
    b64 = base64.b64encode(image_bytes).decode("utf-8")
    content = [
        {"type": "text", "text": prompt},
        {"type": "image", "source": {"type": "base64", "media_type": media_type, "data": b64}},
    ]
    try:
        with model_concurrency_slot("bedrock"):
            resp = bedrock_client.messages.create(
                model=BEDROCK_MODEL,
                max_tokens=min(max_tokens, BEDROCK_MAX_TOKENS),
                messages=[{"role": "user", "content": content}],
                temperature=temperature,
            )
        for block in resp.content:
            if getattr(block, "type", None) == "text":
                return block.text
        return ""
    except anthropic.RateLimitError:
        raise RuntimeError("AI servisi şu an yoğun (rate limit). Lütfen biraz sonra tekrar deneyin.")
    except (anthropic.APITimeoutError, anthropic.APIConnectionError):
        raise RuntimeError("AI servisine ulaşılamadı (zaman aşımı). Lütfen tekrar deneyin.")
    except anthropic.APIError as e:
        logger.warning("Bedrock görsel doğrulama APIError: %s", e)
        raise RuntimeError("AI servisi hatası. Lütfen tekrar deneyin.")


def _heavy_chat(messages, system_prompt=None, max_tokens=1024, temperature=0.7):
    """Ağır görev yönlendiricisi: Bedrock açıksa Claude Sonnet'e gider, aksi halde veya
    herhangi bir hatada OpenAI'ya şeffafça düşer. İmza `_openai_chat` ile aynıdır, böylece
    çağrı noktaları yalnızca `_openai_chat(` → `_heavy_chat(` rename'iyle taşınır.
    Hangi sağlayıcının cevap verdiğini `[AI]` etiketli INFO satırıyla loglar (gözlemlenebilirlik).

    WS9 kurtarma: her sağlayıcı çağrısı geçici hatalarda (TransientAIError)
    sınırlı jitter'lı yeniden denenir (call_with_recovery); Bedrock kalıcı hatada
    OpenAI'ya düşer; HER İKİSİ de düşerse son-iyi (last-good) yanıt döner, o da
    yoksa dostça RuntimeError yükselir (çağıranın mevcut fallback'i)."""
    # Son-iyi anahtarı içerik-bazlı: iki farklı kullanıcı ancak birebir aynı
    # girdiyi gönderirse aynı yanıtı paylaşır (saf girdi-fonksiyonu → sızıntı yok).
    lg_key = ai_recovery.lastgood_key(
        "heavy_chat", BEDROCK_MODEL, system_prompt or "", messages, max_tokens)
    # Model slotu BURADA alınmaz: retry uykuları + Bedrock→OpenAI geçişi boyunca
    # slot rehin kalıp ilgisiz AI işini serileştirirdi (triage 2026-07-19 #3).
    # Slot, her sağlayıcının kendi create() çağrısını sarar (_claude_chat/_openai_chat).
    if BEDROCK_ENABLED and anthropic is not None:
        try:
            reply = ai_recovery.call_with_recovery(
                lambda: _claude_chat(messages, system_prompt=system_prompt,
                                     max_tokens=max_tokens, temperature=temperature),
                feature="heavy_chat.bedrock")
            logger.info("[AI] sağlayıcı: Bedrock (Claude Sonnet)")
            ai_recovery.remember_last_good(lg_key, reply)
            return reply
        except Exception as e:  # RuntimeError dahil her şey → OpenAI'ya düş (istek bozulmasın)
            logger.warning("Bedrock/Claude çağrısı başarısız, OpenAI'ya düşülüyor: %s: %s",
                           type(e).__name__, e)
    try:
        logger.info("[AI] sağlayıcı: OpenAI (%s)", OPENAI_MODEL)
        reply = ai_recovery.call_with_recovery(
            lambda: _openai_chat(messages, system_prompt=system_prompt,
                                 max_tokens=max_tokens, temperature=temperature),
            feature="heavy_chat.openai")
        ai_recovery.remember_last_good(lg_key, reply)
        return reply
    except Exception:
        cached = ai_recovery.recall_last_good(lg_key)
        if cached is not None:
            logger.warning("[AI] her iki sağlayıcı da başarısız — son-iyi (last-good) yanıt sunuldu")
            return cached
        raise
