# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import json
import re
import s3_helper
import nutrition_pipeline
from datetime import datetime, timedelta
from flask import current_app, g, session
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.attributes import flag_modified

from app.config import (BEDROCK_ENABLED, BEDROCK_MAX_TOKENS, BEDROCK_MODEL,
                        BEDROCK_PROMPT_CACHE, OPENAI_MODEL)
from app.extensions import bedrock_client, db, openai_client
from app.models import (WORKOUT_COMPLETION_MARKER, DailyActivity, MealLog,
                        PendingAction, PumpCheck, User, UserSession, WaterLog,
                        WeeklyCheckIn, WeeklyLog, WorkoutLog)
from app.services.ai import _bedrock_validate_image, _heavy_chat, anthropic as _anthropic
from app.services.ai_nutrition import _food_search_llm, _is_relevant_food, _normalize_food_query_en
from app.services.fatsecret import _food_search_fatsecret, _food_search_static
from app.services.gamification import _claim_quest, award_xp, log_activity
from app.timeutil import app_date_of, app_today, day_key, utc_day_bounds


COACH_SYSTEM_PROMPT = """Sen AxisAI uygulamasının elit, destekleyici ama gerçekçi AI Beslenme & Fitness Koçusun. Kullanıcının veritabanına HEM okuma HEM yazma erişimin var ve bunu ARAÇLAR (function calling) üzerinden yaparsın.

VERİ KAYNAKLARIN:
- Beslenme verileri FatSecret API'den geliyor — makroları ASLA tahmin etme, daima aracı çağır.
- Günlük aktivite verileri Apple Health (HealthKit) ve Android Health Connect'ten senkronize edilir ve [GÜNLÜK AKTİVİTE] bloğunda sana sağlanır (adım, mesafe, yakılan kalori).
- HER istekte kullanıcının güncel verisi sana verilir: [KULLANICI PROFİLİ & HAFIZA] (sakatlık, beslenme kısıtları, ekipman, hedefler), [HAFTALIK CHECK-IN TRENDİ] (uyku kalitesi, yorgunluk, progresif yüklenme, beslenme uyumu) ve [GÜNLÜK AKTİVİTE]. Önerilerini DAİMA bu verilere dayandır; zaten verilmiş bu bilgileri kullanıcıya tekrar SORMA.
- Bu verileri analiz ederek kişiye özel, veri odaklı önerilerde bulun.

═══ BESLENME LOGLAMA İŞ AKIŞI (ÇOK ÖNEMLİ) ═══
Kullanıcı bir yiyecek/içecek YEDİĞİNİ söylediğinde VEYA makrolarını/kalorisini sorduğunda:
1. DAİMA önce `fetch_nutrition_and_stage_log` aracını çağır — gerçek makroları FatSecret'tan çeker ve onaya hazır şekilde geçici olarak hazırlar. Bu araç KAYDETMEZ, sadece veriyi getirir.
2. Dönen makroları kullanıcıya KISA ve NET sun (kalori | P | K | Y + porsiyon), sonra AÇIKÇA onay iste: "Günlüğüne kaydedeyim mi?". Araç bir `evaluation.compatibility_score` (0-100) döndürürse onu da AYNEN aktar.
3. Kullanıcı onaylarsa ("evet", "kaydet", "olur" vb.) `confirm_and_commit_meal_log` aracını çağır. Onay GELMEDEN asla bu aracı çağırma — merak amaçlı sorular yanlışlıkla loglanmamalı.
4. Kullanıcı reddederse/iptal ederse ("hayır", "iptal", "vazgeç") `cancel_pending_log` aracını çağır.
ÖNEMLİ: Yiyecek önerirken veya değerlendirirken [KULLANICI PROFİLİ & HAFIZA]'daki dietary_restrictions'a (alerji/intolerans/diyet) MUTLAKA uy — kısıtlı besinleri ASLA önerme, uygun alternatif sun.
Antrenman için aynı mantık: `stage_workout_log` → onay → `confirm_and_commit_workout_log`.

═══ SAKATLIK KONTROLÜ (ANTRENMAN PLANLAMADAN ÖNCE) ═══
Kullanıcı bir antrenman planı/programı ister VEYA egzersiz önerisi beklerken:
1. Kayıtlı sakatlık/tıbbi durum [KULLANICI PROFİLİ & HAFIZA]'daki "injuries" alanında SANA ZATEN VERİLİR — önce oraya bak, gereksiz araç çağrısı yapma. (Yalnızca bu blok hiç gelmediyse `manage_user_memory` `action="get", key="injuries"` ile oku.)
2. "injuries" KAYIT YOK ise: plan üretimini DURDUR ve kullanıcıya sakatlık/tıbbi durumunu sor (ör. "Menisküs, Kifoz, Skolyoz gibi bir durumun var mı? Yoksa 'Hiçbiri' yaz."). Cevabı almadan egzersiz önerme.
3. Kullanıcı cevap verince `manage_user_memory` aracını `action="update", key="injuries"` ile çağırıp KAYDET.
4. injuries doluysa bu kısıtlara MUTLAKA uy: egzersiz seçimi, hacim ve şiddeti sakatlığı tamamen koruyacak şekilde uyarla (ör. Menisküs → ağır squat/lunge yerine leg press/box squat ve düşük-darbe; Kifoz → arka zincir + ekstansiyon vurgusu, ağır overhead'den kaçın). "Hiçbiri" ise normal planla.

═══ DİĞER ARAÇLAR ═══
- Kullanıcının geçmiş metriklerini (kalori, su, kilo, kaldırılan hacim) sorgulamak için `query_fitx_metrics` aracını kullan — sayıları tahmin etme. Uyku SÜRESİ (saat) takibi yoktur; ancak subjektif uyku kalitesi (1-5) [HAFTALIK CHECK-IN TRENDİ]'nde verilir, oradan oku.
- Antrenman şiddetini [HAFTALIK CHECK-IN TRENDİ]'ne göre ayarla: uyku kalitesi düşük (≤2) veya yorgunluk yüksek (≥4) ise hacmi/şiddeti düşür ve deload/toparlanma öner; progresif yüklenme "hayir" ise küçük bir yük/tekrar artışı ya da teknik odağı öner.
- Kullanıcı bir spor salonu/antrenman fotoğrafı (S3 anahtarı) paylaşırsa `analyze_gym_photo` ile doğrula.
- Uzun süreli tercihleri (hedefler, ekipman) `manage_user_memory` ile sakla/oku.

═══ ÇEŞİTLİLİK DİREKTİFİ (ZORUNLU) ═══
ASLA monoton, tekrarlayan "tavuk + pirinç" gibi sıkıcı seçeneklere yönlendirme. Bunun yerine aktif olarak:
- Mikro besin yoğunluğunu öne çıkar (renkli sebzeler, yapraklılar, vitamin/mineral kaynakları).
- Lif alımını teşvik et (bakliyat, tam tahıl, sebze-meyve).
- Sağlıklı yağları öner (zeytinyağı, avokado, kuruyemiş, yağlı balık — omega-3).
- Çeşit sun: aynı makroyu farklı, lezzetli ve yöresel/global alternatiflerle ver.
- Popüler zincir/kafe ürünlerini (Starbucks, yerel kafeler, fast-food) değerlendirirken dürüst ol; daha besleyici, dengeli alternatifler öner.

TEMEL GÖREV:
- Beslenme sorularında gerçek FatSecret makrolarını kullan, tahmin etme.
- Araçların döndürdüğü makrolar ve `compatibility_score` DETERMİNİSTİK olarak sunucuda hesaplanır; bu sayıları ASLA değiştirme, yeniden hesaplama veya yuvarlama — yalnızca AYNEN sun ve yorumla.
- Trendleri, eksik logları ve başarıları proaktif olarak belirt.
- Haftalık rapor günlerinde (Pazartesi/Pazar) otomatik rapor sun.

RESTORAN MENÜ ANALİZİ:
- Restoran menülerini analiz ederken metabolik hassasiyet ve kullanıcının aktif hedeflerini her şeyin üstünde tut.
- Objektif ol, restoran pazarlama abartılarını filtrele.
- Sporcuyu masadaki en akıllı taktiksel yemeğe yönlendir.
- Kalan günlük makro bütçesine göre somut önerilerde bulun.
- Porsiyon boyutları ve gizli kaloriler konusunda uyar.

YANIT FORMATI:
- Yanıtlarını modern UI'a uygun yaz: taranabilir kısa bloklar, madde listeleri, net başlıklar.
- Uzun paragraflar yerine aksiyon odaklı kısa maddeler kullan.

KURALLAR:
- Kısa, net, samimi ve veri odaklı konuş.
- Genel geçer tavsiye VERME — her yanıt kullanıcının verisine dayansın.
- Emin olmadığın tıbbi konularda doktora yönlendir. Tıbbi teşhis veya reçete VERME.
- Kas kazanma hedefinde kilo artışı OLUMLU, kilo vermede azalış OLUMLU.
- Tonu: elit, destekleyici, veri odaklı."""


# Kullanıcı diline göre çıktı direktifi. Sistem promptunun gövdesi (talimatlar,
# araç akışları) Türkçe kalır — model Türkçe talimatı okuyup İngilizce yanıtlayabilir;
# kritik olan ÇIKTI dilini net dayatmaktır.
_COACH_LANG_DIRECTIVE = {
    "tr": ("═══ DİL ═══\n"
           "- Yanıtının TAMAMINI Türkçe yaz; kullanıcıya \"sen\" diye hitap et. "
           "Veriler veya talimatlar başka dilde olsa bile Türkçe yanıt ver."),
    "en": ("═══ LANGUAGE ═══\n"
           "- Write your ENTIRE response in English; address the user as \"you\". "
           "Even though the user's data, the context blocks (e.g. [KULLANICI PROFİLİ], "
           "[GÜNLÜK AKTİVİTE]) and these instructions are written in Turkish, you MUST "
           "reply ONLY in English. Translate any Turkish labels/values into natural "
           "English. Do not output Turkish words."),
}

# Sağlayıcı hatasında gösterilen dostça yedek metinler (dile göre).
_COACH_FALLBACKS = {
    "tr": {"error": "Bir şeyler ters gitti, tekrar dener misin?",
           "tool": "İşlemi tamamlayamadım, tekrar dener misin?"},
    "en": {"error": "Something went wrong — could you try again?",
           "tool": "I couldn't complete that — could you try again?"},
}


def _coach_lang(language):
    return language if language in ("tr", "en") else "tr"


def build_coach_system(language="tr"):
    """Koç sistem promptu + dile özgü çıktı direktifi (TR/EN)."""
    return COACH_SYSTEM_PROMPT + "\n\n" + _COACH_LANG_DIRECTIVE[_coach_lang(language)]


def _assert_principal(user_id):
    """Savunma derinliği: in-process koç/MCP araçları yalnızca kimliği doğrulanmış
    kullanıcı için çalışmalı. user_id ASLA LLM'den gelmez; yine de bir istek
    bağlamında çağrıldıysak current_user ile eşleştiğini doğrula (gelecekteki bir
    yanlış kullanım çapraz-kullanıcı okuma/yazmaya dönüşmesin)."""
    from flask import has_request_context
    from flask_login import current_user
    if has_request_context() and getattr(current_user, "is_authenticated", False) \
            and current_user.id != user_id:
        raise PermissionError("user_id, kimliği doğrulanmış kullanıcıyla eşleşmiyor")


def _fetch_profile_and_trends(user_id):
    """Kullanıcının uzun-süreli profilini ve kendi bildirdiği trendleri bağlama
    enjekte eder; böylece koç HER yanıtta kullanıcının gerçek verisine dayanır,
    yalnızca anlık loglara değil. SQLAlchemy ORM ile DOĞRUDAN okur (fitx_mcp /
    psycopg2'ye bağlı değil) → lokal/SQLite ortamında da çalışır. Her bölüm kendi
    try/except'inde: bir sorgu patlarsa diğer bölümler yine de döner."""
    parts = []

    # [KULLANICI PROFİLİ & HAFIZA] — manage_user_memory ile yazılan kalıcı veriler.
    # injuries/dietary_restrictions BOŞ olsa bile açıkça belirt: koç sakatlığı
    # sormalı, kısıtlama yokken de bunu bilerek serbest öneri yapabilmeli.
    try:
        user = db.session.get(User, user_id)
        meta = dict((user.user_metadata or {}) if user else {})
        lines = [
            f"- sakatlık/tıbbi durum (injuries): {meta.get('injuries') or 'KAYIT YOK — plan vermeden önce kullanıcıya sor'}",
            f"- beslenme kısıtları (dietary_restrictions): {meta.get('dietary_restrictions') or 'kayıt yok'}",
        ]
        for key in ("equipment_available", "fitness_goals", "preferences"):
            if meta.get(key):
                lines.append(f"- {key}: {meta[key]}")
        if user and user.target_weight:
            lines.append(f"- hedef kilo (target_weight): {user.target_weight} kg")
        if user and user.goal_type:
            lines.append(f"- hedef tipi (goal_type): {user.goal_type}")
        parts.append("[KULLANICI PROFİLİ & HAFIZA]\n" + "\n".join(lines))
        # Kayıtlı sakatlık varsa KATI, yapısal kontrendikasyon direktifini de enjekte
        # et — form jeneratörüyle AYNI motor (app/services/injury_constraints). Böylece
        # koç "hangi hareketler yasak / güvenli alternatif ne" konusunda tutarlı kalır.
        from app.services import injury_constraints
        directive = injury_constraints.build_injury_directive(meta.get("injuries"))
        if directive:
            parts.append(directive.strip())
    except Exception:
        current_app.logger.warning("[COACH] profil/hafıza bağlamı alınamadı", exc_info=True)

    # [HAFTALIK CHECK-IN TRENDİ] — kullanıcının kendi bildirdiği toparlanma/uyum
    # sinyalleri (uyku, yorgunluk, progresif yüklenme, beslenme uyumu). Antrenman
    # şiddeti/deload kararları bunlara dayanmalı.
    try:
        checkins = (WeeklyCheckIn.query.filter_by(user_id=user_id)
                    .order_by(WeeklyCheckIn.created_at.desc()).limit(4).all())
        if checkins:
            rows = []
            for c in checkins:
                # B13: naive-UTC created_at.date() yerine Istanbul gününü kullan;
                # 00:00–03:00 arası yazılan kayıt bir gün erken etiketlenmesin.
                d = app_date_of(c.created_at).isoformat() if c.created_at else "?"
                line = (f"- {d}: kilo {c.weight}kg | yoğunluk {c.yogunluk}/5 | "
                        f"yorgunluk {c.fatigue}/5 | uyku kalitesi {c.uyku_kalitesi}/5 | "
                        f"beslenme uyumu {c.beslenme_uyumu}/5 | progresif yüklenme: "
                        f"{c.progressive_overload or '?'}")
                if c.note:
                    line += f" | not: {c.note}"
                rows.append(line)
            parts.append(f"[HAFTALIK CHECK-IN TRENDİ (son {len(rows)}, yeni→eski)]\n"
                         + "\n".join(rows))
    except Exception:
        current_app.logger.warning("[COACH] haftalık check-in bağlamı alınamadı", exc_info=True)

    # [GÜNLÜK AKTİVİTE (7 gün)] — Apple Health / Health Connect senkronu (adım,
    # mesafe, yakılan kalori). Toplam enerji harcaması resmini tamamlar.
    try:
        lo = (app_today() - timedelta(days=6)).isoformat()
        hi = app_today().isoformat()
        rows = DailyActivity.query.filter(
            DailyActivity.user_id == user_id,
            DailyActivity.date_key >= lo, DailyActivity.date_key <= hi).all()
        if rows:
            steps = sum(r.steps or 0 for r in rows)
            kcal = sum(r.calories_burned or 0 for r in rows)
            dist = sum(r.distance_km or 0 for r in rows)
            active_days = len({r.date_key for r in rows})
            parts.append(
                "[GÜNLÜK AKTİVİTE (7 gün)]\n"
                f"- toplam adım: {steps} | yakılan kalori: {round(kcal)} kcal | "
                f"mesafe: {round(dist, 1)} km | aktif gün: {active_days}/7")
    except Exception:
        current_app.logger.warning("[COACH] günlük aktivite bağlamı alınamadı", exc_info=True)

    return parts


def _fetch_coach_context(user_id, question="", language="tr"):
    _assert_principal(user_id)
    # Not: Beslenme makroları artık koç araçları (fetch_nutrition_and_stage_log)
    # üzerinden tek yoldan gelir; burada FatSecret verisi enjekte ETMİYORUZ ki
    # model rakip bir veri kaynağı görüp staging adımını atlamasın.
    from fitx_mcp.server import (
        get_user_fitness_summary,
        get_user_workout_history,
        get_user_supplement_stack,
        get_friend_activities,
        get_user_nutrition_log,
    )
    parts = []
    try:
        parts.append(f"[FITNESS ÖZETİ]\n{get_user_fitness_summary(user_id)}")
    except Exception:
        current_app.logger.warning("[COACH] fitness özeti alınamadı", exc_info=True)
        parts.append("[FITNESS ÖZETİ] Veri alınamadı.")
    # Kalıcı profil + kendi bildirdiği trendler (sakatlık, beslenme kısıtı, uyku/
    # yorgunluk, günlük aktivite). MCP'den BAĞIMSIZ — doğrudan ORM ile okunur.
    parts.extend(_fetch_profile_and_trends(user_id))
    try:
        parts.append(f"[ANTRENMAN GEÇMİŞİ (7 gün)]\n{get_user_workout_history(user_id, 7)}")
    except Exception:
        current_app.logger.warning("[COACH] antrenman geçmişi alınamadı", exc_info=True)
    try:
        parts.append(f"[SUPPLEMENT STACK]\n{get_user_supplement_stack(user_id)}")
    except Exception:
        current_app.logger.warning("[COACH] supplement stack alınamadı", exc_info=True)
    try:
        parts.append(f"[BESLENME LOGU (3 gün)]\n{get_user_nutrition_log(user_id, 3)}")
    except Exception:
        current_app.logger.warning("[COACH] beslenme logu alınamadı", exc_info=True)
    try:
        parts.append(f"[ARKADAŞ AKTİVİTELERİ]\n{get_friend_activities(user_id)}")
    except Exception:
        current_app.logger.warning("[COACH] arkadaş aktiviteleri alınamadı", exc_info=True)

    from analytics_engine import get_nudges
    try:
        models = {
            "WorkoutLog": WorkoutLog,
            "MealLog": MealLog,
            "UserSession": UserSession,
            "WeeklyCheckIn": WeeklyCheckIn,
            "WaterLog": WaterLog,
        }
        nudges = get_nudges(db.session.get(User, user_id), db, models,
                            getattr(g, "prev_last_login", None), language=language)
        if nudges:
            parts.append("[PROAKTİF BİLDİRİMLER]\n" + "\n".join(nudges))
    except Exception:
        current_app.logger.warning("[COACH] proaktif bildirimler alınamadı", exc_info=True)

    return "\n\n".join(parts)


_GRAMS_RE = re.compile(r"(\d+(?:[.,]\d+)?)\s*(?:g|gr|gram)\b", re.IGNORECASE)


def _extract_grams(text):
    """Sorgudan gram miktarını yakala (ör. '300g tavuk' → 300.0). Yoksa None."""
    m = _GRAMS_RE.search(text or "")
    if m:
        try:
            val = float(m.group(1).replace(",", "."))
            if 0 < val <= 5000:
                return val
        except ValueError:
            pass
    return None


def _coach_search_food(query):
    """Birleşik besin araması — alaka-kapısı + TR→EN normalizasyonlu.

    1) Ham sorguyla FatSecret dene (İngilizce sorgular ve marka adları doğrudan
       eşleşir). Sonuçları ALAKA filtresinden geçir: FatSecret eşleyemediği
       Türkçe sorgulara ilgisiz jenerik besin döndürdüğü için ('patates
       kızartması' → 'Soy Nuts') ad-token örtüşmesi olmayanları ele.
    2) Alakalı sonuç yoksa sorguyu İngilizce'ye çevirip tekrar dene — FatSecret
       verisi ağırlıklı İngilizce, Türkçe serbest metin nadiren eşleşir.
    3) Son çare: statik Türkçe tablo, sonra LLM tahmini.
    Hepsi 100g bazlı 'per_100g' makroları içerir."""
    raw = (query or "").strip()

    relevant = [r for r in (_food_search_fatsecret(raw) or [])
                if _is_relevant_food(raw, r.get("name", ""))]
    if relevant:
        return relevant

    english = _normalize_food_query_en(raw)
    if english and english.lower() != raw.lower():
        relevant = [r for r in (_food_search_fatsecret(english) or [])
                    if _is_relevant_food(english, r.get("name", ""))]
        if relevant:
            return relevant

    return _food_search_static(raw) or _food_search_llm(english or raw) or []


def _today_nutrition_totals(user_id):
    """Bugünün beslenme toplamları (MealLog — tek kanonik beslenme defteri).
    menu.py'deki 'consumed' ile AYNI tarih anahtarını (utcnow %d.%m) kullanır ki
    koçun 'kalan bütçe'si ile menü analizinin 'kalanı' birebir tutarlı olsun.
    (Faz C tarih semantiğini tüm okuyucularda birlikte ISO/Istanbul'a taşıyacak.)"""
    today_key = day_key()
    row = db.session.query(
        db.func.coalesce(db.func.sum(MealLog.kalori), 0),
        db.func.coalesce(db.func.sum(MealLog.protein), 0),
        db.func.coalesce(db.func.sum(MealLog.karb), 0),
        db.func.coalesce(db.func.sum(MealLog.yag), 0),
        db.func.count(MealLog.id),
    ).filter(
        MealLog.user_id == user_id,
        MealLog.tarih == today_key,
    ).first()
    return {
        "calories": round(row[0]),
        "protein": round(row[1], 1),
        "carbs": round(row[2], 1),
        "fat": round(row[3], 1),
        "entry_count": row[4],
    }


def _remaining_macros_for_user(user_id):
    """Kullanicinin bugun KALAN gunluk makro butcesi.

    UserSession hedef kalorisinden hedef-makro dagilimi (analyze_menu ile ayni
    formul) cikarilir, bugun MealLog'a islenen tuketim dusulur.
    Deterministik; LLM yok. Profil/hedef yoksa None doner.
    """
    sess = (UserSession.query.filter_by(user_id=user_id)
            .order_by(UserSession.created_at.desc()).first())
    if not sess or not sess.target_calories:
        return None
    target_cal = sess.target_calories
    goal = sess.goal or ""
    protein_target = target_cal * (0.30 if goal == "kas kazanma" else 0.25) / 4
    fat_target = target_cal * 0.25 / 9
    carb_target = target_cal * (0.45 if goal == "kas kazanma" else 0.50) / 4
    consumed = _today_nutrition_totals(user_id)
    return {
        "calories": max(target_cal - consumed["calories"], 0),
        "protein": max(protein_target - consumed["protein"], 0),
        "carbs": max(carb_target - consumed["carbs"], 0),
        "fat": max(fat_target - consumed["fat"], 0),
    }


def _today_workout_totals(user_id):
    """Bugünün antrenman toplam volümü (Istanbul günü; created_at UTC olduğu için
    UTC sınırlarıyla karşılaştırılır)."""
    start, end = utc_day_bounds()
    row = db.session.query(
        db.func.coalesce(db.func.sum(WorkoutLog.volume), 0),
        db.func.count(WorkoutLog.id),
    ).filter(
        WorkoutLog.user_id == user_id,
        WorkoutLog.created_at >= start,
        WorkoutLog.created_at < end,
        # D4: UI tamamlama-işaretçisi (volume=0) gerçek egzersiz değil; koç
        # bağlamındaki "bugünkü hacim/egzersiz sayısı"nı şişirmesin (entry_count'ı
        # kabartıyordu). "Antrenman yapıldı mı" sinyali ayrı yollardan (nudge/
        # PumpCheck) hâlâ işaretçiyi görür.
        WorkoutLog.exercise_name != WORKOUT_COMPLETION_MARKER,
    ).first()
    return {"total_volume": round(row[0], 1), "entry_count": row[1]}


def _tool_fetch_nutrition_and_stage_log(user_id, food_query):
    """TOOL (staging): FatSecret'tan makro çek → PendingAction'a yaz → LLM'e döndür.
    KALICI KAYIT YAPMAZ. Durum geçişi: (yok) → staged."""
    food_query = (food_query or "").strip()
    if not food_query:
        return json.dumps({"status": "error", "message": "Yiyecek sorgusu boş."}, ensure_ascii=False)

    results = _coach_search_food(food_query)
    if not results:
        # FatSecret/fallback boş → LLM kullanıcıdan netleştirme istesin (hata yönetimi).
        return json.dumps({
            "status": "not_found",
            "message": f"'{food_query}' için besin verisi bulunamadı. Kullanıcıdan daha açık bir tanım iste (pişirme şekli, marka, miktar).",
        }, ensure_ascii=False)

    top = results[0]
    per_100g = top.get("per_100g") or top.get("macros") or {}
    grams = _extract_grams(food_query) or 100.0
    scale = grams / 100.0
    payload = {
        # B5: get(..., 0) açık None değerinde 0 vermez → float(None) TypeError.
        # `or 0` ile None/boş değerleri de 0'a indir.
        "food_name": (top.get("name") or food_query)[:200],
        "calories": round(float(per_100g.get("calories") or 0) * scale, 1),
        "protein": round(float(per_100g.get("protein") or 0) * scale, 1),
        "carbs": round(float(per_100g.get("carbs") or 0) * scale, 1),
        "fat": round(float(per_100g.get("fat") or 0) * scale, 1),
        "serving_size": f"{grams:g} g",
    }

    # Deterministik uyum degerlendirmesi (compatibility_score 0-100). Tum matematik
    # nutrition_pipeline'da yapilir; LLM yalnizca bu sabit sayilari sunar.
    remaining = _remaining_macros_for_user(user_id)
    evaluation = None
    if remaining is not None:
        evaluation = nutrition_pipeline.build_evaluation(
            food_id=top.get("food_id", ""),
            name=payload["food_name"],
            standardized_serving=payload["serving_size"],
            macros={
                "calories": payload["calories"],
                "protein": payload["protein"],
                "carbs": payload["carbs"],
                "fat": payload["fat"],
            },
            remaining=remaining,
        )

    # Tek aktif 'staged' meal: önceki bekleyenleri temizle, yenisini yaz, commit et.
    _cleanup_stale_pending(user_id)
    PendingAction.query.filter_by(user_id=user_id, action_type="log_meal").delete()
    db.session.add(PendingAction(user_id=user_id, action_type="log_meal", payload=payload))
    db.session.commit()

    return json.dumps({
        "status": "staged",
        "staged_food": payload,
        "evaluation": evaluation,
        "instruction": ("Makroları ve (varsa) compatibility_score'u kullanıcıya AYNEN, "
                        "değiştirmeden ve yeniden hesaplamadan sun — sayılar kesindir. "
                        "Sonra 'Günlüğüne kaydedeyim mi?' diye onay iste; onay gelmeden "
                        "confirm_and_commit_meal_log çağırma."),
    }, ensure_ascii=False)


def _tool_confirm_and_commit_meal_log(user_id):
    """TOOL (commit): En son staged meal'i kalıcı MealLog kaydına taşı (tek kanonik
    beslenme defteri — diyari/menü ile aynı tablo), PendingAction satırını sil.
    Durum geçişi: staged → committed."""
    pending = (PendingAction.query
               .filter_by(user_id=user_id, action_type="log_meal")
               .order_by(PendingAction.created_at.desc())
               .first())
    if not pending:
        # 'evet' dendi ama ortada bekleyen yemek yok → güvenli hata yönetimi.
        return json.dumps({
            "status": "no_pending",
            "message": "Onaylanacak bekleyen bir yemek kaydı yok. Önce kullanıcının ne yediğini öğrenip fetch_nutrition_and_stage_log çağır.",
        }, ensure_ascii=False)

    data = pending.payload or {}
    cal = float(data.get("calories", 0) or 0)
    pro = float(data.get("protein", 0) or 0)
    carb = float(data.get("carbs", 0) or 0)
    fat = float(data.get("fat", 0) or 0)
    name = (data.get("food_name") or "Yemek")[:200]

    # Staged makrolar (FatSecret/LLM kaynaklı) porsiyon-sanity kapısından geçmeden
    # kanonik deftere yazılıyordu — diyari/menü/UI hepsi kısarken koç yolu atlıyordu.
    # Fiziksel olarak imkânsız bir porsiyonu (örn. 9999 kcal) makul tavanlara kıs.
    clamped = nutrition_pipeline.clamp_serving_macros(cal, pro, carb, fat)
    if clamped != (cal, pro, carb, fat):
        current_app.logger.warning(
            "[COACH] Staged makrolar makul değil (%s) — kısılıyor %s → %s",
            name, (cal, pro, carb, fat), clamped)
        cal, pro, carb, fat = clamped

    # Satırı önce atomik 'sahiplen': eşzamanlı çift-onayda (double-confirm) yalnızca
    # biri 1 satır siler; diğeri 0 alır ve çift loglamadan döner (3.10 idempotent).
    claimed = PendingAction.query.filter_by(id=pending.id).delete(synchronize_session=False)
    if not claimed:
        db.session.rollback()
        return json.dumps({
            "status": "no_pending",
            "message": "Bu kayıt zaten işlendi.",
        }, ensure_ascii=False)

    db.session.add(MealLog(
        user_id=user_id, ogun="AI Koç", yemekler=name,
        kalori=cal, protein=pro, karb=carb, yag=fat,
        tarih=day_key(), source="coach",
    ))
    award_xp(user_id, 10)
    log_activity(user_id, "nutrition_logged", f"{name} — {round(cal)} kcal")
    db.session.commit()

    return json.dumps({
        "status": "committed",
        "logged": {
            "food_name": name, "calories": cal, "protein": pro,
            "carbs": carb, "fat": fat, "serving_size": data.get("serving_size", ""),
        },
        "xp_awarded": 10,
        "today_totals": _today_nutrition_totals(user_id),
    }, ensure_ascii=False)


_PENDING_TTL = timedelta(hours=1)


def _cleanup_stale_pending(user_id, max_age=_PENDING_TTL):
    """Onaylanmadan bayatlamış (>1 saat) bekleyen aksiyonları toplu sil (3.10).

    Onay hiç gelmeyen 'staged' kayıtlar birikip sonraki bir 'evet'te yanlış/eski
    bir yemeği loglayabilir; periyodik toplu temizlik bu riski kapatır. Commit
    çağırana bırakılmaz — kendi içinde idempotenttir, hata boğulur."""
    try:
        cutoff = datetime.utcnow() - max_age
        deleted = (PendingAction.query
                   .filter(PendingAction.user_id == user_id,
                           PendingAction.created_at < cutoff)
                   .delete(synchronize_session=False))
        if deleted:
            current_app.logger.info(
                "[PENDING] %d bayat bekleyen aksiyon temizlendi (user=%s)", deleted, user_id)
    except Exception:
        db.session.rollback()


def _tool_stage_workout_log(user_id, exercise_name, sets, reps, weight_kg):
    """TOOL (staging): Antrenmanı onaya hazırla. Kalıcı kayıt yapmaz."""
    exercise_name = (exercise_name or "").strip()
    if not exercise_name:
        return json.dumps({"status": "error", "message": "Egzersiz adı boş."}, ensure_ascii=False)
    try:
        sets = int(sets or 0)
        reps = int(reps or 0)
        weight = float(weight_kg or 0)
    except (TypeError, ValueError):
        sets, reps, weight = 3, 10, 0.0
    if sets <= 0:
        sets = 3
    if reps <= 0:
        reps = 10
    if weight < 0:
        weight = 0.0

    payload = {
        "exercise_name": exercise_name[:120],
        "sets": sets, "reps": reps, "weight_kg": weight,
        "volume": round(sets * reps * weight, 1),
    }
    _cleanup_stale_pending(user_id)
    PendingAction.query.filter_by(user_id=user_id, action_type="log_workout").delete()
    db.session.add(PendingAction(user_id=user_id, action_type="log_workout", payload=payload))
    db.session.commit()

    return json.dumps({
        "status": "staged",
        "staged_workout": payload,
        "instruction": "Antrenmanı özetle ve onay iste; onay gelince confirm_and_commit_workout_log çağır.",
    }, ensure_ascii=False)


def _tool_confirm_and_commit_workout_log(user_id):
    """TOOL (commit): En son staged antrenmanı kalıcı WorkoutLog'a taşı."""
    pending = (PendingAction.query
               .filter_by(user_id=user_id, action_type="log_workout")
               .order_by(PendingAction.created_at.desc())
               .first())
    if not pending:
        return json.dumps({
            "status": "no_pending",
            "message": "Onaylanacak bekleyen bir antrenman kaydı yok.",
        }, ensure_ascii=False)

    d = pending.payload or {}
    # Satırı önce atomik 'sahiplen' (double-confirm idempotency — 3.10).
    claimed = PendingAction.query.filter_by(id=pending.id).delete(synchronize_session=False)
    if not claimed:
        db.session.rollback()
        return json.dumps({
            "status": "no_pending",
            "message": "Bu kayıt zaten işlendi.",
        }, ensure_ascii=False)

    db.session.add(WorkoutLog(
        user_id=user_id,
        exercise_name=(d.get("exercise_name") or "Egzersiz")[:120],
        sets=int(d.get("sets", 3)), reps=int(d.get("reps", 10)),
        weight_kg=float(d.get("weight_kg", 0)), volume=float(d.get("volume", 0)),
    ))
    award_xp(user_id, 15)
    log_activity(user_id, "workout_completed",
                 f"{d.get('exercise_name')} — {d.get('sets')}x{d.get('reps')} @ {d.get('weight_kg')}kg")
    db.session.commit()

    return json.dumps({
        "status": "committed",
        "logged": d,
        "xp_awarded": 15,
        "today_totals": _today_workout_totals(user_id),
    }, ensure_ascii=False)


def _tool_cancel_pending_log(user_id):
    """TOOL: Kullanıcı reddederse SON stage edilen kaydı sil (meal VEYA workout).

    Tüm bekleyenleri silmek yerine en yenisini hedefler — tek bir 'iptal' hem
    staged meal'i hem staged workout'u birden silmesin (#11). Kullanıcı genelde
    en son sunulan kaydı reddeder; o da en yeni olandır."""
    pending = (PendingAction.query
               .filter_by(user_id=user_id)
               .order_by(PendingAction.created_at.desc(), PendingAction.id.desc())
               .first())
    if not pending:
        return json.dumps({"status": "cancelled", "removed": 0}, ensure_ascii=False)
    cancelled_type = pending.action_type
    removed = PendingAction.query.filter_by(id=pending.id).delete()
    db.session.commit()
    return json.dumps({"status": "cancelled", "removed": removed,
                       "cancelled_type": cancelled_type}, ensure_ascii=False)


# ── manage_user_memory ───────────────────────────────────────────────────────
# LLM'in yazabileceği anahtarlar beyaz-listede (rastgele anahtar şişmesini önle).
_MEMORY_KEYS = ("injuries", "fitness_goals", "equipment_available",
                "dietary_restrictions", "preferences")
_MEMORY_VALUE_MAXLEN = 2000  # serileştirilmiş değer üst sınırı (LLM girdisi)


def _tool_manage_user_memory(user_id, action, key=None, value=None):
    """TOOL: Kullanıcının uzun süreli metadata'sını (sakatlıklar, tercihler) oku/yaz.
    User.user_metadata (JSON) ile eşlenir. user_id ASLA LLM'den gelmez."""
    action = (action or "").strip().lower()
    key = (key or "").strip()
    user = db.session.get(User, user_id)
    if not user:
        return json.dumps({"status": "error", "message": "Kullanıcı bulunamadı."}, ensure_ascii=False)
    meta = dict(user.user_metadata or {})

    if action == "get":
        if key:
            return json.dumps({"status": "ok", "action": "get", "key": key,
                               "value": meta.get(key)}, ensure_ascii=False)
        return json.dumps({"status": "ok", "action": "get", "memory": meta}, ensure_ascii=False)

    if action == "update":
        if key not in _MEMORY_KEYS:
            return json.dumps({"status": "error",
                               "message": f"Geçersiz anahtar: '{key}'. Geçerli anahtarlar: {', '.join(_MEMORY_KEYS)}"},
                              ensure_ascii=False)
        # 'update' DAİMA bir değer ister. None/boş ile çağrı kayıtlı veriyi (ör.
        # sakatlık) sessizce silmesin — sakatlık akışında "yok" için 'Hiçbiri' yazılır.
        if value is None or (isinstance(value, str) and not value.strip()):
            return json.dumps({"status": "error",
                               "message": "'update' için boş olmayan bir value gerekli (silmek için açık bir değer gönder, ör. 'Hiçbiri')."},
                              ensure_ascii=False)
        try:
            if len(json.dumps(value, ensure_ascii=False)) > _MEMORY_VALUE_MAXLEN:
                return json.dumps({"status": "error", "message": "Değer çok uzun."}, ensure_ascii=False)
        except (TypeError, ValueError):
            return json.dumps({"status": "error", "message": "Değer JSON'a çevrilemedi."}, ensure_ascii=False)
        # JSON kolon: yerinde mutasyon SQLAlchemy tarafından izlenmez — yeni dict ata
        # + flag_modified ile değişikliği garanti et (aksi halde commit kalıcı olmaz).
        meta[key] = value
        user.user_metadata = meta
        flag_modified(user, "user_metadata")
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            current_app.logger.warning("[MEMORY] commit başarısız: %s: %s", type(e).__name__, e)
            return json.dumps({"status": "error", "message": "Kaydedilemedi, tekrar dene."}, ensure_ascii=False)
        return json.dumps({"status": "ok", "action": "update", "key": key,
                           "value": value}, ensure_ascii=False)

    return json.dumps({"status": "error",
                       "message": f"Geçersiz action: '{action}'. 'get' veya 'update' olmalı."},
                      ensure_ascii=False)


# ── query_fitx_metrics ────────────────────────────────────────────────────────
_VALID_DATE_RANGES = ("today", "last_7_days", "current_month")
_VALID_METRICS = ("calories", "water_ml", "sleep_hours", "weight_kg", "volume_lifted")


def _range_start_day(date_range):
    """date_range → aralığın BAŞLANGIÇ Istanbul günü (date). Bitiş daima bugün."""
    today = app_today()
    return {
        "today": today,
        "last_7_days": today - timedelta(days=6),
        "current_month": today.replace(day=1),
    }.get(date_range)


def _range_keys(date_range):
    """ISO-string tarih kolonları (MealLog.tarih, WaterLog.date_key) için (lo, hi)
    ISO anahtar çifti. 'YYYY-MM-DD' sözlüksel olarak sıralandığı için string
    karşılaştırması doğru aralığı verir: col >= lo AND col <= hi."""
    start = _range_start_day(date_range)
    return (start.isoformat(), app_today().isoformat()) if start else None


def _range_bounds(date_range):
    """datetime kolonları (created_at, naive UTC) için yarı-açık [start, end) UTC
    sınırları: col >= start AND col < end. utc_day_bounds Istanbul gününü baz alır."""
    start_day = _range_start_day(date_range)
    if not start_day:
        return None
    start, _ = utc_day_bounds(start_day)
    _, end = utc_day_bounds(app_today())
    return start, end


def _tool_query_fitx_metrics(user_id, metric_type, date_range):
    """TOOL: Kullanıcının geçmiş metriklerini parametrik (HAM SQL YOK) sorgula.
    Enum'lar beyaz-listede; her metrik sabit, güvenli bir sorguya eşlenir."""
    metric_type = (metric_type or "").strip()
    date_range = (date_range or "").strip()
    if metric_type not in _VALID_METRICS:
        return json.dumps({"status": "error",
                           "message": f"Geçersiz metric_type: '{metric_type}'. Geçerli: {', '.join(_VALID_METRICS)}"},
                          ensure_ascii=False)
    if date_range not in _VALID_DATE_RANGES:
        return json.dumps({"status": "error",
                           "message": f"Geçersiz date_range: '{date_range}'. Geçerli: {', '.join(_VALID_DATE_RANGES)}"},
                          ensure_ascii=False)

    if metric_type == "sleep_hours":
        # Uyku SÜRESİ (saat) verisi YOK; yalnızca subjektif kalite (1-5) var ve o da
        # [HAFTALIK CHECK-IN TRENDİ] bağlam bloğunda zaten sağlanıyor. Veri uydurma.
        return json.dumps({"status": "unsupported", "metric_type": "sleep_hours",
                           "message": "Uyku süresi (saat) takibi yok. Subjektif uyku "
                                      "kalitesi (1-5) için [HAFTALIK CHECK-IN TRENDİ] "
                                      "bağlam bloğuna bak."}, ensure_ascii=False)

    base = {"status": "ok", "metric_type": metric_type, "date_range": date_range}

    if metric_type == "calories":
        lo, hi = _range_keys(date_range)
        total = db.session.query(db.func.coalesce(db.func.sum(MealLog.kalori), 0)).filter(
            MealLog.user_id == user_id, MealLog.tarih >= lo, MealLog.tarih <= hi).scalar()
        return json.dumps({**base, "value": round(total or 0), "unit": "kcal"}, ensure_ascii=False)

    if metric_type == "water_ml":
        lo, hi = _range_keys(date_range)
        cups = db.session.query(db.func.coalesce(db.func.sum(WaterLog.count), 0)).filter(
            WaterLog.user_id == user_id, WaterLog.date_key >= lo, WaterLog.date_key <= hi).scalar()
        return json.dumps({**base, "value": round((cups or 0) * 240), "unit": "ml",
                           "detail": f"{cups or 0} bardak × 240 ml"}, ensure_ascii=False)

    if metric_type == "volume_lifted":
        start, end = _range_bounds(date_range)
        total = db.session.query(db.func.coalesce(db.func.sum(WorkoutLog.volume), 0)).filter(
            WorkoutLog.user_id == user_id,
            WorkoutLog.created_at >= start, WorkoutLog.created_at < end).scalar()
        return json.dumps({**base, "value": round(total or 0, 1), "unit": "kg"}, ensure_ascii=False)

    if metric_type == "weight_kg":
        start, end = _range_bounds(date_range)
        rows = (WeeklyLog.query.filter(
            WeeklyLog.user_id == user_id,
            WeeklyLog.created_at >= start, WeeklyLog.created_at < end)
            .order_by(WeeklyLog.created_at.asc()).all())
        if not rows:
            return json.dumps({**base, "value": None, "unit": "kg",
                               "message": "Bu aralıkta kilo kaydı yok."}, ensure_ascii=False)
        first, last = rows[0].weight, rows[-1].weight
        # L1: WeeklyLog.weight NULL olabilir; round(None, 1) TypeError atardı
        # (blanket except'e düşüp generic hataya dönerdi). None'ı açıkça karşıla.
        if last is None:
            return json.dumps({**base, "value": None, "unit": "kg",
                               "message": "Bu aralıkta geçerli kilo kaydı yok."}, ensure_ascii=False)
        change = round(last - first, 1) if first is not None else None
        return json.dumps({**base, "value": round(last, 1), "unit": "kg",
                           "change": change, "entries": len(rows)}, ensure_ascii=False)

    return json.dumps({"status": "error", "message": f"Bilinmeyen metric_type: {metric_type}"},
                      ensure_ascii=False)


# ── analyze_gym_photo (multimodal Pump Check) ─────────────────────────────────
def _parse_photo_validation(raw):
    """Modelin ham yanıtından {"is_gym":bool,"form_rating":1-10,"reason":str} ayıkla."""
    s = (raw or "").strip().replace("```json", "").replace("```", "")
    start = s.find("{")
    end = s.rfind("}") + 1
    if start != -1 and end > start:
        s = s[start:end]
    try:
        data = json.loads(s)
    except (json.JSONDecodeError, TypeError, ValueError):
        data = {}
    try:
        rating = int(data.get("form_rating") or 0)
    except (TypeError, ValueError):
        rating = 0
    rating = max(1, min(rating, 10)) if rating else 0  # 1..10'a kıs (0 = bilinmiyor)
    return {"is_gym": bool(data.get("is_gym", False)), "form_rating": rating,
            "reason": str(data.get("reason", ""))[:300]}


def _tool_analyze_gym_photo(user_id, s3_key):
    """TOOL: S3'teki bir antrenman fotoğrafını Bedrock (Sonnet) ile doğrula; geçerliyse
    günlük (idempotent) Pump Check ödülünü ver. user_id ASLA LLM'den gelmez; s3_key
    LLM'den gelir → sahiplik (IDOR) sınırı zorunlu."""
    s3_key = (s3_key or "").strip()
    if not s3_key:
        return json.dumps({"status": "error", "message": "s3_key boş."}, ensure_ascii=False)
    if not (BEDROCK_ENABLED and _anthropic is not None):
        return json.dumps({"status": "error", "message": "Görsel doğrulama (Bedrock) şu an etkin değil."},
                          ensure_ascii=False)
    if not s3_helper.is_enabled():
        return json.dumps({"status": "error", "message": "Görsel deposu (S3) yapılandırılmamış."},
                          ensure_ascii=False)

    # IDOR sınırı: anahtar bu kullanıcıya ait olmalı (yol içinde '/<user_id>/').
    try:
        image_bytes = s3_helper.get_object_bytes(s3_key, expected_user_id=user_id)
    except Exception as e:
        current_app.logger.info("[ANALYZE PHOTO] görsel alınamadı: %s: %s", type(e).__name__, e)
        return json.dumps({"status": "error", "message": "Görsel alınamadı veya sana ait değil."},
                          ensure_ascii=False)

    media_type = s3_helper.media_type_for_key(s3_key)
    try:
        if image_bytes and len(image_bytes) > 1_500_000:
            from app.services.menu_ocr import _compress_image_for_vision
            image_bytes, media_type = _compress_image_for_vision(image_bytes)
    except Exception:
        pass  # sıkıştırma başarısızsa ham baytlarla devam

    prompt = (
        "Sen bir fitness uygulamasının 'Pump Check' görsel doğrulayıcısısın. Görseli "
        "incele: bir spor salonu/antrenman ortamı mı? Kişinin fiziksel formunu/çabasını "
        "1-10 arası puanla. SADECE şu katı JSON'u döndür, başka hiçbir şey yazma: "
        '{"is_gym": true|false, "form_rating": 1-10, "reason": "kısa Türkçe gerekçe"}'
    )
    try:
        raw = _bedrock_validate_image(image_bytes, media_type, prompt, max_tokens=200)
    except Exception as e:
        current_app.logger.warning("[ANALYZE PHOTO] Bedrock başarısız: %s: %s", type(e).__name__, e)
        return json.dumps({"status": "error", "message": "Görsel analizi şu an yapılamadı."},
                          ensure_ascii=False)
    if not (raw or "").strip():
        # Boş model yanıtı (transport/model aksaklığı): _parse_photo_validation bunu
        # is_gym:false'a çevirip "burası spor salonu değil" gibi YANLIŞ bir cevaba
        # dönüştürürdü. Gerçek "değil" kararından ayır, hata olarak dön.
        current_app.logger.warning("[ANALYZE PHOTO] Bedrock boş yanıt döndürdü")
        return json.dumps({"status": "error", "message": "Görsel analizi şu an yapılamadı."},
                          ensure_ascii=False)
    result = _parse_photo_validation(raw)

    if not result["is_gym"]:
        return json.dumps({"status": "ok", "is_gym": False, "form_rating": result["form_rating"],
                           "reason": result["reason"], "awarded": False}, ensure_ascii=False)

    # İdempotent ödül: bugün zaten bir Pump Check varsa tekrar ödül YOK (XP farming'i önle).
    # /workout/complete ile aynı günlük-tamamlama defterini paylaşır.
    start_utc, end_utc = utc_day_bounds()
    if PumpCheck.query.filter(
        PumpCheck.user_id == user_id,
        PumpCheck.created_at >= start_utc,
        PumpCheck.created_at < end_utc,
    ).first():
        return json.dumps({"status": "already_done", "is_gym": True,
                           "form_rating": result["form_rating"], "reason": result["reason"],
                           "awarded": False, "message": "Bugünkü antrenmanını zaten tamamladın."},
                          ensure_ascii=False)

    db.session.add(PumpCheck(
        user_id=user_id, image_key=s3_key, location_type="ai_tool",
        description=result["reason"][:200], valid=True, fallback=False,
        date_key=app_today().isoformat()))
    db.session.add(WorkoutLog(
        user_id=user_id, exercise_name=WORKOUT_COMPLETION_MARKER,
        sets=1, reps=1, weight_kg=0, volume=0))
    xp = 35  # /workout/complete ile aynı: 10 base + 25 foto bonusu
    quest = _claim_quest(user_id, "workout_logged")
    award_xp(user_id, xp)
    log_activity(user_id, "workout_completed", "Pump Check doğrulandı (AI koç)")
    try:
        db.session.commit()
    except IntegrityError:
        # TOCTOU yarışı: başka bir istek (UI veya AI tool) bugünün PumpCheck'ini
        # araya yazdı; uq_pump_check_day ikinciyi reddetti → çift XP yok.
        db.session.rollback()
        return json.dumps({"status": "already_done", "is_gym": True,
                           "form_rating": result["form_rating"], "reason": result["reason"],
                           "awarded": False, "message": "Bugünkü antrenmanını zaten tamamladın."},
                          ensure_ascii=False)
    except Exception as e:
        db.session.rollback()
        current_app.logger.warning("[ANALYZE PHOTO] commit başarısız: %s: %s", type(e).__name__, e)
        return json.dumps({"status": "error", "message": "Ödül kaydedilemedi, tekrar dene."},
                          ensure_ascii=False)

    return json.dumps({"status": "committed", "is_gym": True,
                       "form_rating": result["form_rating"], "reason": result["reason"],
                       "awarded": True, "xp_awarded": xp + (quest["xp"] if quest else 0)},
                      ensure_ascii=False)


# ── Araç kayıt defteri (TEK kaynak) ───────────────────────────────────────────
# Kanonik tanım; OpenAI ve Anthropic biçimleri buradan türetilir (şema kayması yok).
# JSON Schema (parameters) iki sağlayıcıda da AYNIDIR. Sıra SABİT tutulur (caching).
_COACH_TOOL_DEFS = [
    {
        "name": "fetch_nutrition_and_stage_log",
        "description": (
            "Kullanıcı bir yiyecek/içecek YEDİĞİNİ söylediğinde VEYA bir yiyeceğin "
            "kalori/makro değerlerini sorduğunda çağır. FatSecret'tan gerçek makroları "
            "çeker ve onaya hazır şekilde geçici olarak hazırlar (stage). KALICI KAYIT "
            "YAPMAZ; sadece veriyi getirir."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "food_query": {
                    "type": "string",
                    "description": "Yiyecek ve varsa miktar. Ör: '300g ızgara tavuk göğsü', 'grande caffe latte', '2 haşlanmış yumurta'.",
                }
            },
            "required": ["food_query"],
        },
    },
    {
        "name": "confirm_and_commit_meal_log",
        "description": (
            "Kullanıcı stage edilmiş yemeği günlüğüne kaydetmeyi ONAYLADIĞINDA çağır "
            "('evet', 'kaydet', 'olur', 'tabii' vb.). Bekleyen yemek kaydını kalıcı "
            "günlüğe yazar. Onay açıkça gelmediyse ÇAĞIRMA."
        ),
        "parameters": {"type": "object", "properties": {}},
    },
    {
        "name": "stage_workout_log",
        "description": (
            "Kullanıcı bir antrenman/egzersiz YAPTIĞINI söylediğinde çağır "
            "(ör. '5x5 100kg squat yaptım'). Veriyi onaya hazırlar; kalıcı kayıt yapmaz."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "exercise_name": {"type": "string", "description": "Egzersiz adı, ör. 'Squat', 'Bench Press'."},
                "sets": {"type": "integer", "description": "Set sayısı. Belirtilmemişse 3."},
                "reps": {"type": "integer", "description": "Tekrar sayısı. Belirtilmemişse 10."},
                "weight_kg": {"type": "number", "description": "Ağırlık (kg). Vücut ağırlığı egzersizinde 0."},
            },
            "required": ["exercise_name"],
        },
    },
    {
        "name": "confirm_and_commit_workout_log",
        "description": "Kullanıcı stage edilmiş antrenmanı kaydetmeyi onayladığında çağır.",
        "parameters": {"type": "object", "properties": {}},
    },
    {
        "name": "cancel_pending_log",
        "description": "Kullanıcı stage edilmiş kaydı reddederse/iptal ederse çağır ('hayır', 'iptal', 'vazgeç', 'yanlış').",
        "parameters": {"type": "object", "properties": {}},
    },
    {
        "name": "manage_user_memory",
        "description": (
            "Kullanıcının uzun süreli metadata'sını (sakatlıklar/tıbbi durumlar, hedefler, "
            "ekipman, tercihler) oku veya yaz. Antrenman planı/önerisi vermeden ÖNCE "
            "action='get', key='injuries' ile sakatlık verisini kontrol et; yoksa kullanıcıya "
            "sor ve action='update' ile kaydet."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "action": {"type": "string", "enum": ["get", "update"],
                           "description": "'get' okur, 'update' yazar."},
                "key": {"type": "string",
                        "description": "Veri anahtarı. Ör: 'injuries', 'fitness_goals', 'equipment_available', 'dietary_restrictions', 'preferences'."},
                "value": {"type": "string",
                          "description": "action='update' için saklanacak değer (ör. 'Menisküs' veya 'Hiçbiri'). 'get' için gerekmez."},
            },
            "required": ["action", "key"],
        },
    },
    {
        "name": "query_fitx_metrics",
        "description": (
            "Kullanıcının geçmiş metriklerini güvenli ve parametrik olarak getir. Sayıları "
            "ASLA tahmin etme — analitik sorularda bu aracı çağır."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "metric_type": {"type": "string",
                                "enum": ["calories", "water_ml", "sleep_hours", "weight_kg", "volume_lifted"],
                                "description": "Metrik türü. Not: 'sleep_hours' henüz desteklenmiyor."},
                "date_range": {"type": "string",
                               "enum": ["today", "last_7_days", "current_month"],
                               "description": "Zaman aralığı."},
            },
            "required": ["metric_type", "date_range"],
        },
    },
    {
        "name": "analyze_gym_photo",
        "description": (
            "Kullanıcı bir spor salonu/antrenman fotoğrafının S3 anahtarını paylaştığında "
            "çağır. Görseli doğrular (spor salonu mu, form puanı 1-10) ve geçerliyse günlük "
            "Pump Check ödülünü verir."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "s3_key": {"type": "string", "description": "Yüklenen görselin S3 nesne anahtarı."},
            },
            "required": ["s3_key"],
        },
    },
]


def _to_openai_tool(t):
    """Kanonik tanım → OpenAI function-calling biçimi."""
    return {"type": "function", "function": {
        "name": t["name"], "description": t["description"], "parameters": t["parameters"]}}


def _to_anthropic_tool(t):
    """Kanonik tanım → Anthropic Messages API biçimi (input_schema = parameters)."""
    return {"name": t["name"], "description": t["description"], "input_schema": t["parameters"]}


# OpenAI döngüsü bu listeyi olduğu gibi kullanır (davranış değişmez).
COACH_TOOLS = [_to_openai_tool(t) for t in _COACH_TOOL_DEFS]
# Bedrock/Anthropic döngüsü için aynı kaynaktan türetilen biçim.
COACH_TOOLS_ANTHROPIC = [_to_anthropic_tool(t) for t in _COACH_TOOL_DEFS]


def _dispatch_coach_tool(user_id, name, arguments_json):
    """LLM'in istediği aracı sunucu tarafında çalıştır. user_id ASLA LLM'den
    gelmez — güvenlik için current_user'dan enjekte edilir. JSON string döndürür."""
    _assert_principal(user_id)
    try:
        args = json.loads(arguments_json) if arguments_json else {}
    except (json.JSONDecodeError, TypeError):
        args = {}

    # Araç gövdesindeki beklenmeyen hatayı (özellikle DB commit/delete) merkezi
    # olarak yakala: oturumu rollback ile temizle (kirli transaction sonraki
    # commit'i de patlatmasın) ve koç turunu çökertmek yerine modele hata durumu
    # döndür. _assert_principal KASTEN bunun DIŞINDA — güvenlik ihlali dostça bir
    # mesaja dönüşmemeli, propagate etmeli.
    try:
        if name == "fetch_nutrition_and_stage_log":
            return _tool_fetch_nutrition_and_stage_log(user_id, args.get("food_query", ""))
        if name == "confirm_and_commit_meal_log":
            return _tool_confirm_and_commit_meal_log(user_id)
        if name == "stage_workout_log":
            return _tool_stage_workout_log(
                user_id, args.get("exercise_name", ""),
                args.get("sets"), args.get("reps"), args.get("weight_kg"),
            )
        if name == "confirm_and_commit_workout_log":
            return _tool_confirm_and_commit_workout_log(user_id)
        if name == "cancel_pending_log":
            return _tool_cancel_pending_log(user_id)
        if name == "manage_user_memory":
            return _tool_manage_user_memory(
                user_id, args.get("action", ""), args.get("key"), args.get("value"))
        if name == "query_fitx_metrics":
            return _tool_query_fitx_metrics(
                user_id, args.get("metric_type", ""), args.get("date_range", ""))
        if name == "analyze_gym_photo":
            return _tool_analyze_gym_photo(user_id, args.get("s3_key", ""))
        return json.dumps({"status": "error", "message": f"Bilinmeyen araç: {name}"}, ensure_ascii=False)
    except Exception:
        db.session.rollback()
        current_app.logger.warning("[COACH] araç '%s' çalışırken hata", name, exc_info=True)
        return json.dumps({"status": "error",
                           "message": "Araç çalışırken bir hata oluştu, tekrar dener misin?"},
                          ensure_ascii=False)


COACH_HISTORY_LIMIT = 6          # son 3 alışveriş (user+assistant) yeterli bağlam


COACH_HISTORY_CHAR_CAP = 400     # her turu kırp ki istem şişmesin


def _sanitize_client_history(raw):
    """Widget'ın gönderdiği konuşma geçmişini güvenli OpenAI mesajlarına çevir.

    Widget formatı: [{"role": "user"|"bot", "text": "..."}]. 'bot' → 'assistant'
    eşlenir, metin kırpılır, yalnızca düz-metin user/assistant turları geçer
    (tool/sistem rolleri client'tan KABUL EDİLMEZ). Bozuk girdi sessizce atlanır."""
    if not isinstance(raw, list):
        return []
    out = []
    for item in raw[-COACH_HISTORY_LIMIT:]:
        if not isinstance(item, dict):
            continue
        role = item.get("role")
        role = "assistant" if role in ("bot", "assistant") else "user" if role == "user" else None
        if role is None:
            continue
        text = item.get("text") or item.get("content") or ""
        if not isinstance(text, str):
            continue
        text = text.strip()
        if text:
            content = text[:COACH_HISTORY_CHAR_CAP]
            # B15: Anthropic ardışık aynı-rol turlarında 400 verir; iki user (veya
            # iki assistant) turu arka arkaya gelirse birleştir ki Bedrock çağrısı
            # 400'lenip sessizce gpt-4o-mini yedeğine düşmesin.
            if out and out[-1]["role"] == role:
                merged = f"{out[-1]['content']}\n{content}"[:COACH_HISTORY_CHAR_CAP]
                out[-1]["content"] = merged
            else:
                out.append({"role": role, "content": content})
    return out


_COACH_TOOL_LOOP_CAP = 5  # araç çağrısı zincirine güvenli üst sınır (iki sağlayıcı)


class _BedrockFallback(Exception):
    """Bedrock döngüsü İLK çağrıda (henüz hiçbir araç çalışmadan) hata verdiğinde
    fırlatılır → OpenAI'ya güvenle düşülebilir. Bir araç YAN ETKİ ürettikten sonra
    oluşan hatalar bunu fırlatmaz (yarıda sağlayıcı değiştirip aracı tekrar
    çalıştırmaktan kaçınmak için)."""


def _run_coach_conversation(user_id, question, context, client_history=None, language="tr"):
    """Koç sohbeti yönlendiricisi: ortak mesajları kurar, Bedrock açıksa Bedrock
    araç-kullanım döngüsünü dener (ilk çağrı hatasında OpenAI'ya şeffafça düşer),
    aksi halde mevcut OpenAI döngüsünü çalıştırır; sonra geçmişi kalıcılaştırır.

    Konuşma geçmişi kullanıcının GÖRDÜĞÜ sohbettir: widget her istekte `history`
    gönderir, biz onu kaynak-doğru kabul ederiz. Asıl 'staged' veri DB'deki
    PendingAction'da yaşar. Client geçmiş göndermezse eski session-cookie'sine düşülür.
    """
    use_client = client_history is not None
    if use_client:
        history = _sanitize_client_history(client_history)
        # Widget mevcut soruyu da history'nin sonuna iter; soruyu aşağıda biz
        # ayrıca eklediğimiz için sondaki user turlarını atıp çift eklemeyi önle.
        while history and history[-1]["role"] == "user":
            history.pop()
    else:
        history = list(session.get("coach_history", []))
    history = history[-COACH_HISTORY_LIMIT:]

    final_text = None
    if BEDROCK_ENABLED and _anthropic is not None:
        try:
            final_text = _run_coach_conversation_bedrock(user_id, question, context, history, language)
        except _BedrockFallback as e:
            current_app.logger.warning(
                "[COACH] Bedrock ilk çağrı başarısız, OpenAI'ya düşülüyor: %s", e)
            final_text = None
    if final_text is None:
        final_text = _run_coach_conversation_openai(user_id, question, context, history, language)

    is_error_fallback = not final_text
    if not final_text:
        final_text = _COACH_FALLBACKS[_coach_lang(language)]["error"]

    # Geçmiş client'ta (widget sessionStorage) tutuluyor; client modunda session'a
    # YAZMA. Yalnızca client history göndermezse eski cookie geçmişini güncelle.
    # B16: sağlayıcı hata-yedeği metnini geçmişe YAZMA — aksi halde bir sonraki
    # turda bağlam olarak geri beslenip modeli kirletiyordu.
    if not use_client and not is_error_fallback:
        new_history = history + [
            {"role": "user", "content": question[:COACH_HISTORY_CHAR_CAP]},
            {"role": "assistant", "content": final_text[:COACH_HISTORY_CHAR_CAP]},
        ]
        session["coach_history"] = new_history[-COACH_HISTORY_LIMIT:]
    return final_text


def _run_coach_conversation_openai(user_id, question, context, history, language="tr"):
    """OpenAI function-calling döngüsü: system → (gerekirse araç çağrıları) → final metin.
    Geçmişi session'a YAZMAZ (çağıran yönlendirici halleder)."""
    messages = [{"role": "system", "content": build_coach_system(language)}]
    if context:
        messages.append({"role": "system", "content": f"[KULLANICI VERİSİ]\n{context}"})
    messages.extend(history)
    messages.append({"role": "user", "content": question})

    final_text = ""
    for _ in range(_COACH_TOOL_LOOP_CAP):
        try:
            resp = openai_client.chat.completions.create(
                model=OPENAI_MODEL,
                messages=messages,
                tools=COACH_TOOLS,
                tool_choice="auto",
                max_tokens=700,
                temperature=0.6,
            )
        except Exception as e:
            current_app.logger.warning("[COACH] OpenAI çağrısı başarısız: %s", type(e).__name__)
            return _COACH_FALLBACKS[_coach_lang(language)]["error"]
        if not resp.choices:
            # İçerik filtresi boş choices döndürebilir; ham IndexError yerine
            # boş final_text ile çık (çağıran yönlendirici dostça mesaja düşer).
            current_app.logger.warning("[COACH] OpenAI boş choices döndürdü")
            break
        msg = resp.choices[0].message
        tool_calls = msg.tool_calls or []

        if not tool_calls:
            final_text = msg.content or ""
            break

        # Araç isteyen assistant mesajını (tool_calls ile) sıraya ekle.
        messages.append({
            "role": "assistant",
            "content": msg.content or "",
            "tool_calls": [
                {"id": tc.id, "type": "function",
                 "function": {"name": tc.function.name, "arguments": tc.function.arguments}}
                for tc in tool_calls
            ],
        })
        # Her tool_call_id için tam olarak bir 'tool' yanıtı ekle (API zorunluluğu).
        for tc in tool_calls:
            result = _dispatch_coach_tool(user_id, tc.function.name, tc.function.arguments)
            messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})
        # Döngü başa döner: model araç sonuçlarıyla final metni üretir ya da zincirler.
    else:
        final_text = _COACH_FALLBACKS[_coach_lang(language)]["tool"]
    return final_text


def _build_bedrock_system(context, language="tr"):
    """Bedrock `system` parametresini kur. Caching açıkken dile özgü sistem
    promptunu ephemeral cache breakpoint ile işaretle; DEĞİŞKEN [KULLANICI VERİSİ]
    daima önbelleğe-alınan bloğun SONRASINA gelir (asla içine gömülmez — sessiz
    invalidasyon). Caching kapalıyken düz string yeterli."""
    system_prompt = build_coach_system(language)
    if BEDROCK_PROMPT_CACHE:
        blocks = [{"type": "text", "text": system_prompt,
                   "cache_control": {"type": "ephemeral"}}]
        if context:
            blocks.append({"type": "text", "text": f"[KULLANICI VERİSİ]\n{context}"})
        return blocks
    sys = system_prompt
    if context:
        sys += f"\n\n[KULLANICI VERİSİ]\n{context}"
    return sys


def _anthropic_tools_for_call():
    """COACH_TOOLS_ANTHROPIC'in çağrı-zamanı kopyası. Caching açıkken SON araca bir
    cache breakpoint ekler (sıra sabit → stabil önbellek). Temel liste kirletilmez."""
    if not (BEDROCK_PROMPT_CACHE and COACH_TOOLS_ANTHROPIC):
        return COACH_TOOLS_ANTHROPIC
    tools = [dict(t) for t in COACH_TOOLS_ANTHROPIC]
    tools[-1] = {**tools[-1], "cache_control": {"type": "ephemeral"}}
    return tools


def _first_text_block(resp):
    for block in getattr(resp, "content", None) or []:
        if getattr(block, "type", None) == "text":
            return block.text or ""
    return ""


def _run_coach_conversation_bedrock(user_id, question, context, history, language="tr"):
    """Bedrock (Anthropic Messages API) araç-kullanım döngüsü. stop_reason=='tool_use'
    olduğu sürece araçları çalıştırır, tool_result'ları geri besler ve modelin final
    metnine (stop_reason=='end_turn') ulaşana dek zincirler (güvenli üst sınır).

    İlk create() çağrısı hiçbir araç çalışmadan hata verirse _BedrockFallback fırlatır
    (yönlendirici OpenAI'ya düşer). Bir araç YAN ETKİ ürettikten sonraki hatada
    sağlayıcı DEĞİŞTİRİLMEZ — yumuşak hata metni döner."""
    system = _build_bedrock_system(context, language)
    tools = _anthropic_tools_for_call()
    convo = [dict(m) for m in history] + [{"role": "user", "content": question}]
    # Anthropic ilk mesajın 'user' rolünde olmasını şart koşar; baştaki assistant
    # turlarını (ör. widget'ın açılış bot mesajı) at — aksi halde ilk çağrı 400 verir.
    while convo and convo[0].get("role") != "user":
        convo.pop(0)
    max_tokens = min(700, BEDROCK_MAX_TOKENS)

    tools_ran = 0
    for _ in range(_COACH_TOOL_LOOP_CAP):
        # B4: create() YANINDA yanıt ayrıştırma da korunmalı — `resp.content` None
        # (→ TypeError) gibi create sonrası hatalar önceden _BedrockFallback DIŞINDA
        # kaçıp yönlendiricinin OpenAI yedeğini atlayarak koçu 500'lüyordu. Aynı
        # tools_ran mantığını uygula: hiç araç çalışmadıysa OpenAI'ya düş, çalıştıysa
        # sağlayıcı değiştirme (yan etkiyi tekrarlama) → yumuşak hata.
        try:
            resp = bedrock_client.messages.create(
                model=BEDROCK_MODEL,
                max_tokens=max_tokens,
                system=system,
                messages=convo,
                tools=tools,
            )

            if getattr(resp, "stop_reason", None) != "tool_use":
                text = _first_text_block(resp)
                if text:
                    return text
                # Metin bloğu yok: hiç araç çalışmadıysa OpenAI'ya düş (soru
                # cevaplanabilirdi); araç çalıştıysa sağlayıcı değiştirme.
                if tools_ran == 0:
                    raise _BedrockFallback("boş Bedrock yanıtı (metin bloğu yok)")
                return "İşlemi tamamlayamadım, tekrar dener misin?"

            # Araç isteyen assistant turunu (tool_use bloklarıyla) olduğu gibi ekle.
            convo.append({"role": "assistant", "content": resp.content})
            tool_results = []
            for block in resp.content:
                if getattr(block, "type", None) == "tool_use":
                    out = _dispatch_coach_tool(user_id, block.name, json.dumps(block.input or {}))
                    tool_results.append({"type": "tool_result", "tool_use_id": block.id, "content": out})
                    tools_ran += 1
            convo.append({"role": "user", "content": tool_results})
        except _BedrockFallback:
            raise
        except Exception as e:
            if tools_ran == 0:
                raise _BedrockFallback(f"{type(e).__name__}: {e}")
            current_app.logger.warning("[COACH][Bedrock] araç sonrası çağrı/ayrıştırma hatası: %s", e)
            return "İşlemi tamamlayamadım, tekrar dener misin?"
        # Döngü başa döner: model araç sonuçlarıyla final metni üretir ya da zincirler.

    return "İşlemi tamamlayamadım, tekrar dener misin?"


def generate_coach_reply(name, age, gender, weight, height,
                         goal, level, current_activity,
                         bmr, tdee, target_calories,
                         training_plan, nutrition_plan,
                         user_message,
                         previous_weight=None, days_passed=None, language="tr"):

    activity_labels = {
        "sedentary"  : "hareketsiz (masa başı iş)",
        "active"     : "aktif (haftada 3-5 gün)",
        "very_active": "çok aktif (haftada 5-6 gün)"
    }
    activity_text = activity_labels.get(current_activity, current_activity)

    # Önceki ilerleme metni
    diff = 0
    sure = "0 gün"
    progress_text = "İlk kayıt — geçmiş veri yok."
    if previous_weight and days_passed is not None:
        diff = round(weight - previous_weight, 1)
        sure = f"{days_passed} gün"
        if days_passed >= 7:
            sure = f"{days_passed // 7} hafta {days_passed % 7} gün"

    if (goal or "").lower() == "kas kazanma":  # B14: goal None → AttributeError guard
        # Kas kazanmada kilo artışı OLUMLU
        if diff > 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg almış. "
                f"KAS KAZANMA hedefinde bu bir BAŞARI. Tebrik et. "
                f"Kalori fazlası doğru çalışıyor, devam etmesini söyle."
            )
        elif diff < 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg vermiş. "
                f"KAS KAZANMA hedefinde bu istenmeyen bir durum. "
                f"Kalori alımını artırması gerektiğini vurgula. "
                f"Kalori açığı değil, kalori fazlası hedefleniyor."
            )
        else:
            progress_text = (
                f"Kullanıcı {sure} önce de {previous_weight} kg'dı, kilo değişmemiş. "
                f"KAS KAZANMA hedefinde kilo artışı bekleniyor. "
                f"Kalori alımını biraz artırmasını öner."
            )
    else:
        # Kilo verme hedefinde
        if diff < 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg vermiş. "
                f"KİLO VERME hedefinde bu bir BAŞARI. Tebrik et. "
                f"Verme hızını değerlendir: {sure}de {abs(diff)} kg."
            )
        elif diff > 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg almış. "
                f"KİLO VERME hedefinde bu istenmeyen bir durum. "
                f"Nazikçe değin, kalori takibine odaklanmasını söyle."
            )
        else:
            progress_text = (
                f"Kullanıcı {sure} önce de {previous_weight} kg'dı, kilo değişmemiş. "
                f"KİLO VERME hedefinde plato olabilir. "
                f"Kalori açığını gözden geçirmesini öner."
            )
    if _coach_lang(language) == "en":
        lang_line = ('You speak ENGLISH. Address the user directly as "you". Write your '
                     'ENTIRE answer in English and translate the Turkish section headers '
                     'below into natural English headers.')
    else:
        lang_line = ('Türkçe konuşuyorsun. Kullanıcıya "sen" diye hitap et, hiçbir zaman '
                     '"siz" kullanma. Yanıtında tek bir İngilizce kelime bile kullanma, '
                     'tamamen Türkçe yaz.')

    prompt = f"""Sen deneyimli, samimi ve motive edici bir kişisel fitness koçusun.
Şeker boyamıyorsun ama insanı kırmıyorsun da.
{lang_line}
Tavsiyelerin bu kişinin spesifik verilerine dayansın — genel geçer şeyler söyleme.
"ÇOK ÖNEMLİ: Kas kazanma hedefinde kilo artışı OLUMLUDUR, bunu asla negatif algılama. "
"Kilo verme hedefinde kilo azalışı OLUMLUDUR. "
"Hedefe göre değerlendirme yap, genel kalıplarla düşünme."

Kullanıcı bilgileri:
- İsim: {name}, Yaş: {age}, Cinsiyet: {gender}
- Güncel kilo: {weight}kg, Boy: {height}cm
- BMR: {round(bmr)} kcal, TDEE: {round(tdee)} kcal
- Hedef kalori: {round(target_calories)} kcal/gün
- Hedef: {goal}
- Fitness seviyesi: {level}
- Günlük aktivite: {activity_text}
- Kullanıcının sorusu/mesajı: {user_message if user_message else 'Yok'}

İlerleme durumu:
{progress_text}

Aşağıdaki formatta kişiye özel koçluk yorumu yaz:

GENEL DEĞERLENDİRME:
(2-3 cümle — mevcut durumu ve ilerlemeyi değerlendir, sayıları kullan)

EN KRİTİK ADIM:
(şu an odaklanması gereken tek şey, spesifik ve ölçülebilir olsun)

BU HAFTA YAP:
1. (spesifik görev — gün, süre, miktar belirt)
2. (spesifik görev — gün, süre, miktar belirt)
3. (spesifik görev — gün, süre, miktar belirt)

MOTİVASYON:
(bu kişinin durumuna özel, güçlü bir cümle)"""

    try:
        return _heavy_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt=("You are a fitness coach. Speak English — friendly, specific, "
                           "motivating; use numbers and durations."
                           if _coach_lang(language) == "en"
                           else "Sen bir fitness koçusun. Türkçe, samimi, spesifik ve motive edici konuş. Sayılar ve süreler kullan."),
            max_tokens=700,
            temperature=0.7,
        )
    except Exception:
        current_app.logger.exception("Koç yorumu üretilemedi")
        return ("Coach feedback is unavailable right now, please try again."
                if _coach_lang(language) == "en"
                else "Koç yorumu şu an alınamıyor, lütfen tekrar dene.")


def generate_checkin_feedback(name, weight, prev_weight, days_passed,
                               goal, yogunluk, fatigue, overload,
                               uyku, beslenme, note, language="tr"):

    yogunluk_labels = {1:"çok düşük",2:"düşük",3:"orta",4:"yüksek",5:"çok yüksek"}
    fatigue_labels  = {1:"hiç yorgun değil",2:"biraz yorgun",3:"normal",4:"yorgun",5:"çok yorgun"}
    overload_labels = {"evet":"ağırlık/tekrar artırdı","hayir":"artıramadı","kismen":"kısmen artırdı"}
    uyku_labels     = {1:"çok kötü",2:"kötü",3:"orta",4:"iyi",5:"çok iyi"}
    beslenme_labels = {1:"hiç uyamadı",2:"zayıf",3:"orta",4:"iyi",5:"tam uyum"}

    progress = "İlk check-in, geçmiş veri yok."
    if prev_weight and days_passed:
        diff = round(weight - prev_weight, 1)
        if (goal or "").lower() == "kas kazanma":  # B14: goal None guard
            if diff > 0:
                progress = f"{days_passed} günde {abs(diff)} kg aldı — kas kazanma hedefinde olumlu."
            elif diff < 0:
                progress = f"{days_passed} günde {abs(diff)} kg verdi — kas kazanma hedefinde bu istenmeyen."
            else:
                progress = f"{days_passed} günde kilo değişmedi — kalori artışı gerekebilir."
        else:
            if diff < 0:
                progress = f"{days_passed} günde {abs(diff)} kg verdi — kilo verme hedefinde başarılı."
            elif diff > 0:
                progress = f"{days_passed} günde {abs(diff)} kg aldı — kilo verme hedefinde istenmeyen."
            else:
                progress = f"{days_passed} günde kilo değişmedi — plato olabilir."

    checkin_lang = ('Write your ENTIRE feedback in English; address the user as "you". '
                    'The data below is in Turkish — translate it as needed.'
                    if _coach_lang(language) == "en"
                    else 'Türkçe yaz, İngilizce kullanma. Kullanıcıya "sen" diye hitap et.')

    prompt = f"""Sen bir kişisel fitness koçusun. {checkin_lang}

Haftalık check-in verileri:
- İsim: {name}
- Güncel kilo: {weight} kg
- Hedef: {goal}
- İlerleme: {progress}
- Antrenman yoğunluğu: {yogunluk_labels.get(yogunluk, 'orta')}
- Yorgunluk durumu: {fatigue_labels.get(fatigue, 'normal')}
- Progressive overload: {overload_labels.get(overload, 'kısmen')}
- Uyku kalitesi: {uyku_labels.get(uyku, 'orta')}
- Beslenme uyumu: {beslenme_labels.get(beslenme, 'orta')}
- Kullanıcının notu: {note if note else 'Yok'}

Bu verilere dayanarak kısa ve spesifik bir koçluk geri bildirimi yaz.
Maksimum 4-5 cümle. İyi giden şeyleri vurgula, eksik olanlar için somut öneri ver.
Fatigue yüksekse dinlenme öner, progressive overload yapamadıysa nasıl yapabileceğini anlat.
Uyku kötüyse bunun etkisini açıkla."""

    try:
        return _heavy_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt=("You are a fitness coach. Speak concise, specific, motivating English."
                           if _coach_lang(language) == "en"
                           else "Sen bir fitness koçusun. Kısa, spesifik, motive edici Türkçe konuş."),
            max_tokens=400,
            temperature=0.7,
        )
    except Exception:
        current_app.logger.exception("Check-in geri bildirimi üretilemedi")
        return ("Feedback is unavailable right now, please try again."
                if _coach_lang(language) == "en"
                else "Geri bildirim şu an alınamadı, lütfen tekrar dene.")
