# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import json
import re
import nutrition_pipeline
from datetime import datetime, timedelta
from flask import current_app, g, session

from app.config import OPENAI_MODEL
from app.extensions import db, openai_client
from app.models import MealLog, PendingAction, User, UserSession, WorkoutLog
from app.services.ai import _heavy_chat
from app.services.ai_nutrition import _food_search_llm, _is_relevant_food, _normalize_food_query_en
from app.services.fatsecret import _food_search_fatsecret, _food_search_static
from app.services.gamification import award_xp, log_activity
from app.timeutil import day_key, utc_day_bounds


COACH_SYSTEM_PROMPT = """Sen FitX uygulamasının elit, destekleyici ama gerçekçi AI Beslenme & Fitness Koçusun. Kullanıcının veritabanına HEM okuma HEM yazma erişimin var ve bunu ARAÇLAR (function calling) üzerinden yaparsın.

VERİ KAYNAKLARIN:
- Beslenme verileri FatSecret API'den geliyor — makroları ASLA tahmin etme, daima aracı çağır.
- Günlük aktivite verileri Apple Health (HealthKit) ve Android Health Connect'ten senkronize ediliyor (adım sayısı, kalori yakımı).
- Bu verileri analiz ederek kişiye özel, veri odaklı önerilerde bulun.

═══ BESLENME LOGLAMA İŞ AKIŞI (ÇOK ÖNEMLİ) ═══
Kullanıcı bir yiyecek/içecek YEDİĞİNİ söylediğinde VEYA makrolarını/kalorisini sorduğunda:
1. DAİMA önce `fetch_nutrition_and_stage_log` aracını çağır — gerçek makroları FatSecret'tan çeker ve onaya hazır şekilde geçici olarak hazırlar. Bu araç KAYDETMEZ, sadece veriyi getirir.
2. Dönen makroları kullanıcıya KISA ve NET sun (kalori | P | K | Y + porsiyon), sonra AÇIKÇA onay iste: "Günlüğüne kaydedeyim mi?". Araç bir `evaluation.compatibility_score` (0-100) döndürürse onu da AYNEN aktar.
3. Kullanıcı onaylarsa ("evet", "kaydet", "olur" vb.) `confirm_and_commit_meal_log` aracını çağır. Onay GELMEDEN asla bu aracı çağırma — merak amaçlı sorular yanlışlıkla loglanmamalı.
4. Kullanıcı reddederse/iptal ederse ("hayır", "iptal", "vazgeç") `cancel_pending_log` aracını çağır.
Antrenman için aynı mantık: `stage_workout_log` → onay → `confirm_and_commit_workout_log`.

═══ ÇEŞİTLİLİK DİREKTİFİ (ZORUNLU) ═══
ASLA monoton, tekrarlayan "tavuk + pirinç" gibi sıkıcı seçeneklere yönlendirme. Bunun yerine aktif olarak:
- Mikro besin yoğunluğunu öne çıkar (renkli sebzeler, yapraklılar, vitamin/mineral kaynakları).
- Lif alımını teşvik et (bakliyat, tam tahıl, sebze-meyve).
- Sağlıklı yağları öner (zeytinyağı, avokado, kuruyemiş, yağlı balık — omega-3).
- Çeşit sun: aynı makroyu farklı, lezzetli ve yöresel/global alternatiflerle ver.
- Popüler zincir/kafe ürünlerini (Starbucks, yerel kafeler, fast-food) değerlendirirken dürüst ol; daha besleyici, dengeli alternatifler öner.

TEMEL GÖREV:
- Beslenme sorularında gerçek FatSecret makrolarını kullan, tahmin etme.
- Araçların döndürdüğü makrolar ve `compatibility_score` DETERMİNİSTİK olarak sunucuda hesaplanır; bu sayıları ASLA değiştirme, yeniden hesaplama veya yuvarlama — yalnızca AYNEN sun ve yorumla.
- Trendleri, eksik logları ve başarıları proaktif olarak belirt.
- Haftalık rapor günlerinde (Pazartesi/Pazar) otomatik rapor sun.

RESTORAN MENÜ ANALİZİ:
- Restoran menülerini analiz ederken metabolik hassasiyet ve kullanıcının aktif hedeflerini her şeyin üstünde tut.
- Objektif ol, restoran pazarlama abartılarını filtrele.
- Sporcuyu masadaki en akıllı taktiksel yemeğe yönlendir.
- Kalan günlük makro bütçesine göre somut önerilerde bulun.
- Porsiyon boyutları ve gizli kaloriler konusunda uyar.

YANIT FORMATI:
- Yanıtlarını modern UI'a uygun yaz: taranabilir kısa bloklar, madde listeleri, net başlıklar.
- Uzun paragraflar yerine aksiyon odaklı kısa maddeler kullan.

KURALLAR:
- Türkçe yaz, kullanıcıya "sen" diye hitap et.
- Kısa, net, samimi ve veri odaklı konuş.
- Genel geçer tavsiye VERME — her yanıt kullanıcının verisine dayansın.
- Emin olmadığın tıbbi konularda doktora yönlendir. Tıbbi teşhis veya reçete VERME.
- Kas kazanma hedefinde kilo artışı OLUMLU, kilo vermede azalış OLUMLU.
- Tonu: elit, destekleyici, veri odaklı."""


def _assert_principal(user_id):
    """Savunma derinliği: in-process koç/MCP araçları yalnızca kimliği doğrulanmış
    kullanıcı için çalışmalı. user_id ASLA LLM'den gelmez; yine de bir istek
    bağlamında çağrıldıysak current_user ile eşleştiğini doğrula (gelecekteki bir
    yanlış kullanım çapraz-kullanıcı okuma/yazmaya dönüşmesin)."""
    from flask import has_request_context
    from flask_login import current_user
    if has_request_context() and getattr(current_user, "is_authenticated", False) \
            and current_user.id != user_id:
        raise PermissionError("user_id, kimliği doğrulanmış kullanıcıyla eşleşmiyor")


def _fetch_coach_context(user_id, question=""):
    _assert_principal(user_id)
    # Not: Beslenme makroları artık koç araçları (fetch_nutrition_and_stage_log)
    # üzerinden tek yoldan gelir; burada FatSecret verisi enjekte ETMİYORUZ ki
    # model rakip bir veri kaynağı görüp staging adımını atlamasın.
    from fitx_mcp.server import (
        get_user_fitness_summary,
        get_user_workout_history,
        get_user_supplement_stack,
        get_friend_activities,
        get_user_nutrition_log,
    )
    parts = []
    try:
        parts.append(f"[FITNESS ÖZETİ]\n{get_user_fitness_summary(user_id)}")
    except Exception:
        parts.append("[FITNESS ÖZETİ] Veri alınamadı.")
    try:
        parts.append(f"[ANTRENMAN GEÇMİŞİ (7 gün)]\n{get_user_workout_history(user_id, 7)}")
    except Exception:
        pass
    try:
        parts.append(f"[SUPPLEMENT STACK]\n{get_user_supplement_stack(user_id)}")
    except Exception:
        pass
    try:
        parts.append(f"[BESLENME LOGU (3 gün)]\n{get_user_nutrition_log(user_id, 3)}")
    except Exception:
        pass
    try:
        parts.append(f"[ARKADAŞ AKTİVİTELERİ]\n{get_friend_activities(user_id)}")
    except Exception:
        pass

    from analytics_engine import get_nudges
    try:
        models = {
            "WorkoutLog": WorkoutLog,
            "MealLog": MealLog,
            "UserSession": UserSession,
        }
        nudges = get_nudges(User.query.get(user_id), db, models,
                            getattr(g, "prev_last_login", None))
        if nudges:
            parts.append("[PROAKTİF BİLDİRİMLER]\n" + "\n".join(nudges))
    except Exception:
        pass

    return "\n\n".join(parts)


_GRAMS_RE = re.compile(r"(\d+(?:[.,]\d+)?)\s*(?:g|gr|gram)\b", re.IGNORECASE)


def _extract_grams(text):
    """Sorgudan gram miktarını yakala (ör. '300g tavuk' → 300.0). Yoksa None."""
    m = _GRAMS_RE.search(text or "")
    if m:
        try:
            val = float(m.group(1).replace(",", "."))
            if 0 < val <= 5000:
                return val
        except ValueError:
            pass
    return None


def _coach_search_food(query):
    """Birleşik besin araması — alaka-kapısı + TR→EN normalizasyonlu.

    1) Ham sorguyla FatSecret dene (İngilizce sorgular ve marka adları doğrudan
       eşleşir). Sonuçları ALAKA filtresinden geçir: FatSecret eşleyemediği
       Türkçe sorgulara ilgisiz jenerik besin döndürdüğü için ('patates
       kızartması' → 'Soy Nuts') ad-token örtüşmesi olmayanları ele.
    2) Alakalı sonuç yoksa sorguyu İngilizce'ye çevirip tekrar dene — FatSecret
       verisi ağırlıklı İngilizce, Türkçe serbest metin nadiren eşleşir.
    3) Son çare: statik Türkçe tablo, sonra LLM tahmini.
    Hepsi 100g bazlı 'per_100g' makroları içerir."""
    raw = (query or "").strip()

    relevant = [r for r in (_food_search_fatsecret(raw) or [])
                if _is_relevant_food(raw, r.get("name", ""))]
    if relevant:
        return relevant

    english = _normalize_food_query_en(raw)
    if english and english.lower() != raw.lower():
        relevant = [r for r in (_food_search_fatsecret(english) or [])
                    if _is_relevant_food(english, r.get("name", ""))]
        if relevant:
            return relevant

    return _food_search_static(raw) or _food_search_llm(english or raw) or []


def _today_nutrition_totals(user_id):
    """Bugünün beslenme toplamları (MealLog — tek kanonik beslenme defteri).
    menu.py'deki 'consumed' ile AYNI tarih anahtarını (utcnow %d.%m) kullanır ki
    koçun 'kalan bütçe'si ile menü analizinin 'kalanı' birebir tutarlı olsun.
    (Faz C tarih semantiğini tüm okuyucularda birlikte ISO/Istanbul'a taşıyacak.)"""
    today_key = day_key()
    row = db.session.query(
        db.func.coalesce(db.func.sum(MealLog.kalori), 0),
        db.func.coalesce(db.func.sum(MealLog.protein), 0),
        db.func.coalesce(db.func.sum(MealLog.karb), 0),
        db.func.coalesce(db.func.sum(MealLog.yag), 0),
        db.func.count(MealLog.id),
    ).filter(
        MealLog.user_id == user_id,
        MealLog.tarih == today_key,
    ).first()
    return {
        "calories": round(row[0]),
        "protein": round(row[1], 1),
        "carbs": round(row[2], 1),
        "fat": round(row[3], 1),
        "entry_count": row[4],
    }


def _remaining_macros_for_user(user_id):
    """Kullanicinin bugun KALAN gunluk makro butcesi.

    UserSession hedef kalorisinden hedef-makro dagilimi (analyze_menu ile ayni
    formul) cikarilir, bugun MealLog'a islenen tuketim dusulur.
    Deterministik; LLM yok. Profil/hedef yoksa None doner.
    """
    sess = (UserSession.query.filter_by(user_id=user_id)
            .order_by(UserSession.created_at.desc()).first())
    if not sess or not sess.target_calories:
        return None
    target_cal = sess.target_calories
    goal = sess.goal or ""
    protein_target = target_cal * (0.30 if goal == "kas kazanma" else 0.25) / 4
    fat_target = target_cal * 0.25 / 9
    carb_target = target_cal * (0.45 if goal == "kas kazanma" else 0.50) / 4
    consumed = _today_nutrition_totals(user_id)
    return {
        "calories": max(target_cal - consumed["calories"], 0),
        "protein": max(protein_target - consumed["protein"], 0),
        "carbs": max(carb_target - consumed["carbs"], 0),
        "fat": max(fat_target - consumed["fat"], 0),
    }


def _today_workout_totals(user_id):
    """Bugünün antrenman toplam volümü (Istanbul günü; created_at UTC olduğu için
    UTC sınırlarıyla karşılaştırılır)."""
    start, end = utc_day_bounds()
    row = db.session.query(
        db.func.coalesce(db.func.sum(WorkoutLog.volume), 0),
        db.func.count(WorkoutLog.id),
    ).filter(
        WorkoutLog.user_id == user_id,
        WorkoutLog.created_at >= start,
        WorkoutLog.created_at < end,
    ).first()
    return {"total_volume": round(row[0], 1), "entry_count": row[1]}


def _tool_fetch_nutrition_and_stage_log(user_id, food_query):
    """TOOL (staging): FatSecret'tan makro çek → PendingAction'a yaz → LLM'e döndür.
    KALICI KAYIT YAPMAZ. Durum geçişi: (yok) → staged."""
    food_query = (food_query or "").strip()
    if not food_query:
        return json.dumps({"status": "error", "message": "Yiyecek sorgusu boş."}, ensure_ascii=False)

    results = _coach_search_food(food_query)
    if not results:
        # FatSecret/fallback boş → LLM kullanıcıdan netleştirme istesin (hata yönetimi).
        return json.dumps({
            "status": "not_found",
            "message": f"'{food_query}' için besin verisi bulunamadı. Kullanıcıdan daha açık bir tanım iste (pişirme şekli, marka, miktar).",
        }, ensure_ascii=False)

    top = results[0]
    per_100g = top.get("per_100g") or top.get("macros") or {}
    grams = _extract_grams(food_query) or 100.0
    scale = grams / 100.0
    payload = {
        "food_name": (top.get("name") or food_query)[:200],
        "calories": round(float(per_100g.get("calories", 0)) * scale, 1),
        "protein": round(float(per_100g.get("protein", 0)) * scale, 1),
        "carbs": round(float(per_100g.get("carbs", 0)) * scale, 1),
        "fat": round(float(per_100g.get("fat", 0)) * scale, 1),
        "serving_size": f"{grams:g} g",
    }

    # Deterministik uyum degerlendirmesi (compatibility_score 0-100). Tum matematik
    # nutrition_pipeline'da yapilir; LLM yalnizca bu sabit sayilari sunar.
    remaining = _remaining_macros_for_user(user_id)
    evaluation = None
    if remaining is not None:
        evaluation = nutrition_pipeline.build_evaluation(
            food_id=top.get("food_id", ""),
            name=payload["food_name"],
            standardized_serving=payload["serving_size"],
            macros={
                "calories": payload["calories"],
                "protein": payload["protein"],
                "carbs": payload["carbs"],
                "fat": payload["fat"],
            },
            remaining=remaining,
        )

    # Tek aktif 'staged' meal: önceki bekleyenleri temizle, yenisini yaz, commit et.
    _cleanup_stale_pending(user_id)
    PendingAction.query.filter_by(user_id=user_id, action_type="log_meal").delete()
    db.session.add(PendingAction(user_id=user_id, action_type="log_meal", payload=payload))
    db.session.commit()

    return json.dumps({
        "status": "staged",
        "staged_food": payload,
        "evaluation": evaluation,
        "instruction": ("Makroları ve (varsa) compatibility_score'u kullanıcıya AYNEN, "
                        "değiştirmeden ve yeniden hesaplamadan sun — sayılar kesindir. "
                        "Sonra 'Günlüğüne kaydedeyim mi?' diye onay iste; onay gelmeden "
                        "confirm_and_commit_meal_log çağırma."),
    }, ensure_ascii=False)


def _tool_confirm_and_commit_meal_log(user_id):
    """TOOL (commit): En son staged meal'i kalıcı MealLog kaydına taşı (tek kanonik
    beslenme defteri — diyari/menü ile aynı tablo), PendingAction satırını sil.
    Durum geçişi: staged → committed."""
    pending = (PendingAction.query
               .filter_by(user_id=user_id, action_type="log_meal")
               .order_by(PendingAction.created_at.desc())
               .first())
    if not pending:
        # 'evet' dendi ama ortada bekleyen yemek yok → güvenli hata yönetimi.
        return json.dumps({
            "status": "no_pending",
            "message": "Onaylanacak bekleyen bir yemek kaydı yok. Önce kullanıcının ne yediğini öğrenip fetch_nutrition_and_stage_log çağır.",
        }, ensure_ascii=False)

    data = pending.payload or {}
    cal = float(data.get("calories", 0) or 0)
    pro = float(data.get("protein", 0) or 0)
    carb = float(data.get("carbs", 0) or 0)
    fat = float(data.get("fat", 0) or 0)
    name = (data.get("food_name") or "Yemek")[:200]

    # Satırı önce atomik 'sahiplen': eşzamanlı çift-onayda (double-confirm) yalnızca
    # biri 1 satır siler; diğeri 0 alır ve çift loglamadan döner (3.10 idempotent).
    claimed = PendingAction.query.filter_by(id=pending.id).delete(synchronize_session=False)
    if not claimed:
        db.session.rollback()
        return json.dumps({
            "status": "no_pending",
            "message": "Bu kayıt zaten işlendi.",
        }, ensure_ascii=False)

    db.session.add(MealLog(
        user_id=user_id, ogun="AI Koç", yemekler=name,
        kalori=cal, protein=pro, karb=carb, yag=fat,
        tarih=day_key(), source="coach",
    ))
    award_xp(user_id, 10)
    log_activity(user_id, "nutrition_logged", f"{name} — {round(cal)} kcal")
    db.session.commit()

    return json.dumps({
        "status": "committed",
        "logged": {
            "food_name": name, "calories": cal, "protein": pro,
            "carbs": carb, "fat": fat, "serving_size": data.get("serving_size", ""),
        },
        "xp_awarded": 10,
        "today_totals": _today_nutrition_totals(user_id),
    }, ensure_ascii=False)


_PENDING_TTL = timedelta(hours=1)


def _cleanup_stale_pending(user_id, max_age=_PENDING_TTL):
    """Onaylanmadan bayatlamış (>1 saat) bekleyen aksiyonları toplu sil (3.10).

    Onay hiç gelmeyen 'staged' kayıtlar birikip sonraki bir 'evet'te yanlış/eski
    bir yemeği loglayabilir; periyodik toplu temizlik bu riski kapatır. Commit
    çağırana bırakılmaz — kendi içinde idempotenttir, hata boğulur."""
    try:
        cutoff = datetime.utcnow() - max_age
        deleted = (PendingAction.query
                   .filter(PendingAction.user_id == user_id,
                           PendingAction.created_at < cutoff)
                   .delete(synchronize_session=False))
        if deleted:
            current_app.logger.info(
                "[PENDING] %d bayat bekleyen aksiyon temizlendi (user=%s)", deleted, user_id)
    except Exception:
        db.session.rollback()


def _tool_stage_workout_log(user_id, exercise_name, sets, reps, weight_kg):
    """TOOL (staging): Antrenmanı onaya hazırla. Kalıcı kayıt yapmaz."""
    exercise_name = (exercise_name or "").strip()
    if not exercise_name:
        return json.dumps({"status": "error", "message": "Egzersiz adı boş."}, ensure_ascii=False)
    try:
        sets = int(sets or 0)
        reps = int(reps or 0)
        weight = float(weight_kg or 0)
    except (TypeError, ValueError):
        sets, reps, weight = 3, 10, 0.0
    if sets <= 0:
        sets = 3
    if reps <= 0:
        reps = 10
    if weight < 0:
        weight = 0.0

    payload = {
        "exercise_name": exercise_name[:120],
        "sets": sets, "reps": reps, "weight_kg": weight,
        "volume": round(sets * reps * weight, 1),
    }
    _cleanup_stale_pending(user_id)
    PendingAction.query.filter_by(user_id=user_id, action_type="log_workout").delete()
    db.session.add(PendingAction(user_id=user_id, action_type="log_workout", payload=payload))
    db.session.commit()

    return json.dumps({
        "status": "staged",
        "staged_workout": payload,
        "instruction": "Antrenmanı özetle ve onay iste; onay gelince confirm_and_commit_workout_log çağır.",
    }, ensure_ascii=False)


def _tool_confirm_and_commit_workout_log(user_id):
    """TOOL (commit): En son staged antrenmanı kalıcı WorkoutLog'a taşı."""
    pending = (PendingAction.query
               .filter_by(user_id=user_id, action_type="log_workout")
               .order_by(PendingAction.created_at.desc())
               .first())
    if not pending:
        return json.dumps({
            "status": "no_pending",
            "message": "Onaylanacak bekleyen bir antrenman kaydı yok.",
        }, ensure_ascii=False)

    d = pending.payload or {}
    # Satırı önce atomik 'sahiplen' (double-confirm idempotency — 3.10).
    claimed = PendingAction.query.filter_by(id=pending.id).delete(synchronize_session=False)
    if not claimed:
        db.session.rollback()
        return json.dumps({
            "status": "no_pending",
            "message": "Bu kayıt zaten işlendi.",
        }, ensure_ascii=False)

    db.session.add(WorkoutLog(
        user_id=user_id,
        exercise_name=(d.get("exercise_name") or "Egzersiz")[:120],
        sets=int(d.get("sets", 3)), reps=int(d.get("reps", 10)),
        weight_kg=float(d.get("weight_kg", 0)), volume=float(d.get("volume", 0)),
    ))
    award_xp(user_id, 15)
    log_activity(user_id, "workout_completed",
                 f"{d.get('exercise_name')} — {d.get('sets')}x{d.get('reps')} @ {d.get('weight_kg')}kg")
    db.session.commit()

    return json.dumps({
        "status": "committed",
        "logged": d,
        "xp_awarded": 15,
        "today_totals": _today_workout_totals(user_id),
    }, ensure_ascii=False)


def _tool_cancel_pending_log(user_id):
    """TOOL: Kullanıcı reddederse tüm bekleyen staged kayıtları sil."""
    removed = PendingAction.query.filter_by(user_id=user_id).delete()
    db.session.commit()
    return json.dumps({"status": "cancelled", "removed": removed}, ensure_ascii=False)


COACH_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "fetch_nutrition_and_stage_log",
            "description": (
                "Kullanıcı bir yiyecek/içecek YEDİĞİNİ söylediğinde VEYA bir yiyeceğin "
                "kalori/makro değerlerini sorduğunda çağır. FatSecret'tan gerçek makroları "
                "çeker ve onaya hazır şekilde geçici olarak hazırlar (stage). KALICI KAYIT "
                "YAPMAZ; sadece veriyi getirir."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "food_query": {
                        "type": "string",
                        "description": "Yiyecek ve varsa miktar. Ör: '300g ızgara tavuk göğsü', 'grande caffe latte', '2 haşlanmış yumurta'.",
                    }
                },
                "required": ["food_query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "confirm_and_commit_meal_log",
            "description": (
                "Kullanıcı stage edilmiş yemeği günlüğüne kaydetmeyi ONAYLADIĞINDA çağır "
                "('evet', 'kaydet', 'olur', 'tabii' vb.). Bekleyen yemek kaydını kalıcı "
                "günlüğe yazar. Onay açıkça gelmediyse ÇAĞIRMA."
            ),
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "stage_workout_log",
            "description": (
                "Kullanıcı bir antrenman/egzersiz YAPTIĞINI söylediğinde çağır "
                "(ör. '5x5 100kg squat yaptım'). Veriyi onaya hazırlar; kalıcı kayıt yapmaz."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "exercise_name": {"type": "string", "description": "Egzersiz adı, ör. 'Squat', 'Bench Press'."},
                    "sets": {"type": "integer", "description": "Set sayısı. Belirtilmemişse 3."},
                    "reps": {"type": "integer", "description": "Tekrar sayısı. Belirtilmemişse 10."},
                    "weight_kg": {"type": "number", "description": "Ağırlık (kg). Vücut ağırlığı egzersizinde 0."},
                },
                "required": ["exercise_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "confirm_and_commit_workout_log",
            "description": "Kullanıcı stage edilmiş antrenmanı kaydetmeyi onayladığında çağır.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "cancel_pending_log",
            "description": "Kullanıcı stage edilmiş kaydı reddederse/iptal ederse çağır ('hayır', 'iptal', 'vazgeç', 'yanlış').",
            "parameters": {"type": "object", "properties": {}},
        },
    },
]


def _dispatch_coach_tool(user_id, name, arguments_json):
    """LLM'in istediği aracı sunucu tarafında çalıştır. user_id ASLA LLM'den
    gelmez — güvenlik için current_user'dan enjekte edilir. JSON string döndürür."""
    _assert_principal(user_id)
    try:
        args = json.loads(arguments_json) if arguments_json else {}
    except (json.JSONDecodeError, TypeError):
        args = {}

    if name == "fetch_nutrition_and_stage_log":
        return _tool_fetch_nutrition_and_stage_log(user_id, args.get("food_query", ""))
    if name == "confirm_and_commit_meal_log":
        return _tool_confirm_and_commit_meal_log(user_id)
    if name == "stage_workout_log":
        return _tool_stage_workout_log(
            user_id, args.get("exercise_name", ""),
            args.get("sets"), args.get("reps"), args.get("weight_kg"),
        )
    if name == "confirm_and_commit_workout_log":
        return _tool_confirm_and_commit_workout_log(user_id)
    if name == "cancel_pending_log":
        return _tool_cancel_pending_log(user_id)
    return json.dumps({"status": "error", "message": f"Bilinmeyen araç: {name}"}, ensure_ascii=False)


COACH_HISTORY_LIMIT = 6          # son 3 alışveriş (user+assistant) yeterli bağlam


COACH_HISTORY_CHAR_CAP = 400     # her turu kırp ki istem şişmesin


def _sanitize_client_history(raw):
    """Widget'ın gönderdiği konuşma geçmişini güvenli OpenAI mesajlarına çevir.

    Widget formatı: [{"role": "user"|"bot", "text": "..."}]. 'bot' → 'assistant'
    eşlenir, metin kırpılır, yalnızca düz-metin user/assistant turları geçer
    (tool/sistem rolleri client'tan KABUL EDİLMEZ). Bozuk girdi sessizce atlanır."""
    if not isinstance(raw, list):
        return []
    out = []
    for item in raw[-COACH_HISTORY_LIMIT:]:
        if not isinstance(item, dict):
            continue
        role = item.get("role")
        role = "assistant" if role in ("bot", "assistant") else "user" if role == "user" else None
        if role is None:
            continue
        text = item.get("text") or item.get("content") or ""
        if not isinstance(text, str):
            continue
        text = text.strip()
        if text:
            out.append({"role": role, "content": text[:COACH_HISTORY_CHAR_CAP]})
    return out


def _run_coach_conversation(user_id, question, context, client_history=None):
    """OpenAI function-calling döngüsü: system → (gerekirse araç çağrıları) → final metin.

    Konuşma geçmişi kullanıcının GÖRDÜĞÜ sohbettir: widget her istekte `history`
    gönderir, biz onu kaynak-doğru kabul ederiz (UI ↔ model her zaman senkron;
    "sohbeti temizle" doğal çalışır). Asıl 'staged' veri DB'deki PendingAction'da
    yaşar — onay/iptal akışı geçmiş metnine değil, ona bağlıdır. Geriye dönük
    uyumluluk için client geçmiş göndermezse eski session-cookie'sine düşülür.
    """
    use_client = client_history is not None
    if use_client:
        history = _sanitize_client_history(client_history)
        # Widget mevcut soruyu da history'nin sonuna iter; soruyu aşağıda biz
        # ayrıca eklediğimiz için sondaki user turlarını atıp çift eklemeyi önle.
        while history and history[-1]["role"] == "user":
            history.pop()
    else:
        history = session.get("coach_history", [])

    messages = [{"role": "system", "content": COACH_SYSTEM_PROMPT}]
    if context:
        messages.append({"role": "system", "content": f"[KULLANICI VERİSİ]\n{context}"})
    messages.extend(history[-COACH_HISTORY_LIMIT:])
    messages.append({"role": "user", "content": question})

    final_text = ""
    for _ in range(5):  # araç çağrısı yinelemesine güvenli üst sınır
        resp = openai_client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=messages,
            tools=COACH_TOOLS,
            tool_choice="auto",
            max_tokens=700,
            temperature=0.6,
        )
        msg = resp.choices[0].message
        tool_calls = msg.tool_calls or []

        if not tool_calls:
            final_text = msg.content or ""
            break

        # Araç isteyen assistant mesajını (tool_calls ile) sıraya ekle.
        messages.append({
            "role": "assistant",
            "content": msg.content or "",
            "tool_calls": [
                {"id": tc.id, "type": "function",
                 "function": {"name": tc.function.name, "arguments": tc.function.arguments}}
                for tc in tool_calls
            ],
        })
        # Her tool_call_id için tam olarak bir 'tool' yanıtı ekle (API zorunluluğu).
        for tc in tool_calls:
            result = _dispatch_coach_tool(user_id, tc.function.name, tc.function.arguments)
            messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})
        # Döngü başa döner: model araç sonuçlarıyla final metni üretir ya da zincirler.
    else:
        final_text = "İşlemi tamamlayamadım, tekrar dener misin?"

    if not final_text:
        final_text = "Bir şeyler ters gitti, tekrar dener misin?"

    # Geçmiş artık client'ta (widget sessionStorage) tutuluyor; client modunda
    # session'a YAZMA (UI kaynak-doğru). Yalnızca client history göndermezse eski
    # cookie geçmişini güncelle — geriye dönük uyumluluk.
    if not use_client:
        history.append({"role": "user", "content": question[:COACH_HISTORY_CHAR_CAP]})
        history.append({"role": "assistant", "content": final_text[:COACH_HISTORY_CHAR_CAP]})
        session["coach_history"] = history[-COACH_HISTORY_LIMIT:]
    return final_text


def generate_coach_reply(name, age, gender, weight, height,
                         goal, level, current_activity,
                         bmr, tdee, target_calories,
                         training_plan, nutrition_plan,
                         user_message,
                         previous_weight=None, days_passed=None):

    activity_labels = {
        "sedentary"  : "hareketsiz (masa başı iş)",
        "active"     : "aktif (haftada 3-5 gün)",
        "very_active": "çok aktif (haftada 5-6 gün)"
    }
    activity_text = activity_labels.get(current_activity, current_activity)

    # Önceki ilerleme metni
    diff = 0
    sure = "0 gün"
    progress_text = "İlk kayıt — geçmiş veri yok."
    if previous_weight and days_passed is not None:
        diff = round(weight - previous_weight, 1)
        sure = f"{days_passed} gün"
        if days_passed >= 7:
            sure = f"{days_passed // 7} hafta {days_passed % 7} gün"

    if goal.lower() == "kas kazanma":
        # Kas kazanmada kilo artışı OLUMLU
        if diff > 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg almış. "
                f"KAS KAZANMA hedefinde bu bir BAŞARI. Tebrik et. "
                f"Kalori fazlası doğru çalışıyor, devam etmesini söyle."
            )
        elif diff < 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg vermiş. "
                f"KAS KAZANMA hedefinde bu istenmeyen bir durum. "
                f"Kalori alımını artırması gerektiğini vurgula. "
                f"Kalori açığı değil, kalori fazlası hedefleniyor."
            )
        else:
            progress_text = (
                f"Kullanıcı {sure} önce de {previous_weight} kg'dı, kilo değişmemiş. "
                f"KAS KAZANMA hedefinde kilo artışı bekleniyor. "
                f"Kalori alımını biraz artırmasını öner."
            )
    else:
        # Kilo verme hedefinde
        if diff < 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg vermiş. "
                f"KİLO VERME hedefinde bu bir BAŞARI. Tebrik et. "
                f"Verme hızını değerlendir: {sure}de {abs(diff)} kg."
            )
        elif diff > 0:
            progress_text = (
                f"Kullanıcı {sure} önce {previous_weight} kg'dı, "
                f"şimdi {weight} kg — {abs(diff)} kg almış. "
                f"KİLO VERME hedefinde bu istenmeyen bir durum. "
                f"Nazikçe değin, kalori takibine odaklanmasını söyle."
            )
        else:
            progress_text = (
                f"Kullanıcı {sure} önce de {previous_weight} kg'dı, kilo değişmemiş. "
                f"KİLO VERME hedefinde plato olabilir. "
                f"Kalori açığını gözden geçirmesini öner."
            )
    prompt = f"""Sen deneyimli, samimi ve motive edici bir kişisel fitness koçusun.
Şeker boyamıyorsun ama insanı kırmıyorsun da. Türkçe konuşuyorsun.
Kullanıcıya "sen" diye hitap et, hiçbir zaman "siz" kullanma.
Yanıtında tek bir İngilizce kelime bile kullanma, tamamen Türkçe yaz.
Tavsiyelerin bu kişinin spesifik verilerine dayansın — genel geçer şeyler söyleme.
"ÇOK ÖNEMLİ: Kas kazanma hedefinde kilo artışı OLUMLUDUR, bunu asla negatif algılama. "
"Kilo verme hedefinde kilo azalışı OLUMLUDUR. "
"Hedefe göre değerlendirme yap, genel kalıplarla düşünme."

Kullanıcı bilgileri:
- İsim: {name}, Yaş: {age}, Cinsiyet: {gender}
- Güncel kilo: {weight}kg, Boy: {height}cm
- BMR: {round(bmr)} kcal, TDEE: {round(tdee)} kcal
- Hedef kalori: {round(target_calories)} kcal/gün
- Hedef: {goal}
- Fitness seviyesi: {level}
- Günlük aktivite: {activity_text}
- Kullanıcının sorusu/mesajı: {user_message if user_message else 'Yok'}

İlerleme durumu:
{progress_text}

Aşağıdaki formatta kişiye özel koçluk yorumu yaz:

GENEL DEĞERLENDİRME:
(2-3 cümle — mevcut durumu ve ilerlemeyi değerlendir, sayıları kullan)

EN KRİTİK ADIM:
(şu an odaklanması gereken tek şey, spesifik ve ölçülebilir olsun)

BU HAFTA YAP:
1. (spesifik görev — gün, süre, miktar belirt)
2. (spesifik görev — gün, süre, miktar belirt)
3. (spesifik görev — gün, süre, miktar belirt)

MOTİVASYON:
(bu kişinin durumuna özel, güçlü bir cümle)"""

    try:
        return _heavy_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="Sen bir fitness koçusun. Türkçe, samimi, spesifik ve motive edici konuş. Sayılar ve süreler kullan.",
            max_tokens=700,
            temperature=0.7,
        )
    except Exception:
        current_app.logger.exception("Koç yorumu üretilemedi")
        return "Koç yorumu şu an alınamıyor, lütfen tekrar dene."


def generate_checkin_feedback(name, weight, prev_weight, days_passed,
                               goal, yogunluk, fatigue, overload,
                               uyku, beslenme, note):

    yogunluk_labels = {1:"çok düşük",2:"düşük",3:"orta",4:"yüksek",5:"çok yüksek"}
    fatigue_labels  = {1:"hiç yorgun değil",2:"biraz yorgun",3:"normal",4:"yorgun",5:"çok yorgun"}
    overload_labels = {"evet":"ağırlık/tekrar artırdı","hayir":"artıramadı","kismen":"kısmen artırdı"}
    uyku_labels     = {1:"çok kötü",2:"kötü",3:"orta",4:"iyi",5:"çok iyi"}
    beslenme_labels = {1:"hiç uyamadı",2:"zayıf",3:"orta",4:"iyi",5:"tam uyum"}

    progress = "İlk check-in, geçmiş veri yok."
    if prev_weight and days_passed:
        diff = round(weight - prev_weight, 1)
        if goal.lower() == "kas kazanma":
            if diff > 0:
                progress = f"{days_passed} günde {abs(diff)} kg aldı — kas kazanma hedefinde olumlu."
            elif diff < 0:
                progress = f"{days_passed} günde {abs(diff)} kg verdi — kas kazanma hedefinde bu istenmeyen."
            else:
                progress = f"{days_passed} günde kilo değişmedi — kalori artışı gerekebilir."
        else:
            if diff < 0:
                progress = f"{days_passed} günde {abs(diff)} kg verdi — kilo verme hedefinde başarılı."
            elif diff > 0:
                progress = f"{days_passed} günde {abs(diff)} kg aldı — kilo verme hedefinde istenmeyen."
            else:
                progress = f"{days_passed} günde kilo değişmedi — plato olabilir."

    prompt = f"""Sen bir kişisel fitness koçusun. Türkçe yaz, İngilizce kullanma.
Kullanıcıya "sen" diye hitap et.

Haftalık check-in verileri:
- İsim: {name}
- Güncel kilo: {weight} kg
- Hedef: {goal}
- İlerleme: {progress}
- Antrenman yoğunluğu: {yogunluk_labels.get(yogunluk, 'orta')}
- Yorgunluk durumu: {fatigue_labels.get(fatigue, 'normal')}
- Progressive overload: {overload_labels.get(overload, 'kısmen')}
- Uyku kalitesi: {uyku_labels.get(uyku, 'orta')}
- Beslenme uyumu: {beslenme_labels.get(beslenme, 'orta')}
- Kullanıcının notu: {note if note else 'Yok'}

Bu verilere dayanarak kısa ve spesifik bir koçluk geri bildirimi yaz.
Maksimum 4-5 cümle. İyi giden şeyleri vurgula, eksik olanlar için somut öneri ver.
Fatigue yüksekse dinlenme öner, progressive overload yapamadıysa nasıl yapabileceğini anlat.
Uyku kötüyse bunun etkisini açıkla."""

    try:
        return _heavy_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="Sen bir fitness koçusun. Kısa, spesifik, motive edici Türkçe konuş.",
            max_tokens=400,
            temperature=0.7,
        )
    except Exception:
        current_app.logger.exception("Check-in geri bildirimi üretilemedi")
        return "Geri bildirim şu an alınamadı, lütfen tekrar dene."
