# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import json
import re
from flask import current_app

from app.services.ai import PORTION_SANITY_RULE, _openai_chat
from app.services.foodcache import _cache_macros


# Türkçe karakterleri ASCII'ye katlar — alaka eşleştirmesi aksandan bağımsız olsun.
_TR_FOLD = str.maketrans({
    "ç": "c", "Ç": "c", "ğ": "g", "Ğ": "g", "ı": "i", "I": "i", "İ": "i",
    "ö": "o", "Ö": "o", "ş": "s", "Ş": "s", "ü": "u", "Ü": "u",
})

# Alaka kararını sürüklememesi gereken sözcükler. Üç grup:
#  1) Miktar/porsiyon/pişirme (İngilizce sonuç adında Türkçe karşılığı bulunmaz),
#  2) Genel sıfat/nitelik (renk, "low/diet" vb. — tek başına besin kimliği değil),
#  3) Mutfak/ulus sıfatları (besin ADI eşleşmeli; 'türk' → 'Big Turk Bites' gibi
#     çapraz-mutfak yanlış eşleşmeleri keser).
_FOOD_STOPWORDS = {
    # miktar / porsiyon / pişirme
    "orta", "boy", "buyuk", "kucuk", "adet", "dilim", "kase", "bardak", "tabak",
    "porsiyon", "gram", "tane", "bir", "iki", "uc", "dort", "bes", "yarim",
    "haslanmis", "izgara", "pismis", "kizarmis", "firinda", "tava", "sote",
    "small", "medium", "large", "slice", "cup", "bowl", "plate", "piece",
    "serving", "boiled", "grilled", "cooked", "fried", "baked", "roasted", "raw",
    "the", "and", "with", "of",
    # genel sıfat / nitelik
    "red", "green", "white", "black", "brown", "yellow", "fresh", "hot", "cold",
    "sweet", "plain", "mixed", "whole", "low", "light", "diet", "dietetic",
    "original", "classic", "style", "homemade", "fat", "free", "lean",
    # mutfak / ulus
    "turk", "turkish", "indian", "italian", "french", "american", "mexican",
    "chinese", "greek", "thai", "japanese", "spanish", "german", "english",
    "arabic", "persian", "asian",
}


def _food_tokens(text):
    """Aksandan arındırılmış, küçük harfli anlamlı tokenler (len>=3) — alaka için."""
    folded = (text or "").translate(_TR_FOLD).lower()
    raw = re.findall(r"[a-z0-9]+", folded)
    return {t for t in raw if len(t) >= 3 and t not in _FOOD_STOPWORDS}


def _is_relevant_food(query, name):
    """Sonuç adı sorguyla anlamlı bir KELİME paylaşıyorsa True. FatSecret,
    eşleyemediği (çoğunlukla Türkçe) sorgulara ALAKASIZ jenerik besinler
    döndürür ('patates kızartması' → 'Soy Nuts'); bu kapı onları eler.

    Substring değil token (kelime-sınırı) eşleştirir — yoksa 'hindi' ⊂ 'b*hindi*'
    (bamya), 'suyu' ⊂ 't*suyu*' gibi yanlış pozitifler oluşur. Çoğul/çekim
    toleransı için ≥4 harfli önek eşleşmesine izin verilir ('banana'↔'bananas')."""
    q_tokens = _food_tokens(query)
    if not q_tokens:
        return True  # Eşleşecek anlamlı token yok → aşırı filtreleme yapma.
    n_tokens = _food_tokens(name)
    if not n_tokens:
        return False
    for qt in q_tokens:
        for nt in n_tokens:
            if qt == nt:
                return True
            shorter, longer = (qt, nt) if len(qt) <= len(nt) else (nt, qt)
            if len(shorter) >= 4 and longer.startswith(shorter):
                return True
    return False


def _token_match_count(query, name):
    """Sonuç adının (`name`) sorgudaki (`query`) KAÇ FARKLI anlamlı token'ı
    karşıladığını say. `_is_relevant_food` ile aynı eşleştirme kuralı (tam eşitlik
    veya ≥4 harf önek toleransı), ama boolean yerine örtüşme SAYISI döner —
    adayları 'en spesifik' olana göre sıralamak için kullanılır."""
    q_tokens = _food_tokens(query)
    if not q_tokens:
        return 0
    n_tokens = _food_tokens(name)
    if not n_tokens:
        return 0
    matched = 0
    for qt in q_tokens:
        for nt in n_tokens:
            if qt == nt:
                matched += 1
                break
            shorter, longer = (qt, nt) if len(qt) <= len(nt) else (nt, qt)
            if len(shorter) >= 4 and longer.startswith(shorter):
                matched += 1
                break
    return matched


def _is_specific_match(query, name):
    """`_is_relevant_food`'tan DAHA KATI alaka kapısı — menü makro hattı içindir.

    Çok-kelimeli (kompozit) yemek adlarında ('Tavuk Burger', 'Sezar Salata') tek
    bir GENEL kategori kelimesini ('burger', 'salata') paylaşmak YETMEZ. FatSecret
    bilmediği Türkçe niteleyiciyi yok sayıp tüm AİLEYE aynı jenerik kaydı döndürür:
    'Tavuk/Mantar/Vejetaryen Burger' → hepsi aynı 'Burger' → ÖZDEŞ ve yanlış makro
    (tavuk/sebze burgerine 82 g et proteini, 0 g karb — kepeksiz köfte kaydı).

    Bu kapı, sorgu ≥2 anlamlı token içeriyorsa sonucun bunlardan EN AZ 2'siyle
    örtüşmesini ister; böylece yalnızca jenerik kategori kelimesini paylaşan kayıt
    reddedilir ve öğe FatSecret jeneriği yerine LLM tahminine düşer (LLM niteleyiciye
    göre ayırt eder, kepek karbını da verir). Tek-token basit öğeler ('Çay', 'Kola',
    'Bal') eskisi gibi 1 örtüşmeyle eşleşir — onlarda jenerik-çökme sorunu yoktur."""
    q_tokens = _food_tokens(query)
    if not q_tokens:
        return True  # Anlamlı token yok → aşırı filtreleme yapma (bkz _is_relevant_food).
    need = 2 if len(q_tokens) >= 2 else 1
    return _token_match_count(query, name) >= need


def _normalize_food_query_en(q):
    """Serbest metin (çoğunlukla Türkçe) besin sorgusunu kısa bir İngilizce
    arama terimine çevir. FatSecret veritabanı ağırlıklı İngilizce/ABD; ham
    Türkçe sorgular ya hiç ya da yanlış eşleşir. Başarısızlıkta "" döner ki
    çağıran orijinal sorguya düşebilsin."""
    q = (q or "").strip()
    if not q:
        return ""
    try:
        out = _openai_chat(
            messages=[{"role": "user", "content":
                "Convert this food/drink description into a concise English search "
                "term for a nutrition database. Keep brand names as-is and keep the "
                "amount/quantity if present. Reply with ONLY the English term — no "
                "punctuation, no explanation.\n\n" + q}],
            system_prompt="You translate food/drink names to English for a "
                          "nutrition database lookup. Reply with only the search term.",
            temperature=0.0,
            max_tokens=24,
        ).strip().strip('"').strip(".").strip()
        # Model bir cümle döndürürse (çeviri yerine açıklama) güvenli reddet.
        if not out or len(out) > 80 or "\n" in out:
            return ""
        return out
    except Exception:
        return ""


def _normalize_food_queries_en(names):
    """Bir besin adı LİSTESİNİ TEK LLM çağrısında kısa İngilizce arama terimlerine
    çevir. Menü taraması düzinelerce Türkçe öğe içerir; her birini ayrı ayrı
    çevirmek (öğe başına 1 çağrı) çok yavaş olur — bu toplu sürüm hepsini bir kerede
    çevirir.

    `name -> english` sözlüğü döner. Yalnızca güvenli, anlamlı çeviriler eklenir;
    çevrilemeyen/şüpheli (boş, çok uzun, ham ile aynı) girdiler atlanır ki çağıran
    ham ada düşebilsin. Herhangi bir hata → {} (çağıran ham sorgularla devam eder).
    Tasarımı tekil `_normalize_food_query_en` ile aynı; sadece toplu çalışır."""
    names = [n for n in (names or []) if n and n.strip()]
    if not names:
        return {}
    listing = "\n".join(f"- {n}" for n in names)
    prompt = (
        "Aşağıdaki yemek/içecek adlarının HER BİRİNİ, bir beslenme veritabanında "
        "aratmak için kısa bir İngilizce terime çevir. Marka adlarını olduğu gibi "
        "bırak. SADECE JSON nesnesi döndür: anahtar = verilen ad (AYNEN), değer = "
        "İngilizce terim. Başka hiçbir şey yazma.\n\n" + listing
    )
    try:
        raw = _openai_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="You translate food/drink names to concise English search "
                          "terms for a nutrition database. Reply with ONLY a JSON "
                          "object mapping each given name to its English term.",
            temperature=0.0,
            max_tokens=min(200 + len(names) * 20, 2000),
        ).strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start < 0 or end <= start:
            return {}
        parsed = json.loads(raw[start:end])
        if not isinstance(parsed, dict):
            return {}
        # LLM anahtarı küçük-büyük harf/boşluk farkıyla dönebilir → toleranslı eşle.
        llm_lower = {str(k).strip().lower(): v for k, v in parsed.items()}
        result = {}
        for name in names:
            en = parsed.get(name)
            if en is None:
                en = llm_lower.get(name.strip().lower())
            if isinstance(en, str):
                en = en.strip().strip('"').strip(".").strip()
                if en and len(en) <= 80 and "\n" not in en and en.lower() != name.lower():
                    result[name] = en
        return result
    except Exception:
        return {}


def _food_search_llm(q):
    """Fallback: use LLM to estimate nutrition for common foods.

    FatSecret erisilemezken besin verisinin TEK kaynagi budur. Bu yuzden ornek
    olarak SABIT sayilar verilmez (model bunlari her besine kopyalayip ayni
    makrolari klonlayabilir — todos.txt §4); bunun yerine X/Y/Z/W yer tutuculari
    kullanilir ve her besinin KENDI farkli, gercek degerlerini uretmesi istenir.
    """
    prompt = (
        f"Kullanıcı '{q}' araması yaptı. Bu aramayla eşleşen 5 yaygın besini listele.\n"
        "Her biri için 100 gram başına GERÇEK makro değerlerini ver. Her besinin "
        "kendi gerçek değerleri olmalı — hiçbir besine aynı değerleri verme.\n"
        "SADECE JSON döndür, başka metin yazma. Aşağıdaki X/Y/Z/W yer tutucularını "
        "her besin için gerçek sayılarla doldur (örnek sayıları KOPYALAMA):\n"
        '[{{"name":"Besin adı","calories":X,"protein":Y,"carbs":Z,"fat":W}}]'
    )
    try:
        text = _openai_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="SADECE JSON döndür. Her besin için 100g başına gerçek, "
                          "birbirinden farklı makro değerleri hesapla; örnek/şablon "
                          "sayılarını tekrar etme." + PORTION_SANITY_RULE,
            temperature=0.3,
            max_tokens=600,
        ).strip()
        if text.startswith("```"):
            text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        items = json.loads(text)
        results = []
        for item in items:
            per_100g = {
                "calories": float(item.get("calories", 0)),
                "protein": float(item.get("protein", 0)),
                "carbs": float(item.get("carbs", 0)),
                "fat": float(item.get("fat", 0)),
            }
            name = item.get("name", q)
            _cache_macros({name: per_100g})
            results.append({
                "name": name,
                "brand": "",
                "food_id": "",
                "serving": "Per 100g",
                "is_per_serving": False,
                "macros": per_100g,
                "per_100g": per_100g
            })
        return results
    except Exception:
        return []


# Tarayıcı (proxy_scan_menu) body_text'i bu sınırda kapıyor; çıkarıcı da tamamını
# LLM'e versin (ikisi hizalı olmalı). Önceki 10000 kısıtı uzun menülerde (örn. 32k
# karakterlik BigChefs menüsü) sonradan gelen kategorileri (Burgerler, Pizzalar,
# ana yemekler, tatlılar) LLM girişine hiç ulaştırmadan atıyordu — kategoriler
# "eksik" görünüyordu. gpt-4o-mini 128k bağlamla bu boyutu rahat işler.
_MENU_EXTRACT_MAX_CHARS = 40000

# Çıkarım kapasitesi tek kaynaktan: istemdeki "toplam en fazla N yemek" sınırı,
# menu.py'deki kırpma ve LLM çıkış bütçesi hep bu sabitten türetilir.
MAX_MENU_ITEMS = 80
_MENU_ITEMS_PER_CATEGORY = 8
# Çıkış bütçesi kapasiteyle birlikte hareket etmeli: Türkçe yemek adları
# İngilizceye göre daha çok token'a bölünür; öğe başına ~60 token + JSON
# yapısı/kategori adları payı. Sabit 2500 tavanı, 80 öğelik yanıtı dizi
# ortasında kesip TÜM çıkarımı boş döndürebiliyordu
# (docs/menu-extraction-truncation-risk.md).
_MENU_EXTRACT_MAX_TOKENS = 200 + MAX_MENU_ITEMS * 60


def _salvage_truncated_categories(raw):
    """Kesik (max_tokens'a takılmış) JSON çıktısından son tamamlanmış
    öğe/kategori sınırına kadar olan kısmı kurtarır; başaramazsa None döner.

    Beklenen şema {"categories": {"Kategori": ["yemek", ...]}} olduğundan,
    güvenli kesim noktaları yalnızca dizi içinde kapanan string'ler (öğe
    adları) ve kapanan köşeli/küme parantezleridir — dict içinde kapanan bir
    string anahtardır, ardından ":" beklediği için orada kesilemez.
    """
    start = raw.find("{")
    if start < 0:
        return None
    stack = []
    in_str = esc = False
    cut = -1
    cut_stack = []
    for i in range(start, len(raw)):
        ch = raw[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
                if stack and stack[-1] == "[":
                    cut, cut_stack = i, list(stack)
        elif ch == '"':
            in_str = True
        elif ch in "{[":
            stack.append(ch)
        elif ch in "}]":
            if not stack:
                return None
            stack.pop()
            cut, cut_stack = i, list(stack)
    if cut < 0:
        return None
    repaired = raw[start:cut + 1] + "".join(
        "}" if b == "{" else "]" for b in reversed(cut_stack))
    try:
        parsed = json.loads(repaired)
    except json.JSONDecodeError:
        return None
    cats = parsed.get("categories", parsed)
    if not isinstance(cats, dict):
        return None
    return {k: v for k, v in cats.items() if isinstance(v, list) and v} or None


def _extract_categorized_items(raw_text, fw_state=None, headings=None, menu_source=None):
    menu_input = raw_text[:_MENU_EXTRACT_MAX_CHARS]
    if fw_state:
        # framework_state + ham metni birlikte ver ama toplam giriş bütçesini koru.
        menu_input = fw_state[:6000] + "\n\n" + raw_text[:_MENU_EXTRACT_MAX_CHARS - 6000]

    heading_hint = ""
    if headings:
        heading_hint = f"\n\nTespit edilen kategori başlıkları: {', '.join(headings)}\nBu kategorilerin HEPSİ için yemek bul. Hiçbirini atlama."

    doc_hint = ""
    if menu_source == "google_drive":
        doc_hint = ("\n\nDİKKAT: Bu metin bir PDF/görsel/doküman kaynağından çıkarılmıştır. "
                    "Tablo formatları, OCR hataları veya düzensiz boşluklar olabilir. "
                    "Satır satır dikkatlice oku, her yemek öğesini ayır. "
                    "Fiyat sütunlarını ve tablo başlıklarını (adet, fiyat, TL, ₺) yoksay.")

    prompt = f"""Aşağıdaki restoran menü metninden yemekleri KATEGORİLERİYLE çıkar.
Pazarlama metinlerini, açıklamaları, fiyatları YOKSAY. Sadece yemek/içecek adlarını al.
ÖNEMLİ: Önce HER kategoriden en az 2 yemek seç (hiçbir kategoriyi atlama — özellikle Burgerler, Pizzalar, ana yemekler gibi sonradan gelen başlıkları), sonra kalan kotayı doldur.
Kategori başına en fazla {_MENU_ITEMS_PER_CATEGORY} yemek, toplam en fazla {MAX_MENU_ITEMS} yemek.
Kategorileri menüdeki başlıklardan al (örn: Kahvaltılar, Salatalar, Izgara & Etler, Makarnalar, Burgerler, İçecekler, Tatlılar).
Eğer kategori bulamazsan "Genel" kullan.{heading_hint}{doc_hint}

Menü metni:
{menu_input}

SADECE aşağıdaki JSON formatında yanıt ver, başka hiçbir şey yazma:
{{"categories": {{"Kategori Adı": ["yemek1", "yemek2"], "Başka Kategori": ["yemek3"]}}}}"""

    try:
        raw = _openai_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="SADECE JSON döndür. Açıklama yapma, markdown kullanma. Menüdeki TÜM kategorileri dahil et, hiçbirini atlama." + PORTION_SANITY_RULE,
            temperature=0.0,
            max_tokens=_MENU_EXTRACT_MAX_TOKENS,
        ).strip()
        current_app.logger.info(f"[EXTRACT] LLM raw response length: {len(raw)} chars")
        raw = raw.replace("```json", "").replace("```", "").strip()
        start = raw.find("{")
        if start < 0:
            current_app.logger.info(f"[EXTRACT] ERROR: No valid JSON braces found in LLM response: {raw[:200]}")
            return {}
        end = raw.rfind("}") + 1
        parsed = None
        if end > start:
            try:
                parsed = json.loads(raw[start:end])
            except json.JSONDecodeError:
                parsed = None
        if parsed is None:
            # Kesik çıktı (örn. max_tokens'a takıldı): tümünü çöpe atmak yerine
            # son tamamlanmış öğe/kategori sınırına kadar olanı kurtar.
            salvaged = _salvage_truncated_categories(raw)
            if salvaged:
                current_app.logger.warning(
                    f"[EXTRACT] Truncated JSON salvaged: {len(salvaged)} categories, "
                    f"{sum(len(v) for v in salvaged.values())} items recovered")
                return salvaged
            current_app.logger.warning(f"[EXTRACT] JSON parse failed and salvage found nothing — Raw snippet: {raw[start:start+300]}")
            return {}
        cats = parsed.get("categories", parsed)
        if isinstance(cats, dict):
            result = {k: v for k, v in cats.items() if isinstance(v, list)}
            current_app.logger.info(f"[EXTRACT] LLM returned {len(result)} categories: {list(result.keys())} — Total items: {sum(len(v) for v in result.values())}")
            return result
        current_app.logger.info(f"[EXTRACT] ERROR: Unexpected parsed structure type: {type(cats).__name__}")
    except json.JSONDecodeError as je:
        current_app.logger.info(f"[EXTRACT] JSON ERROR: {je}")
    except Exception as e:
        current_app.logger.info(f"[EXTRACT] ERROR: {type(e).__name__}: {e}")
    return {}


def _turkish_ablative_suffix(name):
    name = (name or "").strip()
    if not name:
        return "'dan"
    unvoiced = set("çÇfFhHkKpPsSşŞtT")
    back_vowels = set("aAıIoOuU")
    front_vowels = set("eEiİöÖüÜ")
    last_vowel_is_back = True
    for ch in reversed(name):
        if ch in back_vowels:
            last_vowel_is_back = True
            break
        elif ch in front_vowels:
            last_vowel_is_back = False
            break
    last_char = name[-1]
    if last_char in unvoiced:
        return "'tan" if last_vowel_is_back else "'ten"
    return "'dan" if last_vowel_is_back else "'den"


def _parse_suggestion_items(body_text):
    try:
        raw = _openai_chat(
            messages=[{"role": "user", "content": f"Aşağıdaki öğün önerisinden her bir yiyecek öğesini (miktar dahil) çıkar ve JSON listesi olarak döndür:\n\n\"{body_text}\"\n\nÖrnek çıktı: [\"200g tavuk göğsü\", \"1 kase pilav\", \"yeşil salata\"]"}],
            system_prompt="Kullanıcının yemek önerisinden yiyecek öğelerini çıkar. SADECE JSON array döndür, başka hiçbir şey yazma.",
            temperature=0.0,
            max_tokens=500,
        ).strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        start = raw.find("[")
        end = raw.rfind("]") + 1
        if start >= 0 and end > start:
            items = json.loads(raw[start:end])
            if isinstance(items, list) and items:
                return [str(i).strip() for i in items if str(i).strip()]
    except Exception as e:
        current_app.logger.warning(f"[SUGGESTION] Failed to parse suggestion items: {type(e).__name__}: {e}")
    return []


def _estimate_serving_weights_llm(items):
    if not items:
        return {}
    current_app.logger.info(f"[MACRO ENGINE] Estimating serving weights for {len(items)} per-100g items")
    items_str = "\n".join(f"- {name}" for name in items)
    prompt = f"""Sen bir restoran şefi ve beslenme uzmanısın. Aşağıdaki yemeklerin Türkiye'de standart bir restoranda servis edilen 1 PORSİYONUNUN ortalama ağırlığını GRAM cinsinden tahmin et.

Kurallar:
- Sadece tabakta servis edilen yemeğin ağırlığını ver (tabak hariç)
- Garnitür, pilav, salata gibi yan ürünler dahil
- Et yemekleri: sadece et 150-200g, garnitürle 300-400g
- Salatalar: 250-350g
- Çorbalar: 250-300ml (≈ gram)
- Makarnalar: 300-400g
- Hamburger: 250-350g
- Izgara balık: 200-300g (garnitürle 350-450g)

Yemekler:
{items_str}

SADECE aşağıdaki JSON formatında yanıt ver:
{{{", ".join(f'"{name}": GRAM_SAYISI' for name in items[:3])}{"..." if len(items) > 3 else ""}}}"""

    try:
        raw = _openai_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="SADECE JSON döndür. Her yemek için farklı, gerçekçi gram değerleri ver. Sayıları integer olarak yaz." + PORTION_SANITY_RULE,
            temperature=0.0,
            max_tokens=1000,
        ).strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start >= 0 and end > start:
            parsed = json.loads(raw[start:end])
            llm_lower = {k.strip().lower(): k for k in parsed.keys()}
            results = {}
            for name in items:
                grams = parsed.get(name)
                if grams is None:
                    llm_key = llm_lower.get(name.strip().lower())
                    if llm_key:
                        grams = parsed[llm_key]
                if isinstance(grams, (int, float)) and 50 <= grams <= 600:
                    results[name] = float(grams)
                else:
                    results[name] = 150.0
                    current_app.logger.info(f"[MACRO ENGINE] Serving weight fallback 150g for '{name}' (raw={grams})")
            current_app.logger.info(f"[MACRO ENGINE] Serving weights resolved: {results}")
            return results
    except Exception as e:
        current_app.logger.info(f"[MACRO ENGINE] LLM SERVING WEIGHT ERROR: {type(e).__name__}: {e}")
    return {n: 150.0 for n in items}


def _repair_truncated_json(raw_json):
    import re as _re
    depth = 0
    last_valid = 0
    in_string = False
    escape_next = False
    for i, ch in enumerate(raw_json):
        if escape_next:
            escape_next = False
            continue
        if ch == '\\' and in_string:
            escape_next = True
            continue
        if ch == '"' and not escape_next:
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                last_valid = i + 1
                break
    if depth == 0 and last_valid > 0:
        return raw_json[:last_valid]
    trimmed = raw_json.rstrip()
    trimmed = _re.sub(r',\s*$', '', trimmed)
    trimmed = _re.sub(r'"[^"]*$', '', trimmed)
    trimmed = _re.sub(r',\s*$', '', trimmed)
    trimmed += '}' * depth
    return trimmed


def _estimate_macros_llm_batch(batch_items):
    if not batch_items:
        return {}
    items_str = "\n".join(f"- {name}" for name in batch_items)
    prompt = f"""Sen bir beslenme uzmanısın. Aşağıdaki restoran yemeklerinin 1 PORSİYON (standart restoran servisi) için TAHMİNİ besin değerlerini hesapla.

ÖNEMLİ: Değerler 100 gram için DEĞİL, 1 tam porsiyon (tabaktaki yemeğin tamamı) için olmalı.
Referans porsiyon ağırlıkları: Et yemekleri garnitürle ~350g, salatalar ~300g, çorbalar ~280g, makarnalar ~350g.
Her yemek için gerçekçi değerler ver. Hiçbir yemeğe aynı değerleri verme, her biri farklı olmalı.

ÖNEMLİ: JSON anahtarları olarak yemek isimlerini AYNEN aşağıdaki listeden kopyala, hiçbir harfi değiştirme:
{items_str}

SADECE aşağıdaki JSON formatında yanıt ver:
{{{", ".join(f'"{name}": {{"calories": X, "protein": Y, "carbs": Z, "fat": W}}' for name in batch_items[:3])}{"..." if len(batch_items) > 3 else ""}}}

Tüm {len(batch_items)} yemek için değer ver. Sadece JSON döndür, başka bir şey yazma."""

    max_tok = min(300 + len(batch_items) * 65, 4000)
    try:
        raw = _openai_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="SADECE JSON döndür. Her yemek için 1 TAM PORSİYON (100g değil!) besin değerleri hesapla. Her yemeğe farklı, gerçekçi makro değerleri ver. JSON anahtarlarını kullanıcının verdiği isimlerle BİREBİR AYNI yaz." + PORTION_SANITY_RULE,
            temperature=0.0,
            max_tokens=max_tok,
        ).strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        start = raw.find("{")
        if start < 0:
            current_app.logger.info(f"[MACRO ENGINE] LLM response has no JSON braces: {raw[:200]}")
            return {}

        json_str = raw[start:]
        try:
            parsed = json.loads(json_str)
        except json.JSONDecodeError:
            repaired = _repair_truncated_json(json_str)
            try:
                parsed = json.loads(repaired)
                current_app.logger.info(f"[MACRO ENGINE] Repaired truncated JSON: {len(json_str)} → {len(repaired)} chars")
            except json.JSONDecodeError as je:
                current_app.logger.warning(f"[MACRO ENGINE] JSON repair failed: {je} — raw[{start}:{start+200}]: {raw[start:start+200]}")
                return {}

        current_app.logger.info(f"[MACRO ENGINE] LLM batch returned {len(parsed)} keys")

        import re as _re
        _num_pat = _re.compile(r"(\d+(?:[.,]\d+)?)")
        def _safe_float(v):
            if isinstance(v, (int, float)):
                return float(v)
            if isinstance(v, str):
                match = _num_pat.search(v.replace(",", "."))
                if match:
                    return float(match.group(1))
            return 0.0

        llm_key_map = {k.strip().lower(): k for k in parsed.keys()}
        results = {}
        for name in batch_items:
            m = None
            if name in parsed and isinstance(parsed[name], dict):
                m = parsed[name]
            else:
                llm_key = llm_key_map.get(name.strip().lower())
                if llm_key and isinstance(parsed.get(llm_key), dict):
                    m = parsed[llm_key]

            if m:
                macros = {
                    "calories": _safe_float(m.get("calories", 0)),
                    "protein": _safe_float(m.get("protein", 0)),
                    "carbs": _safe_float(m.get("carbs", 0)),
                    "fat": _safe_float(m.get("fat", 0)),
                }
                if macros["calories"] > 0:
                    results[name] = macros

        return results
    except Exception as e:
        import traceback
        current_app.logger.info(f"[MACRO ENGINE] LLM BATCH ERROR: {type(e).__name__}: {e}")
        traceback.print_exc()
    return {}


_LLM_MACRO_BATCH_SIZE = 15


def _estimate_macros_llm(items):
    if not items:
        return {}
    current_app.logger.info(f"[MACRO ENGINE] LLM fallback for {len(items)} items (batch size {_LLM_MACRO_BATCH_SIZE}): {items[:5]}{'...' if len(items)>5 else ''}")
    all_results = {}
    for i in range(0, len(items), _LLM_MACRO_BATCH_SIZE):
        batch = items[i:i + _LLM_MACRO_BATCH_SIZE]
        current_app.logger.info(f"[MACRO ENGINE] Processing batch {i // _LLM_MACRO_BATCH_SIZE + 1}/{(len(items) - 1) // _LLM_MACRO_BATCH_SIZE + 1} ({len(batch)} items)")
        batch_results = _estimate_macros_llm_batch(batch)
        all_results.update(batch_results)
    current_app.logger.info(f"[MACRO ENGINE] LLM total resolved: {len(all_results)}/{len(items)} items with non-zero macros")
    return all_results


def _score_item(macros, remaining):
    import math
    rem_cal = max(remaining["calories"], 1)
    rem_pro = max(remaining["protein"], 1)
    rem_fat = max(remaining["fat"], 1)
    rem_carb = max(remaining["carbs"], 1)

    ideal_cal = rem_cal * 0.40
    ideal_pro = rem_pro * 0.40
    ideal_fat = rem_fat * 0.35
    ideal_carb = rem_carb * 0.40

    w_cal, w_pro, w_fat, w_carb = 0.25, 0.35, 0.20, 0.20

    err_cal = ((macros["calories"] - ideal_cal) / rem_cal) ** 2
    err_pro = ((macros["protein"] - ideal_pro) / rem_pro) ** 2
    err_fat = ((macros["fat"] - ideal_fat) / rem_fat) ** 2
    err_carb = ((macros["carbs"] - ideal_carb) / rem_carb) ** 2

    wmse = w_cal * err_cal + w_pro * err_pro + w_fat * err_fat + w_carb * err_carb
    base_score = max(0.0, 100.0 * math.exp(-3.5 * wmse))

    penalty = 0.0
    cal_ratio = macros["calories"] / rem_cal
    fat_ratio = macros["fat"] / rem_fat
    carb_ratio = macros["carbs"] / rem_carb

    if cal_ratio > 0.70:
        penalty += (cal_ratio - 0.70) * 40
    if fat_ratio > 0.60:
        penalty += (fat_ratio - 0.60) * 30
    if carb_ratio > 0.75:
        penalty += (carb_ratio - 0.75) * 20

    pro_ratio = macros["protein"] / rem_pro
    bonus = 0.0
    if 0.25 <= pro_ratio <= 0.50:
        bonus += 10.0 * (1.0 - abs(pro_ratio - 0.375) / 0.125)

    score = max(0.0, min(100.0, base_score - penalty + bonus))

    warnings = []
    if cal_ratio > 0.80:
        warnings.append("Günlük kalori limitinin %80'ini aşıyor")
    if fat_ratio > 0.80:
        warnings.append("Günlük yağ limitinin %80'ini aşıyor")
    if carb_ratio > 0.85:
        warnings.append("Karbonhidrat limitine yakın")

    reason_parts = []
    if pro_ratio >= 0.25:
        reason_parts.append(f"Kalan {remaining['protein']:.0f}g protein hedefinle uyumlu")
    if cal_ratio <= 0.50:
        reason_parts.append("Kalori bütçesine uygun")
    if fat_ratio <= 0.40:
        reason_parts.append("Düşük yağ")
    if not reason_parts:
        reason_parts.append(f"{macros['calories']:.0f} kcal · {macros['protein']:.0f}g protein")

    return round(score, 4), warnings, " · ".join(reason_parts)
