# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).



_macro_cache = {}


_food_id_cache = {}   # name → fatsecret food_id


_MACRO_CACHE_MAX = 500


def _get_cached_macros(item_names):
    hits = {}
    misses = []
    for name in item_names:
        cached = _macro_cache.get(name)
        if cached is not None:
            hits[name] = cached
        else:
            misses.append(name)
    return hits, misses


def _cache_macros(macro_map):
    for name, macros in macro_map.items():
        if macros.get("calories", 0) > 0:
            if len(_macro_cache) >= _MACRO_CACHE_MAX:
                oldest = next(iter(_macro_cache))
                del _macro_cache[oldest]
            _macro_cache[name] = macros
