# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).



# Makro onbellegi BAZ (basis) bazinda ayri tutulur: koc aramasi 100g-bazli,
# menu/social hatti PORSIYON-bazli deger yazar. Eski tek-sozluk tasarimda ayni
# ad altinda iki baz karisiyordu ('Pizza' 100g=267 kcal ← koc; menu bunu 1 tam
# porsiyon sanip 4-5 kat eksik gosteriyordu — ya da tersi, sisirme).
_macro_cache = {
    "per_100g": {},
    "per_serving": {},
}


_food_id_cache = {}   # name → fatsecret food_id


_MACRO_CACHE_MAX = 500


_FOOD_ID_CACHE_MAX = 1000


def _get_cached_macros(item_names, basis="per_serving"):
    # setdefault: dis sozluk temizlense bile (test fixture'lari .clear() yapar)
    # namespace kendini onarir.
    cache = _macro_cache.setdefault(basis, {})
    hits = {}
    misses = []
    for name in item_names:
        cached = cache.get(name)
        if cached is not None:
            hits[name] = cached
        else:
            misses.append(name)
    return hits, misses


def _cache_macros(macro_map, basis="per_serving"):
    cache = _macro_cache.setdefault(basis, {})
    for name, macros in macro_map.items():
        if macros.get("calories", 0) > 0:
            if len(cache) >= _MACRO_CACHE_MAX:
                oldest = next(iter(cache))
                del cache[oldest]
            cache[name] = macros


def _cache_food_id(name, fid):
    """name → FatSecret food_id eşlemesini sınırlı (bounded) bir sözlükte tut.

    _macro_cache gibi FIFO tavanı uygula: kimliği doğrulanmış kullanıcılar
    serbest metin sorgularıyla bu önbelleği büyütebildiği için tavansız bırakmak
    yavaş bir bellek-büyümesi (DoS) vektörü olurdu."""
    if not name or not fid:
        return
    key = name.lower()
    if key not in _food_id_cache and len(_food_id_cache) >= _FOOD_ID_CACHE_MAX:
        oldest = next(iter(_food_id_cache))
        del _food_id_cache[oldest]
    _food_id_cache[key] = fid
