# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import threading


# Onbellekler ThreadPoolExecutor worker'larindan (es zamanli FatSecret/LLM
# aramalari) yazilir; tek bir kilit, eviction sirasindaki `next(iter(cache))`
# + `del` bilesik isleminin baska bir thread'in mutasyonuyla cakisip
# "dictionary changed size during iteration" RuntimeError'i atmasini onler.
_cache_lock = threading.Lock()


# Makro onbellegi BAZ (basis) bazinda ayri tutulur: koc aramasi 100g-bazli,
# menu/social hatti PORSIYON-bazli deger yazar. Eski tek-sozluk tasarimda ayni
# ad altinda iki baz karisiyordu ('Pizza' 100g=267 kcal ← koc; menu bunu 1 tam
# porsiyon sanip 4-5 kat eksik gosteriyordu — ya da tersi, sisirme).
_macro_cache = {
    "per_100g": {},
    "per_serving": {},
}


_food_id_cache = {}   # name → fatsecret food_id


_MACRO_CACHE_MAX = 500


_FOOD_ID_CACHE_MAX = 1000


def _get_cached_macros(item_names, basis="per_serving"):
    # setdefault: dis sozluk temizlense bile (test fixture'lari .clear() yapar)
    # namespace kendini onarir.
    # Okuma da _cache_lock altinda: es zamanli eviction (next(iter)+del) ile
    # cakismasin. Donen sozlukler KOPYA — tuketici mutasyonu onbellegi bozmasin (#12).
    hits = {}
    misses = []
    with _cache_lock:
        cache = _macro_cache.setdefault(basis, {})
        for name in item_names:
            cached = cache.get(name)
            if cached is not None:
                hits[name] = dict(cached)
            else:
                misses.append(name)
    return hits, misses


def _cache_macros(macro_map, basis="per_serving"):
    with _cache_lock:
        cache = _macro_cache.setdefault(basis, {})
        for name, macros in macro_map.items():
            if macros.get("calories", 0) > 0:
                if len(cache) >= _MACRO_CACHE_MAX:
                    oldest = next(iter(cache))
                    del cache[oldest]
                # KOPYA sakla — uretici map'i sonradan mutasyon ederse onbellek
                # etkilenmesin (referansla paylasim aliasing'i, #12).
                cache[name] = dict(macros)


def _get_cached_food_id(name, default=""):
    """name → food_id okumasını kilit altında yap. Düz `_food_id_cache.get(...)`
    okuması _cache_food_id'deki eviction `del`'iyle yarışıyordu; dict.get tek
    başına bozulmasa da dokümante kilit disiplinine uymak için tutarlı tut (3.6)."""
    if not name:
        return default
    with _cache_lock:
        return _food_id_cache.get(name.lower(), default)


def _cache_food_id(name, fid):
    """name → FatSecret food_id eşlemesini sınırlı (bounded) bir sözlükte tut.

    _macro_cache gibi FIFO tavanı uygula: kimliği doğrulanmış kullanıcılar
    serbest metin sorgularıyla bu önbelleği büyütebildiği için tavansız bırakmak
    yavaş bir bellek-büyümesi (DoS) vektörü olurdu."""
    if not name or not fid:
        return
    key = name.lower()
    with _cache_lock:
        if key not in _food_id_cache and len(_food_id_cache) >= _FOOD_ID_CACHE_MAX:
            oldest = next(iter(_food_id_cache))
            del _food_id_cache[oldest]
        _food_id_cache[key] = fid
