# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
from datetime import datetime, timedelta
from flask import jsonify
from flask_login import current_user
from sqlalchemy import event

from app.config import LB_ALLTIME_KEY, LB_WEEKLY_KEY
from app.extensions import db, redis_client
from app.models import Activity, DailyQuest, Friendship, User, UserQuestProgress, WeeklyResetLog, WeeklyWinner
from app.timeutil import app_today


def _lb_score(xp, streak):
    """XP'yi 1e5 ile çarpıp streak'i ekleyerek kompozit sıralama skoru üret."""
    return (xp or 0) * 100000 + min(streak or 0, 99999)


def lb_sync_user(user):
    """Tek kullanıcının skorunu iki sete yaz. Redis yoksa/çökerse sessizce geç."""
    if not redis_client or not user:
        return
    try:
        s = user.streak_count or 0
        uid = str(user.id)
        redis_client.zadd(LB_ALLTIME_KEY, {uid: _lb_score(user.rank_points, s)})
        redis_client.zadd(LB_WEEKLY_KEY,  {uid: _lb_score(user.weekly_xp, s)})
    except Exception:
        pass  # Postgres kaynak; boot/rollover'daki lb_rebuild sürüklenmeyi düzeltir


def lb_rebuild():
    """Her iki sorted set'i Postgres'ten sıfırdan kur (boot + haftalık rollover sonrası)."""
    if not redis_client:
        return
    try:
        pipe = redis_client.pipeline()
        pipe.delete(LB_ALLTIME_KEY, LB_WEEKLY_KEY)
        for u in User.query.all():
            s = u.streak_count or 0
            uid = str(u.id)
            pipe.zadd(LB_ALLTIME_KEY, {uid: _lb_score(u.rank_points, s)})
            pipe.zadd(LB_WEEKLY_KEY,  {uid: _lb_score(u.weekly_xp, s)})
        pipe.execute()
    except Exception:
        pass


def _mark_lb_dirty(user_id):
    """Kullanıcıyı 'commit sonrası Redis sync gerekli' olarak işaretle. Eski davranış
    (award_xp içinde anında lb_sync_user) commit ÖNCESI yazıyordu; rollback olunca
    liderlik tablosu yukarı sürükleniyordu (H1-Redis). Artık sync after_commit'te."""
    if user_id is None:
        return
    db.session.info.setdefault("lb_dirty", set()).add(user_id)


@event.listens_for(db.session, "after_commit")
def _flush_lb_dirty(session):
    """Commit BAŞARILI olduktan sonra işaretli kullanıcıları Redis'e yaz (H1-Redis).
    Redis yoksa lb_sync_user zaten sessizce geçer."""
    dirty = session.info.pop("lb_dirty", None)
    if not dirty:
        return
    for uid in dirty:
        u = db.session.get(User, uid)
        if u:
            lb_sync_user(u)


@event.listens_for(db.session, "after_rollback")
@event.listens_for(db.session, "after_soft_rollback")
def _drop_lb_dirty(session, *args):
    """Rollback'te işaretleri at — XP kalıcı olmadı, Redis'e yazma."""
    session.info.pop("lb_dirty", None)


def award_xp(user_id, amount):
    user = db.session.get(User, user_id)
    if user:
        user.rank_points = (user.rank_points or 0) + amount
        user.weekly_xp = (user.weekly_xp or 0) + amount
        _mark_lb_dirty(user_id)  # Redis sync commit BAŞARILI olduktan sonra (after_commit)
        return user.rank_points
    return None


def get_level(xp):
    return 1 + (xp or 0) // 500


def get_title(level):
    if level <= 5:
        return "Fitness Yolcusu"
    elif level <= 10:
        return "Demir Bükücü"
    elif level <= 20:
        return "Kas Mimarı"
    elif level <= 50:
        return "FitX Efsanesi"
    else:
        return "Antrenman Tanrısı"


ACTIVITY_ICONS = {
    "workout_completed": "⚡",
    "new_supplement": "\U0001f48a",
    "streak_milestone": "\U0001f525",
    "new_friend": "\U0001f91d",
    "level_up": "\U0001f31f",
    "quest_completed": "\U0001f3af",
}


def log_activity(user_id, activity_type, content):
    act = Activity(user_id=user_id, activity_type=activity_type, content=content)
    db.session.add(act)


def get_rank_title(points):
    return get_title(get_level(points))


WEEKLY_REWARDS = {1: 500, 2: 300, 3: 150}


def _last_completed_week_key(now=None):
    """ISO 'YYYY-Www' of the most recently completed week (boundary = Sunday 23:59 UTC)."""
    now = now or datetime.utcnow()
    monday = (now - timedelta(days=now.isoweekday() - 1)).replace(
        hour=0, minute=0, second=0, microsecond=0)
    sunday_2359 = monday + timedelta(days=6, hours=23, minutes=59)
    ref = now if now >= sunday_2359 else (monday - timedelta(days=1))  # this week if closed, else last
    y, w, _ = ref.isocalendar()
    return f"{y}-W{w:02d}"


def run_weekly_rollover(now=None, force_week=None):
    """Snapshot the weekly board, award top-3 XP, reset weekly counters. Idempotent."""
    week_key = force_week or _last_completed_week_key(now)

    # Idempotency guard — skip if this week was already processed.
    if WeeklyResetLog.query.filter_by(week_key=week_key).first():
        return {"status": "already_processed", "week_key": week_key}

    wx = db.func.coalesce(User.weekly_xp, 0)
    sc = db.func.coalesce(User.streak_count, 0)
    top = (User.query.filter(wx > 0)
                     .order_by(wx.desc(), sc.desc(), User.id.asc())
                     .limit(3).all())

    winners = []
    for i, u in enumerate(top):
        rank = i + 1
        xp = WEEKLY_REWARDS[rank]
        u.rank_points = (u.rank_points or 0) + xp  # reward feeds all-time only, not weekly
        db.session.add(WeeklyWinner(user_id=u.id, week_key=week_key,
                                    rank=rank, xp_awarded=xp, notified=False))
        winners.append({"user_id": u.id, "rank": rank, "xp": xp})

    # Reset everyone's weekly counter for the new cycle.
    db.session.query(User).update({User.weekly_xp: 0})
    db.session.add(WeeklyResetLog(week_key=week_key, winner_count=len(winners)))

    try:
        db.session.commit()
    except Exception:
        # Concurrent run won the race (week_key UNIQUE) — safe to ignore, but log
        # so the race is observable rather than silent (3.7).
        db.session.rollback()
        try:
            from flask import current_app
            current_app.logger.info(
                "[ROLLOVER] %s zaten işlendi (eşzamanlı yarış — UNIQUE çakışması)", week_key)
        except Exception:
            pass
        return {"status": "already_processed", "week_key": week_key}

    lb_rebuild()  # weekly_xp sıfırlandı + kazananlara XP eklendi → setleri yeniden kur
    return {"status": "done", "week_key": week_key, "winners": winners}


_last_rollover_check = [None]


def get_today_progress(user_id):
    today_key = app_today().isoformat()
    return UserQuestProgress.query.filter_by(
        user_id=user_id, date_key=today_key
    ).all()


def _claim_quest(user_id, quest_type):
    """Görev ilerlemesini + XP'yi + activity'yi session'a EKLER ama COMMIT ETMEZ.
    Çağıran kendi transaction'ında commit eder (atomiklik için — C1). Görev yoksa
    veya bugün zaten alındıysa None döner (session'a hiçbir şey eklemeden)."""
    quest = DailyQuest.query.filter_by(quest_type=quest_type, is_active=True).first()
    if not quest:
        return None
    today_key = app_today().isoformat()
    existing = UserQuestProgress.query.filter_by(
        user_id=user_id, quest_id=quest.id, date_key=today_key
    ).first()
    if existing:
        return None
    db.session.add(UserQuestProgress(
        user_id=user_id, quest_id=quest.id, date_key=today_key, is_claimed=True))
    new_total = award_xp(user_id, quest.points_reward)
    log_activity(user_id, "quest_completed", f"'{quest.title}' görevini tamamladı")
    level = get_level(new_total)
    return {"awarded": True, "xp": quest.points_reward, "new_total": new_total,
            "quest_title": quest.title, "level": level, "title": get_title(level)}


def complete_quest_for_user(user_id, quest_type):
    """Tek-görev kısayolu: _claim_quest + kendi commit'i (mevcut tüm çağıranlar için
    davranış AYNI kalır). Atomik akışlarda doğrudan _claim_quest kullan."""
    result = _claim_quest(user_id, quest_type)
    if result is None:
        return None
    try:
        db.session.commit()
    except Exception:
        db.session.rollback()
        return None
    return result


LEADERBOARD_TOP_N = 100  # size of the visible top list


def _accepted_friend_ids():
    rows = Friendship.query.filter(
        Friendship.status == "accepted",
        db.or_(Friendship.sender_id == current_user.id,
               Friendship.receiver_id == current_user.id)).all()
    return {r.receiver_id if r.sender_id == current_user.id else r.sender_id
            for r in rows}


def _lb_serialize(u, rank, timeframe="all_time"):
    # XP shown reflects the selected timeframe; level always derives from lifetime XP.
    xp = (u.weekly_xp if timeframe == "weekly" else u.rank_points) or 0
    return {
        "rank": rank,
        "id": u.id,
        "username": u.username,
        "full_name": u.full_name or u.username,
        "profile_picture": u.avatar_src,
        "level": get_level(u.rank_points or 0),
        "xp": xp,
        "streak": u.streak_count or 0,
        "is_me": u.id == current_user.id,
    }


def _redis_users_in_order(ids):
    """Verilen id sırasını koruyarak User satırlarını çek (PK IN — tam-tablo sıralaması yok)."""
    if not ids:
        return []
    int_ids = [int(i) for i in ids]
    users = {u.id: u for u in User.query.filter(User.id.in_(int_ids)).all()}
    return [users[i] for i in int_ids if i in users]


def _leaderboard_via_redis(scope, timeframe, key):
    """Sıralamayı Redis sorted set'ten üret; kullanıcı detayları Postgres'ten gelir."""
    if scope == "friends":
        fids = _accepted_friend_ids()
        if not fids:
            return jsonify({"scope": scope, "timeframe": timeframe, "entries": [],
                            "me": None, "in_list": False, "no_friends": True})
        member_ids = [str(i) for i in (fids | {current_user.id})]  # kendini de dahil et
        scores = redis_client.zmscore(key, member_ids)
        # Skora göre azalan, eşitlikte id artan (Postgres tiebreak'iyle aynı). Eksik = 0.
        ranked = sorted(
            ((int(mid), sc if sc is not None else 0.0)
             for mid, sc in zip(member_ids, scores)),
            key=lambda t: (-t[1], t[0]))
        top_ids = [uid for uid, _ in ranked[:LEADERBOARD_TOP_N]]
    else:
        top_ids = redis_client.zrevrange(key, 0, LEADERBOARD_TOP_N - 1)
        ranked = None  # global'de "me" rütbesi ZREVRANK ile hesaplanır

    users = _redis_users_in_order(top_ids)
    entries = [_lb_serialize(u, i + 1, timeframe) for i, u in enumerate(users)]

    in_list = any(e["is_me"] for e in entries)
    me = next((e for e in entries if e["is_me"]), None)
    if not in_list:
        if scope == "friends":
            my_rank = next((i + 1 for i, (uid, _) in enumerate(ranked)
                            if uid == current_user.id), len(ranked) + 1)
        else:
            rank = redis_client.zrevrank(key, str(current_user.id))
            my_rank = (rank + 1) if rank is not None else (redis_client.zcard(key) + 1)
        me = _lb_serialize(current_user, my_rank, timeframe)

    return jsonify({"scope": scope, "timeframe": timeframe, "entries": entries,
                    "me": me, "in_list": in_list, "no_friends": False})


def _leaderboard_via_postgres(scope, timeframe):
    """Redis erişilemezse kullanılan kaynak-doğru yol (eski ORDER BY mantığı)."""
    # Sort: XP (for the selected timeframe) desc → Streak desc → id asc (stable tiebreak).
    # Level is derived from lifetime XP and never breaks a tie that XP did not already break.
    xpc = db.func.coalesce(User.weekly_xp if timeframe == "weekly" else User.rank_points, 0)
    sc = db.func.coalesce(User.streak_count, 0)
    order = (xpc.desc(), sc.desc(), User.id.asc())

    if scope == "friends":
        fids = _accepted_friend_ids()
        if not fids:
            return jsonify({"scope": scope, "timeframe": timeframe, "entries": [],
                            "me": None, "in_list": False, "no_friends": True})
        ids = fids | {current_user.id}  # include self in the friends board
        base = User.query.filter(User.id.in_(ids))
    else:
        base = User.query

    top = base.order_by(*order).limit(LEADERBOARD_TOP_N).all()
    entries = [_lb_serialize(u, i + 1, timeframe) for i, u in enumerate(top)]

    in_list = any(e["is_me"] for e in entries)
    me = next((e for e in entries if e["is_me"]), None)
    if not in_list:
        my_xp = (current_user.weekly_xp if timeframe == "weekly" else current_user.rank_points) or 0
        my_sc = current_user.streak_count or 0
        ahead = db.or_(
            xpc > my_xp,
            db.and_(xpc == my_xp, sc > my_sc),
            db.and_(xpc == my_xp, sc == my_sc, User.id < current_user.id))
        my_rank = base.filter(ahead).count() + 1
        me = _lb_serialize(current_user, my_rank, timeframe)

    return jsonify({"scope": scope, "timeframe": timeframe, "entries": entries,
                    "me": me, "in_list": in_list, "no_friends": False})
