# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import re
import s3_helper
from flask import current_app
from werkzeug.security import generate_password_hash


def _to_float(value, default=0.0):
    """Kullanıcı JSON'undan gelen sayıyı güvenle float'a çevir; geçersiz/eksikse
    default döner (500 yerine). Diary/öğün/supplement makro & fiyat girişlerinde
    ValueError/TypeError'a karşı."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return default



_PROFILE_PIC_RE = re.compile(
    r'^data:image/(png|jpe?g|gif|webp);base64,([A-Za-z0-9+/]+={0,2})$'
)


_MAX_IMAGE_PIXELS = 40_000_000  # ~40 megapixels


_ALLOWED_IMAGE_FORMATS = {"JPEG", "PNG", "GIF", "WEBP"}


def _verify_image_bytes(image_bytes):
    """Confirm the decoded bytes are a real, sane raster image — not arbitrary
    data wearing an image/* MIME, and not a decompression bomb. The regex only
    proves the data-URL is shaped like an image; this proves the payload is one.

    Returns None on success or a user-facing error message. Fails OPEN (returns
    None) only when Pillow is unavailable — that happens in local dev where the
    dependency may be missing; production ships Pillow (see requirements.txt)."""
    try:
        from PIL import Image
    except Exception:
        current_app.logger.warning("Pillow unavailable; skipping image content verification.")
        return None
    import io as _io
    Image.MAX_IMAGE_PIXELS = _MAX_IMAGE_PIXELS
    try:
        im = Image.open(_io.BytesIO(image_bytes))
        fmt = (im.format or "").upper()
        width, height = im.size
        # verify() must run right after open() and leaves the image unusable, so
        # read format/size first, then check structural integrity.
        im.verify()
    except Exception:
        return "Geçerli bir görsel dosyası değil."
    if width * height > _MAX_IMAGE_PIXELS:
        return "Görsel çözünürlüğü çok yüksek."
    if fmt not in _ALLOWED_IMAGE_FORMATS:
        return "Desteklenmeyen görsel formatı."
    return None


def validate_profile_picture(value):
    """Return (cleaned_value, error). Only accept a base64-encoded image data
    URL. Rejecting arbitrary strings stops external/tracking URLs, javascript:
    and data:text/html payloads from being stored and later rendered in the
    <img src> of anyone who views the profile (defense against XSS/SSRF/abuse).
    """
    if not value:
        return None, None  # boş = fotoğrafı kaldır
    if len(value) > 500_000:
        return None, "Profil fotoğrafı çok büyük (maks 2MB)."
    m = _PROFILE_PIC_RE.match(value)
    if not m:
        return None, "Geçersiz profil fotoğrafı formatı."
    # base64 gövdesi gerçekten çözülebiliyor mu?
    import base64 as _b64
    try:
        image_bytes = _b64.b64decode(m.group(2), validate=True)
    except Exception:
        return None, "Profil fotoğrafı çözümlenemedi."
    # Baytlar gerçekten geçerli bir görsel mi (sahte image/* MIME / bomba değil)?
    img_error = _verify_image_bytes(image_bytes)
    if img_error:
        return None, img_error
    return value, None


def _decode_data_url_image(value, max_len):
    """Bir base64 image data-URL'ini doğrular ve (image_bytes, content_type, hata)
    olarak çözer. hata kodları: missing / too_big / bad_format / decode_failed /
    bad_image. Çağıranlar bu kodları kullanıcıya gösterilecek mesaja çevirir."""
    import base64 as _b64
    if not value:
        return None, None, "missing"
    if len(value) > max_len:
        return None, None, "too_big"
    m = _PROFILE_PIC_RE.match(value)
    if not m:
        return None, None, "bad_format"
    try:
        image_bytes = _b64.b64decode(m.group(2), validate=True)
    except Exception:
        return None, None, "decode_failed"
    # Baytlar gerçekten geçerli bir görsel mi? (sahte image/* MIME / bomba değil).
    # Bu görseller S3'e ve OpenAI vision'a gittiği için içeriği burada doğrula.
    if _verify_image_bytes(image_bytes):
        return None, None, "bad_image"
    ext = m.group(1).lower()
    content_type = "image/jpeg" if ext in ("jpg", "jpeg") else f"image/{ext}"
    return image_bytes, content_type, None


def validate_pump_check_image(value):
    """Pump Check fotoğrafı için base64 data-URL'i doğrular ve ham bayta çevirir.
    Return: (image_bytes, content_type, error)."""
    image_bytes, content_type, code = _decode_data_url_image(value, 8_000_000)
    if code:
        msg = {
            "missing": "Pump Check fotoğrafı gerekli.",
            "too_big": "Fotoğraf çok büyük (maks ~6MB).",
            "bad_format": "Geçersiz fotoğraf formatı.",
            "decode_failed": "Fotoğraf çözümlenemedi.",
            "bad_image": "Geçerli bir görsel dosyası değil.",
        }[code]
        return None, None, msg
    return image_bytes, content_type, None


def validate_meal_photo(value):
    """Öğün fotoğrafı (opsiyonel) için base64 data-URL'i doğrular. Boş değer
    geçerli kabul edilir (foto isteğe bağlı). Return: (image_bytes, content_type, error)."""
    if not value:
        return None, None, None  # fotoğraf opsiyonel
    image_bytes, content_type, code = _decode_data_url_image(value, 8_000_000)
    if code and code != "missing":
        msg = {
            "too_big": "Öğün fotoğrafı çok büyük (maks ~6MB).",
            "bad_format": "Geçersiz fotoğraf formatı.",
            "decode_failed": "Fotoğraf çözümlenemedi.",
            "bad_image": "Geçerli bir görsel dosyası değil.",
        }[code]
        return None, None, msg
    return image_bytes, content_type, None


def _meal_photo_url(meal):
    """MealLog kaydı için S3 pre-signed görsel URL'i (yoksa None)."""
    key = getattr(meal, "photo_key", None)
    if not key or not s3_helper.is_enabled():
        return None
    return s3_helper.generate_presigned_url(key, expires_in=3600)


USERNAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def validate_username(name):
    """Return an error message if username is invalid, else None.

    Restricting to [A-Za-z0-9_.-] keeps usernames safe to interpolate into
    HTML/JS/URL contexts on the client (defense against stored XSS).
    """
    if not name or len(name) < 3:
        return "Kullanıcı adı en az 3 karakter olmalıdır."
    if len(name) > 80:
        return "Kullanıcı adı en fazla 80 karakter olabilir."
    if not USERNAME_RE.match(name):
        return "Kullanıcı adı yalnızca harf, rakam, nokta, alt çizgi ve tire içerebilir."
    return None


def validate_password(password):
    """Return an error message if the password is too weak, else None.

    Min 8 chars with at least one letter and one digit raises the bar against
    brute-force/guessing. The 128-char cap bounds the work the hashing function
    does per request (avoids a DoS via a megabyte-long password).
    """
    if not password or len(password) < 8:
        return "Şifre en az 8 karakter olmalıdır."
    if len(password) > 128:
        return "Şifre en fazla 128 karakter olabilir."
    if not any(c.isalpha() for c in password):
        return "Şifre en az bir harf içermelidir."
    if not any(c.isdigit() for c in password):
        return "Şifre en az bir rakam içermelidir."
    return None


EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def validate_email(email):
    """Return an error message if the email is malformed, else None."""
    if not email or len(email) > 120 or not EMAIL_RE.match(email):
        return "Geçerli bir e-posta adresi girin."
    return None


_DUMMY_PW_HASH = generate_password_hash("timing-equalization-placeholder")
