# Auto-generated by refactor: application factory.
import os

from flask import Flask

from app.config import configure_app
from app.extensions import db, login_manager, limiter, migrate, warn_if_limiter_degraded
from app.cli import register_cli
from app.db_init import init_database

# Repo root (one level up from this package) — templates/ and static/ live there,
# matching the original Flask("starter") module-based root path.
_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def create_app():
    app = Flask(
        __name__,
        template_folder=os.path.join(_BASE_DIR, "templates"),
        static_folder=os.path.join(_BASE_DIR, "static"),
    )
    configure_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    register_blueprints(app)

    @app.route("/health")
    def health():
        # Konteyner sağlık kontrolü (Docker HEALTHCHECK). Auth gerektirmez, body okumaz.
        return {"status": "ok"}, 200

    # before_request order must match the original monolith:
    #   _csrf_protect -> (limiter) _check_request_limit -> maybe_weekly_rollover -> update_streak
    from app.hooks import _csrf_protect, generate_csp_nonce, inject_csp_nonce, \
        maybe_weekly_rollover, set_csp_header, update_streak, inject_rank, \
        ratelimit_exceeded, not_found, server_error
    app.before_request(generate_csp_nonce)
    app.before_request(_csrf_protect)
    limiter.init_app(app)
    warn_if_limiter_degraded(app)
    app.before_request(maybe_weekly_rollover)
    app.before_request(update_streak)
    app.context_processor(inject_csp_nonce)
    app.context_processor(inject_rank)
    app.after_request(set_csp_header)
    app.errorhandler(429)(ratelimit_exceeded)
    app.errorhandler(404)(not_found)
    app.errorhandler(500)(server_error)

    register_cli(app)
    init_database(app)
    return app


def register_blueprints(app):
    from app.blueprints.auth import bp as auth_bp
    from app.blueprints.profile import bp as profile_bp
    from app.blueprints.nutrition import bp as nutrition_bp
    from app.blueprints.food import bp as food_bp
    from app.blueprints.menu import bp as menu_bp
    from app.blueprints.training import bp as training_bp
    from app.blueprints.tracking import bp as tracking_bp
    from app.blueprints.social import bp as social_bp
    from app.blueprints.gamification import bp as gamification_bp
    from app.blueprints.supplements import bp as supplements_bp
    from app.blueprints.coach import bp as coach_bp
    for bp in (auth_bp, profile_bp, nutrition_bp, food_bp, menu_bp, training_bp,
               tracking_bp, social_bp, gamification_bp, supplements_bp, coach_bp):
        app.register_blueprint(bp)
