# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import re

import click

from app.extensions import db
from app.models import DailyQuest
from app.services.gamification import run_weekly_rollover


def seed_quests():
    """Insert default daily quests into the database."""
    defaults = [
        {"title": "Günlük Giriş", "description": "Bugün uygulamaya giriş yap", "points_reward": 10, "quest_type": "login"},
        {"title": "Antrenman Kaydet", "description": "Bir antrenman planı oluştur veya kaydet", "points_reward": 50, "quest_type": "workout_logged"},
        {"title": "Bir Arkadaşına Yardım Et", "description": "Bir arkadaşına mesaj gönder", "points_reward": 30, "quest_type": "suggestion_sent"},
        {"title": "Öğün Kaydet", "description": "Bugün bir öğün kaydet", "points_reward": 20, "quest_type": "meal_logged"},
    ]
    for q in defaults:
        existing = DailyQuest.query.filter_by(quest_type=q["quest_type"]).first()
        if not existing:
            db.session.add(DailyQuest(**q))
    db.session.commit()
    click.echo("Default quests seeded successfully.")


def weekly_reset_cmd():
    """Snapshot the weekly board, award top-3 XP, reset weekly_xp. Idempotent.

    Hafta sınırı artık Istanbul'da hesaplanır (B1: weekly_xp Istanbul günlerinde
    birikir). EC2 host cron `59 23 * * 0` (Sunday 23:59 UTC = Pazartesi 02:59
    Istanbul) tamamlanmış haftadan hemen sonra çalışır; idempotent olduğu için
    (WeeklyResetLog) bu ~3 saatlik gecikme yalnızca bildirimi geciktirir, yanlış
    hafta işlemez. Sınıra tam hizalamak istenirse cron'u `59 20 * * 0` (Sunday
    20:59 UTC = Pazar 23:59 Istanbul) yapın.
        flask --app starter weekly-reset
    """
    click.echo(run_weekly_rollover())



# Varsayılan "test/seed hesabı" kalıbı — sadece açıkça tohum/deneme gibi görünen
# kullanıcı adları. Gerçek kullanıcıları yanlışlıkla yakalamamak için dar tutuldu.
_DEFAULT_TEST_RE = re.compile(
    r"^(test|tester|testuser|seed|demo|dummy|sample|deneme|bulk|qa)\d*$", re.I)


def _purge_user(user):
    """Bir kullanıcıyı ve ona bağlı tüm satırları FK-güvenli sırada sil.

    FK'lerde artık ON DELETE CASCADE var (migration a1b2c3d4e5f6 + model ondelete),
    yani Postgres'te user silmek bağımlıları zaten süpürürdü. Yine de bağımlıları
    elle siliyoruz: SQLite (lokal/test) FK eylemlerini varsayılan olarak
    zorlamaz (PRAGMA foreign_keys kapalı), ve açık silme niyeti belirsizliğe yer
    bırakmaz. Bu kullanıcının davet ettiği kişilerin referred_by_id'si NULL'a
    çekilir (FK'de SET NULL olsa da burada da açıkça yapılır).
    """
    from app.models import (
        Activity, CustomMeal, CustomMealItem, DailyActivity, Friendship, MealLog,
        Message, NutritionPlan, PendingAction, PumpCheck, PumpCheckComment,
        PumpCheckLike, Supplement, TrainingPlan, User, UserQuestProgress,
        UserSession, UserWearableConnection, WaterLog, WearableActivityLog,
        WearableSleepLog, WearableWorkoutLog, WeeklyCheckIn, WeeklyLog,
        WeeklyWinner, WorkoutLog,
    )
    uid = user.id

    # CustomMealItem yalnızca custom_meal üzerinden user'a bağlı.
    meal_ids = [m.id for m in CustomMeal.query.filter_by(user_id=uid).all()]
    if meal_ids:
        CustomMealItem.query.filter(
            CustomMealItem.custom_meal_id.in_(meal_ids)
        ).delete(synchronize_session=False)

    pump_ids = [p.id for p in PumpCheck.query.filter_by(user_id=uid).all()]
    pump_child_filter = [PumpCheckLike.user_id == uid]
    comment_child_filter = [PumpCheckComment.user_id == uid]
    if pump_ids:
        pump_child_filter.append(PumpCheckLike.pump_check_id.in_(pump_ids))
        comment_child_filter.append(PumpCheckComment.pump_check_id.in_(pump_ids))
    PumpCheckLike.query.filter(db.or_(*pump_child_filter)).delete(
        synchronize_session=False)
    PumpCheckComment.query.filter(db.or_(*comment_child_filter)).delete(
        synchronize_session=False)

    for Model in (UserSession, WeeklyLog, WeeklyCheckIn, NutritionPlan, TrainingPlan,
                  MealLog, PendingAction, PumpCheck, Activity, Supplement,
                  UserQuestProgress, WeeklyWinner, WaterLog, WorkoutLog,
                  DailyActivity, WearableSleepLog, WearableActivityLog,
                  WearableWorkoutLog, UserWearableConnection, CustomMeal):
        Model.query.filter_by(user_id=uid).delete(synchronize_session=False)

    Friendship.query.filter(
        db.or_(Friendship.sender_id == uid, Friendship.receiver_id == uid)
    ).delete(synchronize_session=False)
    Message.query.filter(
        db.or_(Message.sender_id == uid, Message.receiver_id == uid)
    ).delete(synchronize_session=False)

    User.query.filter_by(referred_by_id=uid).update(
        {"referred_by_id": None}, synchronize_session=False)

    db.session.delete(user)


@click.option("--username", default=None,
              help="Tek bir kullanıcı adını hedefle (tam, büyük/küçük harf duyarsız).")
@click.option("--pattern", default=None,
              help="Özel regex (verilmezse varsayılan test/seed kalıbı kullanılır).")
@click.option("--yes", is_flag=True, help="Onayla ve gerçekten sil (yoksa kuru çalışma).")
def cleanup_test_users(username, pattern, yes):
    """Sızıntı kalan test/seed hesaplarını (ör. 'test') sil.

    Varsayılan KURU ÇALIŞMA — sadece eşleşenleri listeler. Silmek için --yes ekleyin:

        flask --app starter cleanup-test-users                 # önizleme
        flask --app starter cleanup-test-users --yes           # sil
        flask --app starter cleanup-test-users --username test --yes
    """
    from app.models import User

    if username:
        users = User.query.filter(
            db.func.lower(User.username) == username.lower()).all()
    else:
        rx = re.compile(pattern, re.I) if pattern else _DEFAULT_TEST_RE
        users = [u for u in User.query.all() if rx.match(u.username or "")]

    if not users:
        click.echo("Eşleşen test kullanıcısı bulunamadı.")
        return

    click.echo(f"{len(users)} kullanıcı eşleşti:")
    for u in users:
        click.echo(f"  - id={u.id}  username={u.username!r}  email={u.email}  "
                   f"xp={u.rank_points or 0}")

    if not yes:
        click.echo("\nKURU ÇALIŞMA — hiçbir şey silinmedi. Silmek için --yes ekleyin.")
        return

    for u in users:
        _purge_user(u)
    db.session.commit()

    # Liderlik sorted set'lerinden de düşsünler.
    try:
        from app.services.gamification import lb_rebuild
        lb_rebuild()
    except Exception:
        pass

    click.echo(f"\n✓ {len(users)} kullanıcı ve ilişkili kayıtları silindi.")


def register_cli(app):
    app.cli.command("seed-quests")(seed_quests)
    app.cli.command("weekly-reset")(weekly_reset_cmd)
    app.cli.command("cleanup-test-users")(cleanup_test_users)
