# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import logging
import os
import time
from werkzeug.middleware.proxy_fix import ProxyFix
from dotenv import load_dotenv



load_dotenv()

_BOOT_TS = int(time.time())  # cache-bust static assets on each deploy
FATSECRET_TOKEN_URL = "https://oauth.fatsecret.com/connect/token"
# Güvensiz bir varsayılan YOK: ayarlanmazsa boş kalır ve _enforce_fatsecret_tls
# uyarır. Eski hardcoded "http://<public-ip>:3000" varsayılanı, FATSECRET_BASE_URL
# prod'da ayarlanmazsa OAuth bearer token'ını düz metin HTTP üzerinde sızdırıyordu.
FATSECRET_BASE_URL = os.environ.get("FATSECRET_BASE_URL", "")
FATSECRET_API_URL = f"{FATSECRET_BASE_URL}/rest/server.api"
_REDIS_URL = os.environ.get("REDIS_URL")
LB_ALLTIME_KEY = "lb:global:alltime"
LB_WEEKLY_KEY  = "lb:global:weekly"
_IS_DEV = os.environ.get("FLASK_DEBUG") == "1" or os.environ.get("FLASK_ENV") == "development"

# CSP img-src için S3 host(lar)ı: geniş `https://*.amazonaws.com` joker'i yerine
# yalnızca bu uygulamanın kovasına/bölgesine izin ver (virtual-hosted + path-style
# pre-signed URL biçimleri). Kova ayarlı değilse (lokal/test) avatar zaten base64
# (data:) olduğundan S3 host'u eklenmez.
_S3_BUCKET = os.environ.get("S3_BUCKET_NAME", "").strip()
_S3_REGION = os.environ.get("AWS_REGION", "eu-central-1")
if _S3_BUCKET:
    CSP_IMG_S3_HOSTS = (
        f"https://{_S3_BUCKET}.s3.{_S3_REGION}.amazonaws.com "
        f"https://s3.{_S3_REGION}.amazonaws.com"
    )
else:
    CSP_IMG_S3_HOSTS = ""
AI_RATELIMIT = "30 per hour"           # OpenAI text/vision generation
SCRAPE_RATELIMIT = "20 per hour"       # menu scraper (outbound fetch + AI; also SSRF surface)
FOOD_SEARCH_RATELIMIT = "60 per hour"  # food search (LLM only fires on a FatSecret miss)
# Kullanıcı arama (/friends/search): kullanıcı-adı sayımına (enumeration) karşı
# throttle. UI 300ms debounce'lu olduğundan meşru typeahead bu tavanı zorlamaz;
# kullanıcı/IP başına anahtarlanır.
SEARCH_RATELIMIT = "20 per minute; 200 per hour"
# Sonnet (Bedrock) pahalı olduğundan, ağır ÜRETKEN Sonnet route'larına AI_RATELIMIT
# üstüne binen, daha sıkı kullanıcı-başı ikinci tavan. Env ile ayarlanabilir.
BEDROCK_RATELIMIT = os.getenv("BEDROCK_RATELIMIT", "10 per hour")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
# ── Bedrock (Claude Sonnet 4.5 — ağır görevler) ──
# Kimlik bilgisi EC2 IAM Instance Profile'dan gelir (S3 ile aynı); kodda/.env'de anahtar yok.
BEDROCK_REGION = os.getenv("BEDROCK_REGION") or os.getenv("AWS_REGION", "eu-central-1")
BEDROCK_MODEL = os.getenv("BEDROCK_MODEL", "global.anthropic.claude-sonnet-4-5-20250929-v1:0")
BEDROCK_MAX_TOKENS = int(os.getenv("BEDROCK_MAX_TOKENS", "8000"))
BEDROCK_ENABLED = os.getenv("BEDROCK_ENABLED", "0") == "1"  # açık opt-in; prod .env'de =1
# Bedrock prompt caching (cache_control: ephemeral). Statik sistem promptu + araç
# tanımları önbelleğe alınır; deploy bölgesinde (eu-central-1) doğrulanana kadar
# KARANLIK gönder (varsayılan kapalı). Yalnızca tool-use koç döngüsünü etkiler.
BEDROCK_PROMPT_CACHE = os.getenv("BEDROCK_PROMPT_CACHE", "0") == "1"

# ── Amazon Cognito (e-posta ile giriş — OIDC / Hosted UI) ──
# Kullanıcı havuzu ve app client .env'den gelir. App client'ın bir "client secret"i
# VARSA COGNITO_CLIENT_SECRET olarak ekle; YOKSA (public client) boş bırak — PKCE
# kullanılır. Region pool id'nin önekinden türetilir (örn. "eu-central-1_xxx" →
# "eu-central-1"); böylece ayrıca tanımlamaya gerek kalmaz.
COGNITO_USER_POOL_ID = os.getenv("COGNITO_USER_POOL_ID", "").strip()
COGNITO_APP_CLIENT_ID = os.getenv("COGNITO_APP_CLIENT_ID", "").strip()
COGNITO_CLIENT_SECRET = os.getenv("COGNITO_CLIENT_SECRET", "").strip()
COGNITO_REGION = (
    COGNITO_USER_POOL_ID.split("_", 1)[0] if "_" in COGNITO_USER_POOL_ID else _S3_REGION
)
COGNITO_ENABLED = bool(COGNITO_USER_POOL_ID and COGNITO_APP_CLIENT_ID)
COGNITO_METADATA_URL = (
    f"https://cognito-idp.{COGNITO_REGION}.amazonaws.com/"
    f"{COGNITO_USER_POOL_ID}/.well-known/openid-configuration"
) if COGNITO_ENABLED else ""
# Hosted UI domain'i (opsiyonel, örn. "fitx.auth.eu-central-1.amazoncognito.com").
# Ayarlıysa /logout Cognito oturumunu da kapatır (aksi halde yalnızca yerel oturum).
COGNITO_HOSTED_DOMAIN = os.getenv("COGNITO_HOSTED_DOMAIN", "").strip()


def _enforce_fatsecret_tls(app):
    from urllib.parse import urlparse as _urlparse
    if not FATSECRET_BASE_URL:
        app.logger.warning(
            "FATSECRET_BASE_URL ayarlı değil — FatSecret entegrasyonu çalışmaz. "
            "https:// bir endpoint'e işaret ettir.")
        return
    p = _urlparse(FATSECRET_BASE_URL)
    host = (p.hostname or "").lower()
    is_local = host in ("localhost", "127.0.0.1", "::1")
    if p.scheme == "https" or is_local:
        return
    # Düz metin HTTP + loopback dışı: debug olsun olmasın engelle. Token Authorization
    # header'ında gidiyor; cleartext kabul edilemez. Lokal http proxy'e karşı test
    # için bilinçli FATSECRET_ALLOW_INSECURE=1 escape-hatch'i gerekir.
    if os.environ.get("FATSECRET_ALLOW_INSECURE") == "1":
        app.logger.warning(
            "FATSECRET_BASE_URL düz metin http (%s) — FATSECRET_ALLOW_INSECURE=1 ile "
            "izin verildi. Bearer token tel üzerinde açıkta; yalnızca lokal test için.",
            FATSECRET_BASE_URL,
        )
        return
    raise RuntimeError(
        "FATSECRET_BASE_URL must use https:// — the FatSecret OAuth token is sent "
        "in the Authorization header and would otherwise travel in cleartext. Point "
        "FATSECRET_BASE_URL at an https:// endpoint (terminate TLS in front of the "
        "proxy), or set FATSECRET_ALLOW_INSECURE=1 for local http testing."
    )


def configure_app(app):
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1)
    _LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
    _gunicorn_logger = logging.getLogger("gunicorn.error")
    if _gunicorn_logger.handlers:
        app.logger.handlers = _gunicorn_logger.handlers
        app.logger.setLevel(_gunicorn_logger.level or getattr(logging, _LOG_LEVEL, logging.INFO))
    else:
        logging.basicConfig(level=getattr(logging, _LOG_LEVEL, logging.INFO))
        app.logger.setLevel(getattr(logging, _LOG_LEVEL, logging.INFO))
    database_url = os.environ.get("DATABASE_URL", "sqlite:///chatbot.db")
    if database_url.startswith("postgres://"):
        database_url = database_url.replace("postgres://", "postgresql://", 1)
    app.config["SQLALCHEMY_DATABASE_URI"] = database_url
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    _secret_key = os.environ.get("SECRET_KEY")
    if not _secret_key:
        # Allow boot without SECRET_KEY only in explicit debug mode, and generate
        # a per-process random key so dev sessions still cannot be forged from
        # a known constant. Sessions invalidate on restart, which is fine in dev.
        if os.environ.get("FLASK_DEBUG") == "1" or os.environ.get("FLASK_ENV") == "development":
            import secrets as _secrets
            _secret_key = _secrets.token_urlsafe(32)
            app.logger.warning("SECRET_KEY not set; using ephemeral dev key (sessions invalidate on restart).")
        else:
            raise RuntimeError(
                "SECRET_KEY environment variable must be set. "
                "Set FLASK_DEBUG=1 to allow an ephemeral key for local development."
            )
    app.config["SECRET_KEY"] = _secret_key
    _enforce_fatsecret_tls(app)
    app.config["SESSION_COOKIE_HTTPONLY"] = True
    app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
    app.config["SESSION_COOKIE_SECURE"] = not _IS_DEV
    app.config["REMEMBER_COOKIE_HTTPONLY"] = True
    app.config["REMEMBER_COOKIE_SAMESITE"] = "Lax"
    app.config["REMEMBER_COOKIE_SECURE"] = not _IS_DEV
