# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import logging
import os
import time
from werkzeug.middleware.proxy_fix import ProxyFix
from dotenv import load_dotenv



load_dotenv()

_BOOT_TS = int(time.time())  # cache-bust static assets on each deploy
FATSECRET_TOKEN_URL = "https://oauth.fatsecret.com/connect/token"
FATSECRET_BASE_URL = os.environ.get("FATSECRET_BASE_URL", "http://18.153.156.28:3000")
FATSECRET_API_URL = f"{FATSECRET_BASE_URL}/rest/server.api"
_REDIS_URL = os.environ.get("REDIS_URL")
LB_ALLTIME_KEY = "lb:global:alltime"
LB_WEEKLY_KEY  = "lb:global:weekly"
_IS_DEV = os.environ.get("FLASK_DEBUG") == "1" or os.environ.get("FLASK_ENV") == "development"
AI_RATELIMIT = "30 per hour"           # OpenAI text/vision generation
SCRAPE_RATELIMIT = "20 per hour"       # menu scraper (outbound fetch + AI; also SSRF surface)
FOOD_SEARCH_RATELIMIT = "60 per hour"  # food search (LLM only fires on a FatSecret miss)
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")


def _enforce_fatsecret_tls(app):
    from urllib.parse import urlparse as _urlparse
    p = _urlparse(FATSECRET_BASE_URL)
    host = (p.hostname or "").lower()
    is_local = host in ("localhost", "127.0.0.1", "::1")
    if p.scheme == "https" or is_local:
        return
    if _IS_DEV:
        app.logger.warning(
            "FATSECRET_BASE_URL uses plaintext http (%s) — the FatSecret bearer "
            "token is exposed on the wire. Use https:// outside local dev.",
            FATSECRET_BASE_URL,
        )
        return
    raise RuntimeError(
        "FATSECRET_BASE_URL must use https:// in production — the FatSecret "
        "OAuth token is sent in the Authorization header and would otherwise be "
        "transmitted in cleartext. Point FATSECRET_BASE_URL at an https:// "
        "endpoint (terminate TLS in front of the proxy), or set FLASK_DEBUG=1 "
        "for local http testing."
    )


def configure_app(app):
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1)
    _LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
    _gunicorn_logger = logging.getLogger("gunicorn.error")
    if _gunicorn_logger.handlers:
        app.logger.handlers = _gunicorn_logger.handlers
        app.logger.setLevel(_gunicorn_logger.level or getattr(logging, _LOG_LEVEL, logging.INFO))
    else:
        logging.basicConfig(level=getattr(logging, _LOG_LEVEL, logging.INFO))
        app.logger.setLevel(getattr(logging, _LOG_LEVEL, logging.INFO))
    database_url = os.environ.get("DATABASE_URL", "sqlite:///chatbot.db")
    if database_url.startswith("postgres://"):
        database_url = database_url.replace("postgres://", "postgresql://", 1)
    app.config["SQLALCHEMY_DATABASE_URI"] = database_url
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    _secret_key = os.environ.get("SECRET_KEY")
    if not _secret_key:
        # Allow boot without SECRET_KEY only in explicit debug mode, and generate
        # a per-process random key so dev sessions still cannot be forged from
        # a known constant. Sessions invalidate on restart, which is fine in dev.
        if os.environ.get("FLASK_DEBUG") == "1" or os.environ.get("FLASK_ENV") == "development":
            import secrets as _secrets
            _secret_key = _secrets.token_urlsafe(32)
            app.logger.warning("SECRET_KEY not set; using ephemeral dev key (sessions invalidate on restart).")
        else:
            raise RuntimeError(
                "SECRET_KEY environment variable must be set. "
                "Set FLASK_DEBUG=1 to allow an ephemeral key for local development."
            )
    app.config["SECRET_KEY"] = _secret_key
    _enforce_fatsecret_tls(app)
    app.config["SESSION_COOKIE_HTTPONLY"] = True
    app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
    app.config["SESSION_COOKIE_SECURE"] = not _IS_DEV
    app.config["REMEMBER_COOKIE_HTTPONLY"] = True
    app.config["REMEMBER_COOKIE_SAMESITE"] = "Lax"
    app.config["REMEMBER_COOKIE_SECURE"] = not _IS_DEV
