# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import os

from app.extensions import db
from app.models import DailyQuest
from app.services.gamification import lb_rebuild


def init_database(app):
    # Alembic/Flask-Migrate komutları (flask db migrate/upgrade/stamp) app
    # factory'yi import eder; bu sırada create_all çalışırsa autogenerate boş
    # diff görür ve taze DB'lerde migration zinciri anlamsızlaşır. Migration
    # komutlarını çalıştırırken FITX_SKIP_DB_INIT=1 ayarla (bkz. CLAUDE.md).
    if os.environ.get("FITX_SKIP_DB_INIT") == "1":
        return
    _migrations_dir = os.path.join(app.root_path, "..", "migrations")
    with app.app_context():
        # ── Alembic zinciri (konsolsuz, kendi kendine yeten) ──
        # Bekleyen migration'lar create_all'dan ÖNCE uygulanmalı: yeni bir
        # migration tablo oluşturuyorsa create_all onu önce yaratır ve
        # op.create_table çakışırdı. Compose tek instance/tek worker çalıştırdığı
        # için boot'ta otomatik upgrade'de eşzamanlı migration yarışı yok.
        _has_alembic = False
        try:
            from sqlalchemy import inspect as sa_inspect
            _has_alembic = sa_inspect(db.engine).has_table("alembic_version")
            if _has_alembic and os.path.isdir(_migrations_dir):
                from flask_migrate import upgrade
                upgrade()
        except Exception:
            # Migration hatası boot'u öldürmesin; logla ki deploy çıktısında görünsün.
            db.session.rollback()
            app.logger.exception("[DB] Alembic upgrade başarısız — şema migration zinciri gerisinde kalmış olabilir.")

        db.create_all()
        migrations = [
            'ALTER TABLE "user" ADD COLUMN last_login DATE',
            'ALTER TABLE supplement RENAME COLUMN rating_effectiveness TO rating_effect',
            'ALTER TABLE supplement ADD COLUMN rating_digestion INTEGER',
            'ALTER TABLE message ADD COLUMN message_type VARCHAR(20) DEFAULT \'text\'',
            'ALTER TABLE "user" ADD COLUMN target_weight FLOAT',
            'ALTER TABLE "user" ADD COLUMN goal_type VARCHAR(10)',
            'ALTER TABLE "user" ALTER COLUMN profile_picture TYPE TEXT',
            'ALTER TABLE message ALTER COLUMN message_type TYPE VARCHAR(50)',
            'ALTER TABLE meal_log ALTER COLUMN ogun TYPE VARCHAR(100)',
            'ALTER TABLE meal_log ADD COLUMN source VARCHAR(20) DEFAULT \'manual\'',
            'ALTER TABLE meal_log ADD COLUMN photo_key VARCHAR(300)',
            'UPDATE user_quest_progress SET is_claimed = true WHERE is_claimed = false',
            'ALTER TABLE custom_meal_item ADD COLUMN serving_id VARCHAR(50)',
            'ALTER TABLE custom_meal_item ADD COLUMN serving_description VARCHAR(200)',
            'ALTER TABLE custom_meal_item ADD COLUMN serving_quantity FLOAT',
            'ALTER TABLE "user" ADD COLUMN weekly_xp INTEGER DEFAULT 0',
            'ALTER TABLE "user" ADD COLUMN last_reward_week VARCHAR(10)',
            # Davet/referral + freemium kolonları (idempotent — kolon varsa sessizce geçilir)
            'ALTER TABLE "user" ADD COLUMN referral_code VARCHAR(12)',
            'ALTER TABLE "user" ADD COLUMN referred_by_id INTEGER',
            'ALTER TABLE "user" ADD COLUMN is_premium BOOLEAN DEFAULT false',
            'ALTER TABLE "user" ADD COLUMN premium_since TIMESTAMP',
            'ALTER TABLE "user" ADD COLUMN profile_picture_key VARCHAR(300)',
            # AI koç hafızası (sakatlıklar/tercihler) — JSONB (RDS PostgreSQL).
            'ALTER TABLE "user" ADD COLUMN user_metadata JSONB',
            # Görev isimlerini Türkçeleştir (eski İngilizce kayıtları da güncelle)
            "UPDATE daily_quest SET title = 'Günlük Giriş' WHERE quest_type = 'login'",
            "UPDATE daily_quest SET title = 'Antrenman Kaydet' WHERE quest_type = 'workout_logged'",
            "UPDATE daily_quest SET title = 'Bir Arkadaşına Yardım Et' WHERE quest_type = 'suggestion_sent'",
            "UPDATE daily_quest SET title = 'Dolabını Güncelle' WHERE quest_type = 'supplement_added'",
            "UPDATE daily_quest SET title = 'Öğün Kaydet' WHERE quest_type = 'meal_logged'",
        ]
        for sql in migrations:
            try:
                db.session.execute(db.text(sql))
                db.session.commit()
            except Exception as e:
                db.session.rollback()
                # Çoğu hata beklenen idempotent durum ("column already exists");
                # bu yüzden debug seviyesi — ama tamamen yutma ki gerçek bir ALTER
                # başarısızlığı gerektiğinde teşhis edilebilsin (TRIAGE_FIXES #6).
                app.logger.debug("[DB] idempotent ALTER atlandı: %s — %s: %s",
                                 sql, type(e).__name__, e)

        # PL/pgSQL trigger for PostgreSQL activity calorie auto-calculation
        try:
            db.session.execute(db.text("""
                CREATE OR REPLACE FUNCTION calc_activity_calories()
                RETURNS TRIGGER AS $$
                DECLARE
                    w FLOAT; h FLOAT; stride FLOAT; dist FLOAT; dur FLOAT;
                    met_val FLOAT; spd FLOAT;
                BEGIN
                    SELECT weight, height INTO w, h FROM "user" WHERE id = NEW.user_id;
                    w := COALESCE(w, 70); h := COALESCE(h, 170);
                    met_val := CASE NEW.intensity
                        WHEN 'light' THEN 2.0 WHEN 'moderate' THEN 3.5
                        WHEN 'brisk' THEN 4.3 WHEN 'fast' THEN 5.0 ELSE 3.5 END;
                    spd := CASE NEW.intensity
                        WHEN 'light' THEN 3.0 WHEN 'moderate' THEN 4.5
                        WHEN 'brisk' THEN 5.5 WHEN 'fast' THEN 6.5 ELSE 4.5 END;
                    stride := h * 0.414;
                    dist := NEW.steps * stride / 100000.0;
                    dur := dist / spd;
                    NEW.calories_burned := ROUND((met_val * w * dur)::numeric, 1);
                    NEW.distance_km := ROUND(dist::numeric, 2);
                    NEW.duration_min := ROUND((dur * 60)::numeric, 1);
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """))
            db.session.execute(db.text("""
                DROP TRIGGER IF EXISTS trg_calc_activity ON daily_activity;
                CREATE TRIGGER trg_calc_activity
                BEFORE INSERT OR UPDATE ON daily_activity
                FOR EACH ROW EXECUTE FUNCTION calc_activity_calories();
            """))
            db.session.commit()
        except Exception:
            db.session.rollback()
        if DailyQuest.query.count() == 0:
            for q in [
                DailyQuest(title="Günlük Giriş", description="Bugün uygulamaya giriş yap", points_reward=10, quest_type="login"),
                DailyQuest(title="Antrenman Kaydet", description="Bir antrenman planı oluştur veya kaydet", points_reward=50, quest_type="workout_logged"),
                DailyQuest(title="Bir Arkadaşına Yardım Et", description="Bir arkadaşına mesaj gönder", points_reward=30, quest_type="suggestion_sent"),
            ]:
                db.session.add(q)
            db.session.commit()
        if not DailyQuest.query.filter_by(quest_type="supplement_added").first():
            db.session.add(DailyQuest(
                title="Dolabını Güncelle",
                description="Supplement dolabına yeni bir ürün ekle",
                points_reward=25, quest_type="supplement_added"
            ))
            db.session.commit()
        if not DailyQuest.query.filter_by(quest_type="meal_logged").first():
            db.session.add(DailyQuest(
                title="Log a Meal",
                description="Bugün bir öğün kaydet",
                points_reward=20, quest_type="meal_logged"
            ))
            db.session.commit()

        # Görev ekonomisini derinleştir: dönüşümlü ek görevler (su / check-in / davet).
        # Idempotent — her quest_type yalnızca bir kez eklenir.
        _extra_quests = [
            ("meal_logged",      "Öğün Kaydet",          "Bugün bir öğün kaydet",                         15),
            ("water_logged",     "Su Hedefi",            "Bugün su takibini güncelle",                    10),
            ("checkin_done",     "Haftalık Check-in",    "Kilonu güncelle veya check-in yap",             20),
            ("friend_invited",   "Bir Arkadaşını Davet Et", "Davet bağlantını bir arkadaşınla paylaş",    40),
        ]
        for qtype, title, desc, pts in _extra_quests:
            if not DailyQuest.query.filter_by(quest_type=qtype).first():
                db.session.add(DailyQuest(title=title, description=desc,
                                          points_reward=pts, quest_type=qtype))
        db.session.commit()

        # Davet kodu olmayan mevcut kullanıcılara tek seferlik backfill.
        try:
            from app.services.referral import backfill_referral_codes
            backfill_referral_codes()
        except Exception:
            db.session.rollback()

        # Şema az önce create_all + legacy ALTER'larla güncel hâle geldi; DB henüz
        # Alembic zincirinde değilse baseline'ı çalıştırmadan "head" olarak damgala.
        # Mevcut prod DB'ler ve taze kurulumlar böylece konsola gerek kalmadan
        # zincire girer; manuel `flask db stamp head` gerekmez.
        if not _has_alembic:
            try:
                from flask_migrate import stamp
                if os.path.isdir(_migrations_dir):
                    stamp()
                    app.logger.info("[DB] Mevcut şema Alembic baseline olarak damgalandı.")
            except Exception:
                db.session.rollback()
                app.logger.exception("[DB] Alembic stamp başarısız — şema migration zinciri dışında kaldı.")

        # Liderlik sorted set'lerini Postgres'ten doldur (Redis varsa). Redis sonradan
        # ayağa kalkarsa ilk leaderboard isteği zaten Postgres'e düşer; sonraki restart hidratlar.
        lb_rebuild()
