# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import secrets
from datetime import datetime, timedelta
from flask import abort, current_app, g, jsonify, render_template, request, session
from flask_login import current_user

from app.config import _BOOT_TS, CSP_IMG_S3_HOSTS
from app.extensions import db
from app.services.gamification import _last_rollover_check, _mark_lb_dirty, award_xp, get_level, get_title, log_activity, run_weekly_rollover
from app.timeutil import app_today


def generate_csp_nonce():
    """Her istek için tek kullanımlık CSP nonce'u üret. Şablonlardaki satır-içi
    <script nonce="{{ csp_nonce }}"> blokları bu değerle imzalanır; başlıktaki
    nonce ile eşleşmeyen (örn. XSS ile enjekte edilen) script'ler çalışmaz."""
    g.csp_nonce = secrets.token_urlsafe(16)


def set_csp_header(response):
    """Content-Security-Policy başlığını uygula (nginx'ten buraya taşındı —
    nonce per-request üretildiği için statik nginx config'de yazılamaz).

    script-src: 'unsafe-inline' KALDIRILDI — satır-içi script blokları artık
    nonce ister. script-src-attr 'none': tüm satır-içi nitelik-handler'ları
    (onclick=...) yasak. Şablonlardaki/JS'teki on* işleyicileri data-action
    delegasyonuyla (static/actions.js) değiştirildi, böylece bu vektör tamamen
    kapatıldı; asıl enjeksiyon vektörü <script> blokları zaten nonce'a tabidir.
    img-src: 'https:' (tüm hostlar) yerine yalnızca S3 (pre-signed URL'ler,
    *.amazonaws.com) + data: (base64 profil/önizleme görselleri).
    Google Analytics (gtag.js, index.html): script/img/connect kaynakları
    Google'ın resmî CSP rehberindeki host setiyle açıldı."""
    nonce = getattr(g, "csp_nonce", "")
    # img-src: geniş `https://*.amazonaws.com` yerine yalnızca bu uygulamanın S3
    # kovası/bölgesi (config.CSP_IMG_S3_HOSTS). data: base64 avatar/önizleme için
    # gerekli olduğundan korunur.
    s3_src = (CSP_IMG_S3_HOSTS + " ") if CSP_IMG_S3_HOSTS else ""
    response.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        f"script-src 'self' 'nonce-{nonce}' https://cdn.jsdelivr.net "
        "https://*.googletagmanager.com; "
        "script-src-attr 'none'; "
        # style-src: 'unsafe-inline' fallback yalnızca style-src-elem/-attr'ı
        # desteklemeyen ESKİ tarayıcılar için tutulur. Modern tarayıcılar daha
        # SIKI alt-direktifleri uygular:
        #   style-src-elem: <style> blokları + <link> stylesheet → 'unsafe-inline'
        #     KALDIRILDI; satır-içi <style> blokları artık per-request NONCE ister
        #     (XSS ile enjekte edilen <style> — CSS exfil/UI-redress vektörü — çalışmaz).
        #   style-src-attr 'unsafe-inline': dinamik style="..." nitelikleri (örn.
        #     progress-bar genişlikleri) nonce alamadığından kaçınılmaz; bu dar
        #     vektör açık kalır ama tam <style> enjeksiyonundan çok daha sınırlıdır.
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        f"style-src-elem 'self' 'nonce-{nonce}' https://fonts.googleapis.com; "
        "style-src-attr 'unsafe-inline'; "
        "font-src 'self' https://fonts.gstatic.com data:; "
        f"img-src 'self' data: {s3_src}"
        "https://*.google-analytics.com https://*.googletagmanager.com; "
        "connect-src 'self' https://*.google-analytics.com "
        "https://*.analytics.google.com https://*.googletagmanager.com; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self'; "
        "object-src 'none'"
    )
    return response


def inject_csp_nonce():
    return {"csp_nonce": getattr(g, "csp_nonce", "")}


_CSRF_SESSION_KEY = "_csrf_token"


def get_csrf_token():
    """Bu oturuma bağlı CSRF synchronizer token'ı döndür (yoksa üret ve sakla).

    Token, imzalı oturum çerezinde tutulur (sunucu-taraflı kanıt). Şablonlara
    <meta name="csrf-token"> ile sızdırılır; frontend (static/actions.js) durum-
    değiştiren her fetch'e X-CSRFToken başlığı olarak ekler. _csrf_protect bu
    başlığı oturumdaki değerle karşılaştırır."""
    token = session.get(_CSRF_SESSION_KEY)
    if not token:
        token = secrets.token_urlsafe(32)
        session[_CSRF_SESSION_KEY] = token
    return token


def inject_csrf_token():
    return {"csrf_token": get_csrf_token()}


def _csrf_protect():
    """Reject state-changing requests that fail our two CSRF layers.

    Cookie-authenticated POST/PUT/PATCH/DELETE requests are the CSRF attack
    surface. Defence-in-depth:
      1) Origin/Referer must match our host (a cross-site forgery cannot forge
         these; same-origin fetch() sends them automatically).
      2) A per-session synchronizer token (X-CSRFToken header) must match the
         token stored in the session — an attacker cannot read it (cross-origin)
         nor set a custom header, so this holds even if a future change weakens
         layer 1. The frontend adds the header globally (static/actions.js).
    """
    if request.method not in ("POST", "PUT", "PATCH", "DELETE"):
        return
    from urllib.parse import urlparse
    expected_host = request.host.split(":")[0]

    # ── Layer 1: Origin/Referer ──
    # Prefer Origin: a browser always sends it on cross-origin (and most same-origin)
    # state-changing fetch()es and it cannot be forged cross-site.
    origin = request.headers.get("Origin")
    if origin:
        if urlparse(origin).hostname != expected_host:
            abort(403, description="CSRF doğrulaması başarısız.")
    else:
        # Referer fallback only when Origin is absent (older browsers / some
        # proxies strip Origin). Weaker — log each Referer-only approval.
        referer = request.headers.get("Referer")
        if not referer:
            abort(403, description="CSRF doğrulaması başarısız.")
        if urlparse(referer).hostname != expected_host:
            abort(403, description="CSRF doğrulaması başarısız.")
        current_app.logger.info(
            "[CSRF] Origin yok; Referer ile onaylandı: %s %s (referer=%s)",
            request.method, request.path, referer)

    # ── Layer 2: synchronizer token ──
    _csrf_validate_token()


def _csrf_validate_token():
    expected = session.get(_CSRF_SESSION_KEY)
    sent = request.headers.get("X-CSRFToken")
    if not expected or not sent or not secrets.compare_digest(str(sent), str(expected)):
        current_app.logger.info(
            "[CSRF] Token doğrulaması başarısız: %s %s", request.method, request.path)
        abort(403, description="CSRF token doğrulaması başarısız.")


def ratelimit_exceeded(e):
    return jsonify({"error": "Çok fazla deneme yaptınız. Lütfen biraz sonra tekrar deneyin."}), 429


def maybe_weekly_rollover():
    now = datetime.utcnow()
    last = _last_rollover_check[0]
    if last is not None and (now - last).total_seconds() < 300:
        return
    _last_rollover_check[0] = now
    try:
        run_weekly_rollover(now)
    except Exception:
        db.session.rollback()
        # Sessizce yutma: rollover hatası liderlik/ödül tutarlılığını bozabilir,
        # olay tespiti için logla (S6/3.6).
        current_app.logger.warning("[ROLLOVER] Haftalık rollover başarısız", exc_info=True)


def update_streak():
    if current_user.is_authenticated:
        today = app_today()
        if current_user.last_login != today:
            if current_user.last_login == today - timedelta(days=1):
                current_user.streak_count = (current_user.streak_count or 0) + 1
            else:
                current_user.streak_count = 1
            # Bu istekten ÖNCEKI last_login'i sakla: get_nudges seri-riski dürtüsünü
            # "günün ilk isteğinde henüz aktif değildi" mantığıyla doğru tetiklesin
            # (aksi halde aşağıdaki güncelleme yüzünden asla tetiklenmez).
            g.prev_last_login = current_user.last_login
            current_user.last_login = today
            streak = current_user.streak_count
            if streak in (7, 14, 30, 60, 100):
                log_activity(current_user.id, "streak_milestone",
                             f"{streak} günlük seri yakalanadı!")
                award_xp(current_user.id, streak * 2)
            # streak tiebreak'i değişti → commit sonrası Redis sync (after_commit).
            # Milestone yoksa award_xp dirty işaretlemez; burada elle işaretliyoruz.
            _mark_lb_dirty(current_user.id)
            db.session.commit()


def inject_rank():
    base = {"_v": _BOOT_TS}
    if current_user.is_authenticated:
        xp = current_user.rank_points or 0
        level = get_level(xp)
        title = get_title(level)
        xp_in_level = xp % 500
        return {**base,
            "rank_points": xp, "rank_title": title,
            "user_xp": xp, "user_level": level, "user_title": title,
            "xp_in_level": xp_in_level, "xp_for_next": 500,
        }
    return {**base,
        "rank_points": 0, "rank_title": "Fitness Yolcusu",
        "user_xp": 0, "user_level": 1, "user_title": "Fitness Yolcusu",
        "xp_in_level": 0, "xp_for_next": 500,
    }


def not_found(e):
    return render_template("404.html"), 404


def server_error(e):
    return render_template("500.html"), 500
