# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import secrets
from datetime import date, datetime, timedelta
from flask import abort, g, jsonify, render_template, request
from flask_login import current_user

from app.config import _BOOT_TS
from app.extensions import db
from app.services.gamification import _last_rollover_check, award_xp, get_level, get_title, lb_sync_user, log_activity, run_weekly_rollover


def generate_csp_nonce():
    """Her istek için tek kullanımlık CSP nonce'u üret. Şablonlardaki satır-içi
    <script nonce="{{ csp_nonce }}"> blokları bu değerle imzalanır; başlıktaki
    nonce ile eşleşmeyen (örn. XSS ile enjekte edilen) script'ler çalışmaz."""
    g.csp_nonce = secrets.token_urlsafe(16)


def set_csp_header(response):
    """Content-Security-Policy başlığını uygula (nginx'ten buraya taşındı —
    nonce per-request üretildiği için statik nginx config'de yazılamaz).

    script-src: 'unsafe-inline' KALDIRILDI — satır-içi script blokları artık
    nonce ister. script-src-attr 'unsafe-inline': şablonlardaki onclick=...
    nitelik-handler'ları için gerekli (nonce nitelikler için çalışmaz);
    asıl enjeksiyon vektörü olan <script> blokları yine de nonce'a tabidir.
    img-src: 'https:' (tüm hostlar) yerine yalnızca S3 (pre-signed URL'ler,
    *.amazonaws.com) + data: (base64 profil/önizleme görselleri).
    Google Analytics (gtag.js, index.html): script/img/connect kaynakları
    Google'ın resmî CSP rehberindeki host setiyle açıldı."""
    nonce = getattr(g, "csp_nonce", "")
    response.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        f"script-src 'self' 'nonce-{nonce}' https://cdn.jsdelivr.net "
        "https://*.googletagmanager.com; "
        "script-src-attr 'unsafe-inline'; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        "font-src 'self' https://fonts.gstatic.com data:; "
        "img-src 'self' data: https://*.amazonaws.com "
        "https://*.google-analytics.com https://*.googletagmanager.com; "
        "connect-src 'self' https://*.google-analytics.com "
        "https://*.analytics.google.com https://*.googletagmanager.com; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self'; "
        "object-src 'none'"
    )
    return response


def inject_csp_nonce():
    return {"csp_nonce": getattr(g, "csp_nonce", "")}


def _csrf_protect():
    """Reject state-changing requests that don't originate from our own site.

    Cookie-authenticated POST/PUT/PATCH/DELETE requests are the CSRF attack
    surface. We verify the Origin (or Referer) header matches our host; a
    cross-site forgery cannot forge these headers. Same-origin fetch() calls
    send them automatically, so the frontend needs no changes.
    """
    if request.method not in ("POST", "PUT", "PATCH", "DELETE"):
        return
    from urllib.parse import urlparse
    expected_host = request.host.split(":")[0]
    for header in ("Origin", "Referer"):
        value = request.headers.get(header)
        if value:
            if urlparse(value).hostname == expected_host:
                return
            abort(403, description="CSRF doğrulaması başarısız.")
    # No Origin and no Referer on a state-changing request → treat as forged.
    abort(403, description="CSRF doğrulaması başarısız.")


def ratelimit_exceeded(e):
    return jsonify({"error": "Çok fazla deneme yaptınız. Lütfen biraz sonra tekrar deneyin."}), 429


def maybe_weekly_rollover():
    now = datetime.utcnow()
    last = _last_rollover_check[0]
    if last is not None and (now - last).total_seconds() < 300:
        return
    _last_rollover_check[0] = now
    try:
        run_weekly_rollover(now)
    except Exception:
        db.session.rollback()


def update_streak():
    if current_user.is_authenticated:
        today = date.today()
        if current_user.last_login != today:
            if current_user.last_login == today - timedelta(days=1):
                current_user.streak_count = (current_user.streak_count or 0) + 1
            else:
                current_user.streak_count = 1
            current_user.last_login = today
            streak = current_user.streak_count
            if streak in (7, 14, 30, 60, 100):
                log_activity(current_user.id, "streak_milestone",
                             f"{streak} günlük seri yakalanadı!")
                award_xp(current_user.id, streak * 2)
            db.session.commit()
            lb_sync_user(current_user)  # streak tiebreak'i değişti → Redis'i güncelle


def inject_rank():
    base = {"_v": _BOOT_TS}
    if current_user.is_authenticated:
        xp = current_user.rank_points or 0
        level = get_level(xp)
        title = get_title(level)
        xp_in_level = xp % 500
        return {**base,
            "rank_points": xp, "rank_title": title,
            "user_xp": xp, "user_level": level, "user_title": title,
            "xp_in_level": xp_in_level, "xp_for_next": 500,
        }
    return {**base,
        "rank_points": 0, "rank_title": "Fitness Yolcusu",
        "user_xp": 0, "user_level": 1, "user_title": "Fitness Yolcusu",
        "xp_in_level": 0, "xp_for_next": 500,
    }


def not_found(e):
    return render_template("404.html"), 404


def server_error(e):
    return "Internal Server Error", 500



def register_hooks(app):
    app.before_request(generate_csp_nonce)
    app.before_request(_csrf_protect)
    app.before_request(maybe_weekly_rollover)
    app.before_request(update_streak)
    app.context_processor(inject_csp_nonce)
    app.context_processor(inject_rank)
    app.after_request(set_csp_header)
    app.errorhandler(429)(ratelimit_exceeded)
    app.errorhandler(404)(not_found)
    app.errorhandler(500)(server_error)
