# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import logging
import secrets
from datetime import datetime
from flask_login import UserMixin
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import JSONB

from app.extensions import db, login_manager
from app.timeutil import app_today

_logger = logging.getLogger(__name__)


@login_manager.user_loader
def load_user(user_id):
    return db.session.get(User, int(user_id))


class User(UserMixin, db.Model):
    id            = db.Column(db.Integer, primary_key=True)
    username      = db.Column(db.String(80), unique=True, nullable=False)
    email         = db.Column(db.String(120), unique=True, nullable=False)
    # Cognito (cognito_sub) is the sole auth identity. The nullable legacy column
    # remains for schema/migration compatibility and is never read at runtime.
    password_hash = db.Column(db.String(200), nullable=True)
    created_at    = db.Column(db.DateTime, default=datetime.utcnow)

    # Arayüz/koç dili tercihi: 'tr' | 'en'. Kayıt sırasında (kayıt-öncesi TR/EN
    # seçimi) yazılır, ayarlardan değiştirilebilir. Varsayılan 'tr' → mevcut
    # kullanıcılar Türkçe kalır. Locale çözümü app/i18n.resolve_locale'da.
    language      = db.Column(db.String(5), default="tr", server_default="tr")

    # Profil bilgileri
    weight           = db.Column(db.Float)
    height           = db.Column(db.Float)
    age              = db.Column(db.Integer)
    gender           = db.Column(db.String(10))
    goal             = db.Column(db.String(50))
    fitness_level    = db.Column(db.String(20))
    current_activity = db.Column(db.String(20))
    profile_complete = db.Column(db.Boolean, default=False)

    profile_picture  = db.Column(db.Text, nullable=True)
    # S3'e taşınan avatarın nesne anahtarı. Doluysa avatar S3'ten (pre-signed URL)
    # gösterilir ve profile_picture (base64) temizlenir — böylece ~245 KB base64
    # her HTML yanıtına gömülmez. Boşsa eski base64 davranışına düşülür.
    profile_picture_key = db.Column(db.String(300), nullable=True)
    full_name        = db.Column(db.String(150), nullable=True)
    target_weight    = db.Column(db.Float, nullable=True)
    goal_type        = db.Column(db.String(10), nullable=True)
    streak_count     = db.Column(db.Integer, default=0, server_default='0')
    rank_points      = db.Column(db.Integer, default=0, server_default='0')
    weekly_xp        = db.Column(db.Integer, default=0, server_default='0')
    last_reward_week = db.Column(db.String(10), nullable=True)  # ISO week of last seen reward popup, e.g. "2026-W22"
    last_login       = db.Column(db.Date, nullable=True)

    # Amazon Cognito (e-posta ile giriş) kimlik bağı. Cognito 'sub' claim'i —
    # e-posta değişse bile aynı yerel hesaba sabit kalır. Yalnızca Cognito ile
    # giren kullanıcılarda doludur; klasik kullanıcı adı/şifre hesaplarında NULL.
    # Benzersizlik, kolon-içi `unique=True` (adsız constraint) yerine ADLI bir
    # unique index ile (bkz. __table_args__) — migration zinciri bu indeksleri
    # `uq_user_*` adıyla kurdu; model de aynı adı kullanınca autogenerate drift'i
    # kapanır (I-M1: index-vs-constraint uyuşmazlığı).
    cognito_sub      = db.Column(db.String(64), nullable=True)

    # Davet/referral döngüsü: her kullanıcının paylaşılabilir tek davet kodu olur;
    # referred_by_id, bu kullanıcıyı getiren davetçiyi işaret eder (çift taraflı ödül).
    referral_code    = db.Column(db.String(16), nullable=True)
    # Davetçi silinirse davet edilen kullanıcı SİLİNMEMELİ — bağ kopar (SET NULL).
    referred_by_id   = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="SET NULL"), nullable=True)

    # Para kazanma: freemium hattı. is_premium şu an yalnızca instrümantasyon için
    # tutulur (billing yok); GET /premium upgrade-intent GA olayı ile takip edilir.
    is_premium       = db.Column(db.Boolean, default=False, server_default='false')
    premium_since    = db.Column(db.DateTime, nullable=True)

    # Esnek kullanıcı metadata deposu (anahtar/değer): tıbbi durumlar/sakatlıklar
    # ("injuries"), tercihler ("equipment_available", "fitness_goals") AI koç
    # `manage_user_memory` aracı üzerinden buraya yazılıp okunur. Prod (RDS)
    # PostgreSQL'de JSONB, lokal SQLite'ta JSON. Kod None'ı {} olarak ele alır.
    # NOT: kolon adı `user_metadata` — `metadata` declarative sınıflarda ayrılmış.
    user_metadata    = db.Column(JSONB().with_variant(db.JSON(), "sqlite"), nullable=True)

    referrer = db.relationship("User", remote_side=[id], backref="referrals")

    # cognito_sub / referral_code benzersizliği ADLI unique index olarak — migration
    # zinciri bu indeksleri tam bu adlarla kurdu (uq_user_cognito_sub /
    # uq_user_referral_code). Kolon-içi `unique=True` adsız constraint üretip
    # autogenerate'i (schema-drift guard) sürekli kırmızı bırakıyordu (I-M1).
    __table_args__ = (
        db.Index("uq_user_cognito_sub", "cognito_sub", unique=True),
        db.Index("uq_user_referral_code", "referral_code", unique=True),
    )

    @property
    def avatar_src(self):
        """Gösterim için avatar kaynağı. S3 anahtarı varsa kısa ömürlü pre-signed
        URL üret; yoksa eski base64 data-URL'i (veya None) döndür. Hata/kapalı S3'te
        anahtar varsa None döner → şablon baş harf rozetine düşer. Asla istisna atmaz
        (liste sayfaları çok sayıda avatar render eder)."""
        if self.profile_picture_key:
            import s3_helper
            if s3_helper.is_enabled():
                url = s3_helper.generate_presigned_url(self.profile_picture_key, expires_in=21600)
                if url:
                    return url
            # Anahtar var ama URL üretilemedi (S3 kapalı/erişilemiyor): sessizce
            # baş-harf rozetine düşmeden önce logla ki kesinti tespit edilebilsin (3.6).
            # Modül-seviyesi logger: app-context'siz çağrılarda da güvenli (bu property
            # asla istisna atmamalı — liste sayfaları çok sayıda avatar render eder).
            _logger.warning(
                "[S3] Avatar pre-signed URL üretilemedi (key=%s, enabled=%s) — rozete düşülüyor",
                self.profile_picture_key, s3_helper.is_enabled())
            return None
        return self.profile_picture

    def __repr__(self):
        return f"<User {self.username}>"


class UserSession(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # Her coach/tracking isteğinde user_id'ye göre filtreleniyor → index zorunlu
    # (3.2). İlişki + CASCADE ile kullanıcı silindiğinde oturumlar da temizlenir.
    user_id = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"),
                        nullable=True, index=True)
    name = db.Column(db.String(100))
    age = db.Column(db.Integer)
    gender = db.Column(db.String(10))
    weight = db.Column(db.Float)
    height = db.Column(db.Float)
    goal = db.Column(db.String(50))
    fitness_level = db.Column(db.String(20))
    current_activity = db.Column(db.String(20))
    bmr = db.Column(db.Float)
    tdee = db.Column(db.Float)
    target_calories = db.Column(db.Float)
    training_plan = db.Column(db.Text)
    nutrition_plan = db.Column(db.Text)
    coach_reply = db.Column(db.Text)
    created_at = db.Column(db.DateTime , default= datetime.utcnow)

    # passive_deletes: silmeyi DB CASCADE'ine bırak (ORM tek tek NULL'lamasın).
    user = db.relationship("User", backref=db.backref("sessions", passive_deletes=True))

    def __repr__(self):
        return f"<UserSession {self.name} - {self.created_at}>"


class CognitoSession(db.Model):
    """Bir Flask-Login oturumuna bağlı Cognito token'ları (sunucu tarafı, şifreli).
    session_id çerezde taşınır; access/refresh token'lar Fernet ile şifreli saklanır.
    Bir giriş = bir satır → eşzamanlı oturumlar bağımsız yaşar."""
    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(db.String(64), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"),
                        nullable=False, index=True)
    cognito_username = db.Column(db.String(80), nullable=False)
    access_token = db.Column(db.Text, nullable=False)    # Fernet ile şifreli
    refresh_token = db.Column(db.Text, nullable=False)   # Fernet ile şifreli
    access_token_exp = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    last_used_at = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.Index("uq_cognito_session_session_id", "session_id", unique=True),
    )


class MobileAuthSession(db.Model):
    '''One opaque mobile credential family for one device login.'''

    id = db.Column(db.Integer, primary_key=True)
    family_id = db.Column(db.String(64), nullable=False)
    user_id = db.Column(
        db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    cognito_username = db.Column(db.String(80), nullable=False)
    cognito_sub = db.Column(db.String(64), nullable=False)
    cognito_access_token = db.Column(db.Text, nullable=True)
    cognito_refresh_token = db.Column(db.Text, nullable=True)
    cognito_access_expires_at = db.Column(db.DateTime, nullable=True)
    absolute_expires_at = db.Column(db.DateTime, nullable=False)
    revoked_at = db.Column(db.DateTime, nullable=True)
    revoked_reason = db.Column(db.String(40), nullable=True)
    version = db.Column(
        db.Integer, nullable=False, default=1, server_default='1')
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    last_used_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow,
        onupdate=datetime.utcnow)

    __table_args__ = (
        db.Index('uq_mobile_auth_session_family_id', 'family_id', unique=True),
        db.Index('ix_mobile_auth_session_user_id', 'user_id'),
        db.Index(
            'ix_mobile_auth_session_expiry_revoked',
            'absolute_expires_at', 'revoked_at'),
        db.CheckConstraint(
            'version >= 1', name='ck_mobile_auth_session_version'),
    )

    user = db.relationship(
        'User', backref=db.backref('mobile_auth_sessions', passive_deletes=True))


class MobileAccessCredential(db.Model):
    '''Hash-only opaque mobile access credential.'''

    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(
        db.Integer,
        db.ForeignKey('mobile_auth_session.id', ondelete='CASCADE'),
        nullable=False)
    credential_hash = db.Column(db.String(64), nullable=False)
    generation = db.Column(db.Integer, nullable=False)
    issued_at = db.Column(db.DateTime, nullable=False)
    expires_at = db.Column(db.DateTime, nullable=False)
    revoked_at = db.Column(db.DateTime, nullable=True)

    __table_args__ = (
        db.Index(
            'uq_mobile_access_credential_hash', 'credential_hash', unique=True),
        db.UniqueConstraint(
            'session_id', 'generation',
            name='uq_mobile_access_session_generation'),
        db.Index(
            'ix_mobile_access_expiry_revoked', 'expires_at', 'revoked_at'),
        db.CheckConstraint(
            'generation >= 0', name='ck_mobile_access_generation'),
    )

    session = db.relationship(
        'MobileAuthSession',
        backref=db.backref('access_credentials', passive_deletes=True))


class MobileRefreshCredential(db.Model):
    '''Hash-only rotating refresh credential and idempotent replay context.'''

    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(
        db.Integer,
        db.ForeignKey('mobile_auth_session.id', ondelete='CASCADE'),
        nullable=False)
    credential_hash = db.Column(db.String(64), nullable=False)
    generation = db.Column(db.Integer, nullable=False)
    parent_id = db.Column(
        db.Integer,
        db.ForeignKey('mobile_refresh_credential.id', ondelete='CASCADE'),
        nullable=True)
    issued_at = db.Column(db.DateTime, nullable=False)
    expires_at = db.Column(db.DateTime, nullable=False)
    consumed_at = db.Column(db.DateTime, nullable=True)
    grace_expires_at = db.Column(db.DateTime, nullable=True)
    replacement_key_version = db.Column(db.String(32), nullable=True)
    replacement_generation = db.Column(db.Integer, nullable=True)
    replacement_access_id = db.Column(
        db.Integer,
        db.ForeignKey('mobile_access_credential.id', ondelete='SET NULL'),
        nullable=True)
    replacement_refresh_id = db.Column(
        db.Integer,
        db.ForeignKey('mobile_refresh_credential.id', ondelete='SET NULL'),
        nullable=True)
    replacement_issued_at = db.Column(db.DateTime, nullable=True)
    replacement_access_expires_at = db.Column(db.DateTime, nullable=True)
    replacement_refresh_expires_at = db.Column(db.DateTime, nullable=True)
    revoked_at = db.Column(db.DateTime, nullable=True)

    __table_args__ = (
        db.Index(
            'uq_mobile_refresh_credential_hash', 'credential_hash', unique=True),
        db.UniqueConstraint(
            'session_id', 'generation',
            name='uq_mobile_refresh_session_generation'),
        db.UniqueConstraint('parent_id', name='uq_mobile_refresh_parent'),
        db.Index(
            'ix_mobile_refresh_expiry_revoked', 'expires_at', 'revoked_at'),
        db.CheckConstraint(
            'generation >= 0', name='ck_mobile_refresh_generation'),
        db.CheckConstraint(
            'replacement_generation IS NULL OR replacement_generation >= 0',
            name='ck_mobile_refresh_replacement_generation'),
    )

    session = db.relationship(
        'MobileAuthSession',
        backref=db.backref('refresh_credentials', passive_deletes=True))


class WeeklyLog(db.Model):
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    weight     = db.Column(db.Float, nullable=False)
    note       = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<WeeklyLog {self.user_id} - {self.weight}kg - {self.created_at}>"


class WeeklyCheckIn(db.Model):
    id                = db.Column(db.Integer, primary_key=True)
    user_id           = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    weight            = db.Column(db.Float, nullable=False)
    yogunluk          = db.Column(db.Integer)      # 1-5 arası
    fatigue           = db.Column(db.Integer)       # 1-5 arası
    progressive_overload = db.Column(db.String(20)) # "evet", "hayir", "kismen"
    uyku_kalitesi     = db.Column(db.Integer)       # 1-5 arası
    beslenme_uyumu    = db.Column(db.Integer)       # 1-5 arası
    note              = db.Column(db.Text)
    coach_feedback    = db.Column(db.Text)
    created_at        = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<WeeklyCheckIn {self.user_id} - {self.created_at}>"


class NutritionPlan(db.Model):
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    plan_data  = db.Column(db.Text, nullable=False)  # JSON olarak sakla
    score      = db.Column(db.Float)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<NutritionPlan {self.user_id} - {self.created_at}>"


class TrainingPlan(db.Model):
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    plan_data  = db.Column(db.Text, nullable=False)
    score      = db.Column(db.Float)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<TrainingPlan {self.user_id} - {self.created_at}>"


class MealLog(db.Model):
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False)
    ogun       = db.Column(db.String(100), nullable=False)
    yemekler   = db.Column(db.Text, nullable=False)
    kalori     = db.Column(db.Float)
    protein    = db.Column(db.Float)
    karb       = db.Column(db.Float)
    yag        = db.Column(db.Float)
    # Kanonik gün anahtarı (Istanbul ISO 'YYYY-MM-DD'). NOT NULL + default: NULL
    # tarih satırları per-gün sorgularından SESSİZCE kaçardı. Tüm yazma yolları
    # zaten tarih veriyor; default yalnızca güvenlik ağı (app/timeutil tek kaynak).
    tarih      = db.Column(db.String(10), nullable=False, default=lambda: app_today().isoformat())
    source     = db.Column(db.String(20), default="manual")
    idempotency_key = db.Column(db.String(64), nullable=True)
    idempotency_fingerprint = db.Column(db.String(64), nullable=True)
    photo_key  = db.Column(db.String(300), nullable=True)  # S3 nesne anahtarı (opsiyonel)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # DB-seviyesi makro sağlık-kontrolü (3.8): negatif makro ASLA geçerli değildir;
    # üst tavan ise yalnızca açıkça bozuk/taşma (overflow, LLM çöpü, ör. 1e9) değerleri
    # yakalamak için CÖMERT seçildi — MealLog satırı tek bir öğünün/çok-öğeli önerinin
    # TOPLAMI olabildiğinden (app/blueprints/social.py toplamı sanitizer'dan geçmez),
    # per-serving sanitizer tavanı (3000) burada meşru toplamları reddederdi. NULL'lar
    # SQL CHECK semantiğiyle geçer (kolonlar nullable).
    __table_args__ = (
        db.CheckConstraint(
            "(kalori IS NULL OR (kalori >= 0 AND kalori <= 100000)) AND "
            "(protein IS NULL OR (protein >= 0 AND protein <= 50000)) AND "
            "(karb IS NULL OR (karb >= 0 AND karb <= 50000)) AND "
            "(yag IS NULL OR (yag >= 0 AND yag <= 50000))",
            name="ck_meal_log_macro_bounds"),
        # DB1: her beslenme sayfası user_id + tarih ile sorguluyor — kanonik en çok
        # yazılan defter; (user_id, tarih) kompozit indeksi user_id-only sorguları da
        # (leftmost prefix) karşılar.
        db.Index("ix_meal_log_user_id_tarih", "user_id", "tarih"),
        db.UniqueConstraint("user_id", "idempotency_key",
                            name="uq_meal_log_user_idempotency"),
    )

    def __repr__(self):
        return f"<MealLog {self.user_id} - {self.ogun} - {self.created_at}>"


class BarcodeFoodCache(db.Model):
    """Normalized packaged-food cache keyed by barcode.

    FatSecret remains the source of truth on a miss, but UI/business logic should
    consume this internal payload shape so FatSecret response quirks do not leak
    into the rest of the app.
    """
    id         = db.Column(db.Integer, primary_key=True)
    barcode    = db.Column(db.String(32), nullable=False, unique=True, index=True)
    food_id    = db.Column(db.String(50), nullable=True, index=True)
    food_name  = db.Column(db.String(200), nullable=False)
    brand      = db.Column(db.String(120), nullable=True)
    payload    = db.Column(JSONB().with_variant(db.JSON(), "sqlite"), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow,
                           onupdate=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f"<BarcodeFoodCache {self.barcode} - {self.food_name}>"


class PendingAction(db.Model):
    """Onay bekleyen ('staged') koç aksiyonu.

    Kullanıcı bir yemeğin makrolarını sorduğunda veya yediğini söylediğinde,
    veri DOĞRUDAN kalıcı log'a yazılmaz; önce buraya geçici olarak konur. Böylece
    sadece meraktan sorulan ("kaç kalori?") şeyler yanlışlıkla loglanmaz.
    Kullanıcı onayladığında payload kalıcı kayda (MealLog / WorkoutLog)
    taşınır ve buradaki satır silinir → durum geçişi: staged → committed.

    payload (JSON): log_meal için {food_name, calories, protein, carbs, fat,
    serving_size}; log_workout için {exercise_name, sets, reps, weight_kg, volume}.
    """
    id          = db.Column(db.Integer, primary_key=True)
    user_id     = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    action_type = db.Column(db.String(20), nullable=False)  # 'log_meal' | 'log_workout'
    payload     = db.Column(db.JSON, nullable=False)
    created_at  = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    user = db.relationship("User", backref=db.backref("pending_actions", passive_deletes=True))

    def __repr__(self):
        return f"<PendingAction {self.user_id} - {self.action_type} - {self.created_at}>"


class CoachConversation(db.Model):
    """AI koç kalıcı konuşma oturumu (Sprint 4 WS1).

    Kullanıcı başına EN FAZLA bir aktif konuşma (archived_at IS NULL) — kod
    seviyesinde memory_manager.get_or_create_active_conversation ile korunur
    (kısmi unique indeks SQLite'a taşınamıyor). Reset arşivler, SİLMEZ: eski
    mesajlar güvenle saklı kalır. `summary` eski turların LLM özetidir ve
    bağlam penceresine not olarak girer; `summarized_upto_id` özetin kapsadığı
    son CoachMessage.id'dir — özetleme tetikleyicisi 'özetlenmemiş kuyruk'
    boyutunu buradan hesaplar (pruning mesaj silmeden pencere-dışı bırakır)."""
    id             = db.Column(db.Integer, primary_key=True)
    user_id        = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    started_at     = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    archived_at    = db.Column(db.DateTime, nullable=True, index=True)
    summary        = db.Column(db.Text, nullable=True)
    summary_tokens = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    summarized_upto_id = db.Column(db.Integer, nullable=False, default=0, server_default="0")

    user = db.relationship("User", backref=db.backref("coach_conversations", passive_deletes=True))
    messages = db.relationship("CoachMessage", backref="conversation",
                               passive_deletes=True, lazy="dynamic")

    def __repr__(self):
        return f"<CoachConversation {self.id} user={self.user_id} archived={self.archived_at}>"


class CoachMessage(db.Model):
    """AI koç konuşmasının tek turu (user | assistant).

    token_estimate kaba (len//4) tahmindir; prompt/completion_tokens sağlayıcı
    yanıtındaki gerçek `usage` değerleridir (varsa — WS6 gözlemlenebilirlik).
    `interrupted` stream yarıda kesildiğinde işaretlenir (WS2)."""
    id              = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey("coach_conversation.id", ondelete="CASCADE"), nullable=False, index=True)
    role            = db.Column(db.String(12), nullable=False)  # 'user' | 'assistant'
    content         = db.Column(db.Text, nullable=False)
    token_estimate  = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    prompt_tokens     = db.Column(db.Integer, nullable=True)
    completion_tokens = db.Column(db.Integer, nullable=True)
    interrupted     = db.Column(db.Boolean, nullable=False, default=False, server_default="false")
    created_at      = db.Column(db.DateTime, default=datetime.utcnow, nullable=False, index=True)

    def __repr__(self):
        return f"<CoachMessage {self.id} conv={self.conversation_id} {self.role}>"


class PumpCheck(db.Model):
    """Antrenman tamamlama doğrulaması ('Pump Check'). Yüklenen ortam fotoğrafı
    S3'e konur; burada yalnızca nesne anahtarı ve doğrulama sonucu saklanır."""
    id            = db.Column(db.Integer, primary_key=True)
    user_id       = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    image_key     = db.Column(db.String(300), nullable=True)  # S3 nesne anahtarı
    location_type = db.Column(db.String(50))
    description   = db.Column(db.String(200))
    workout_score = db.Column(db.Float, nullable=True)
    visibility    = db.Column(db.String(20), nullable=False, default="private", server_default="private", index=True)
    shared_friend_ids = db.Column(JSONB().with_variant(db.JSON(), "sqlite"), nullable=False, default=list)
    likes_count   = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    comments_count = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    reposts_count = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    valid         = db.Column(db.Boolean, default=True)
    fallback      = db.Column(db.Boolean, default=False)  # AI atlandıysa (fail-open)
    # Sprint 10 PR1 canonical mobile truth. Nullable is deliberate: historical
    # web rows have no authoritative capture/region/structured-analysis data.
    captured_at   = db.Column(db.DateTime, nullable=True)
    body_region   = db.Column(db.String(20), nullable=True)
    analysis_status = db.Column(db.String(20), nullable=True)
    analysis      = db.Column(JSONB().with_variant(db.JSON(), "sqlite"), nullable=True)
    analysis_version = db.Column(db.String(40), nullable=True)
    idempotency_key = db.Column(db.String(64), nullable=True)
    idempotency_fingerprint = db.Column(db.String(64), nullable=True)
    # Günlük idempotency anahtarı (Istanbul ISO 'YYYY-MM-DD'). Aşağıdaki UNIQUE
    # ile birlikte, eşzamanlı iki "antrenmanı tamamla" isteğinin TOCTOU yarışında
    # ikinci kez PumpCheck/XP yazmasını DB seviyesinde engeller (created_at-bazlı
    # uygulama kontrolü tek başına yarışa açıktı → çift XP).
    date_key      = db.Column(db.String(10), nullable=True, index=True)
    created_at    = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint("user_id", "date_key", name="uq_pump_check_day"),
        db.UniqueConstraint(
            "user_id", "idempotency_key",
            name="uq_pump_check_user_idempotency",
        ),
        # Feed V2 birincil kaynak sorgusu: user_id IN (arkadaslar) + ORDER BY
        # created_at DESC. Tek-kolon user_id indeksi siralamayi karsilamiyordu.
        db.Index("ix_pump_check_user_created", "user_id", "created_at"),
    )

    user = db.relationship("User", backref=db.backref("pump_checks", passive_deletes=True))

    def __repr__(self):
        return f"<PumpCheck {self.user_id} - {self.created_at}>"


class PumpCheckLike(db.Model):
    id            = db.Column(db.Integer, primary_key=True)
    pump_check_id = db.Column(db.Integer, db.ForeignKey("pump_check.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id       = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    created_at    = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    __table_args__ = (
        db.UniqueConstraint("pump_check_id", "user_id", name="uq_pump_check_like_user"),
    )

    pump_check = db.relationship("PumpCheck", backref=db.backref("likes", passive_deletes=True))
    user = db.relationship("User", backref=db.backref("pump_check_likes", passive_deletes=True))


class PumpCheckComment(db.Model):
    id            = db.Column(db.Integer, primary_key=True)
    pump_check_id = db.Column(db.Integer, db.ForeignKey("pump_check.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id       = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    body          = db.Column(db.String(500), nullable=False)
    created_at    = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    pump_check = db.relationship("PumpCheck", backref=db.backref("comments", passive_deletes=True))
    user = db.relationship("User", backref=db.backref("pump_check_comments", passive_deletes=True))


class FeedItem(db.Model):
    # Feed V2 omurgası (Sprint 5 PR2): SADECE yeni içerik türleri (repost/quote).
    # ref_id polimorfik tohum — FK YOK (ref_type ayırır); askıda kalan ref →
    # "içerik yok" stub. PumpCheck/Activity feed'e sorgu-zamanında katılır.
    id            = db.Column(db.Integer, primary_key=True)
    user_id       = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    item_type     = db.Column(db.String(20), nullable=False, index=True)   # 'repost' | 'quote'
    ref_type      = db.Column(db.String(20), nullable=False, default="pump_check", server_default="pump_check")
    ref_id        = db.Column(db.Integer, nullable=False, index=True)       # FK YOK — polimorfik
    body          = db.Column(db.String(500), nullable=True)                # quote metni
    likes_count   = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    comments_count = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    created_at    = db.Column(db.DateTime, default=datetime.utcnow, nullable=False, index=True)

    __table_args__ = (
        db.UniqueConstraint("user_id", "item_type", "ref_type", "ref_id", name="uq_feed_item_user_ref"),
    )

    user = db.relationship("User", backref=db.backref("feed_items", passive_deletes=True))


class FeedItemLike(db.Model):
    id           = db.Column(db.Integer, primary_key=True)
    feed_item_id = db.Column(db.Integer, db.ForeignKey("feed_item.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id      = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    __table_args__ = (
        db.UniqueConstraint("feed_item_id", "user_id", name="uq_feed_item_like_user"),
    )

    feed_item = db.relationship("FeedItem", backref=db.backref("likes", passive_deletes=True))
    user = db.relationship("User", backref=db.backref("feed_item_likes", passive_deletes=True))


class FeedItemComment(db.Model):
    id           = db.Column(db.Integer, primary_key=True)
    feed_item_id = db.Column(db.Integer, db.ForeignKey("feed_item.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id      = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    body         = db.Column(db.String(500), nullable=False)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    feed_item = db.relationship("FeedItem", backref=db.backref("comments", passive_deletes=True))
    user = db.relationship("User", backref=db.backref("feed_item_comments", passive_deletes=True))


class FeedHide(db.Model):
    # Görüntüleyen-başı gizleme (polimorfik): pump_check | feed_item | activity.
    id          = db.Column(db.Integer, primary_key=True)
    user_id     = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    target_type = db.Column(db.String(20), nullable=False)
    target_id   = db.Column(db.Integer, nullable=False)
    created_at  = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint("user_id", "target_type", "target_id", name="uq_feed_hide_target"),
    )

    user = db.relationship("User", backref=db.backref("feed_hides", passive_deletes=True))


class FeedReport(db.Model):
    id          = db.Column(db.Integer, primary_key=True)
    user_id     = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)   # şikayetçi
    target_type = db.Column(db.String(20), nullable=False)
    target_id   = db.Column(db.Integer, nullable=False)
    reason      = db.Column(db.String(30), nullable=False)   # 'spam' | 'inappropriate' | 'other'
    note        = db.Column(db.String(300), nullable=True)
    status      = db.Column(db.String(15), nullable=False, default="open", server_default="open")
    created_at  = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint("user_id", "target_type", "target_id", name="uq_feed_report_target"),
    )

    user = db.relationship("User", backref=db.backref("feed_reports", passive_deletes=True))


class Friendship(db.Model):
    id          = db.Column(db.Integer, primary_key=True)
    sender_id   = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    receiver_id = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    status      = db.Column(db.String(10), default="pending")
    created_at  = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint("sender_id", "receiver_id", name="uq_friendship"),
    )

    sender   = db.relationship("User", foreign_keys=[sender_id], backref=db.backref("sent_requests", passive_deletes=True))
    receiver = db.relationship("User", foreign_keys=[receiver_id], backref=db.backref("received_requests", passive_deletes=True))


class Message(db.Model):
    id           = db.Column(db.Integer, primary_key=True)
    sender_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    receiver_id  = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    body         = db.Column(db.Text, nullable=False)
    timestamp    = db.Column(db.DateTime, default=datetime.utcnow)
    is_read      = db.Column(db.Boolean, default=False)
    message_type = db.Column(db.String(50), default="text")

    sender   = db.relationship("User", foreign_keys=[sender_id], backref=db.backref("sent_messages", passive_deletes=True))
    receiver = db.relationship("User", foreign_keys=[receiver_id], backref=db.backref("received_messages", passive_deletes=True))


class Activity(db.Model):
    id            = db.Column(db.Integer, primary_key=True)
    user_id       = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    activity_type = db.Column(db.String(30), nullable=False)
    content       = db.Column(db.String(300), nullable=False)
    timestamp     = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    # Feed V2 kilometre-tasi kaynagi: user_id IN (arkadaslar) + ORDER BY
    # timestamp DESC. Activity en yuksek-hacimli tablo; ayri user_id/timestamp
    # indeksleri IN + siralamayi karsilamiyordu (audit HIGH-1).
    __table_args__ = (
        db.Index("ix_activity_user_ts", "user_id", "timestamp"),
    )

    user = db.relationship("User", backref=db.backref("activities", passive_deletes=True))


class Supplement(db.Model):
    id                   = db.Column(db.Integer, primary_key=True)
    user_id              = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    product_name         = db.Column(db.String(150), nullable=False)
    brand                = db.Column(db.String(100), nullable=False)
    category             = db.Column(db.String(30), nullable=False, default="Other")
    status               = db.Column(db.String(15), nullable=False, default="Active")
    rating_effect        = db.Column(db.Integer, nullable=True)
    rating_taste         = db.Column(db.Integer, nullable=True)
    rating_digestion     = db.Column(db.Integer, nullable=True)
    rating_price         = db.Column(db.Integer, nullable=True)
    review_text          = db.Column(db.Text, nullable=True)
    price_paid           = db.Column(db.Float, nullable=True)
    is_public            = db.Column(db.Boolean, default=True)
    created_at           = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship("User", backref=db.backref("supplements", passive_deletes=True))


class DailyQuest(db.Model):
    id            = db.Column(db.Integer, primary_key=True)
    title         = db.Column(db.String(120), nullable=False)
    description   = db.Column(db.Text)
    points_reward = db.Column(db.Integer, nullable=False, default=10)
    quest_type    = db.Column(db.String(50), nullable=False)
    is_active     = db.Column(db.Boolean, default=True)


class UserQuestProgress(db.Model):
    id           = db.Column(db.Integer, primary_key=True)
    user_id      = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False)
    quest_id     = db.Column(db.Integer, db.ForeignKey("daily_quest.id", ondelete="CASCADE"), nullable=False)
    completed_at = db.Column(db.DateTime, default=datetime.utcnow)
    date_key     = db.Column(db.String(10), nullable=False, default=lambda: app_today().isoformat())
    is_claimed   = db.Column(db.Boolean, default=False)

    __table_args__ = (
        db.UniqueConstraint("user_id", "quest_id", "date_key", name="uq_user_quest_day"),
    )

    user  = db.relationship("User", backref=db.backref("quest_progress", passive_deletes=True))
    quest = db.relationship("DailyQuest", backref="progress_entries")


class WeeklyWinner(db.Model):
    # Haftalık liderlik kazananları — kutlama pop-up'ını da besler.
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    week_key   = db.Column(db.String(10), nullable=False)   # biten ISO hafta, ör. "2026-W22"
    rank       = db.Column(db.Integer, nullable=False)       # 1, 2, 3
    xp_awarded = db.Column(db.Integer, nullable=False)       # 500 / 300 / 150
    notified   = db.Column(db.Boolean, default=False, server_default='false')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship("User", backref=db.backref("weekly_wins", passive_deletes=True))


class WeeklyResetLog(db.Model):
    # Haftalık rollover idempotency koruması — her hafta yalnızca bir kez işlenir.
    id           = db.Column(db.Integer, primary_key=True)
    week_key     = db.Column(db.String(10), unique=True, nullable=False)
    processed_at = db.Column(db.DateTime, default=datetime.utcnow)
    winner_count = db.Column(db.Integer, default=0)


class WaterLog(db.Model):
    # Günlük su (bardak) sayısı — kullanıcı + gün başına tek satır.
    # Cihazlar arası senkron için sunucuda tutulur.
    id       = db.Column(db.Integer, primary_key=True)
    user_id  = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    date_key = db.Column(db.String(10), nullable=False, default=lambda: app_today().isoformat())
    count    = db.Column(db.Integer, nullable=False, default=0)

    __table_args__ = (
        db.UniqueConstraint("user_id", "date_key", name="uq_user_water_day"),
    )


class WorkoutLog(db.Model):
    id            = db.Column(db.Integer, primary_key=True)
    user_id       = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    exercise_name = db.Column(db.String(120), nullable=False)
    sets          = db.Column(db.Integer, nullable=False)
    reps          = db.Column(db.Integer, nullable=False)
    weight_kg     = db.Column(db.Float, nullable=False, default=0)
    volume        = db.Column(db.Float, nullable=False, default=0)
    created_at    = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    user = db.relationship("User", backref=db.backref("workout_logs", passive_deletes=True))


# UI "antrenman tamamlandı" işaretçisi: complete_workout (UI) ve AI koç Pump Check
# aracı, nudge'lar/"bugün antrenman yapıldı mı" sinyali görsün diye sentetik bir
# WorkoutLog (volume=0) yazar. Bu işaretçi GERÇEK bir egzersiz DEĞİL; volume/sayım
# raporlamasında gerçek egzersizlerden ayırmak için TEK kaynak sabit (D4). Hem iki
# yazıcı hem de _today_workout_totals filtresi bu sabiti kullanır.
WORKOUT_COMPLETION_MARKER = "Antrenman tamamlandı (Pump Check)"


# ── Persisted workout-session lifecycle (Sprint 7 PR3) ───────────────────────
# The lifecycle status vocabulary. Small + explicit: ACTIVE is the only
# non-terminal state; COMPLETED/ABANDONED are terminal and immutable. "Stale" is
# a DERIVED condition of an ACTIVE session (see app/services/workout_session/),
# never a persisted status. No PAUSED — closing a browser is not a server-proven
# pause (docs/WORKOUT_STATE.md "Sprint 7 PR3").
WORKOUT_SESSION_ACTIVE = "active"
WORKOUT_SESSION_COMPLETED = "completed"
WORKOUT_SESSION_ABANDONED = "abandoned"
WORKOUT_SESSION_STATUSES = (
    WORKOUT_SESSION_ACTIVE,
    WORKOUT_SESSION_COMPLETED,
    WORKOUT_SESSION_ABANDONED,
)


def _new_session_public_id():
    """Opaque, non-guessable public id for API exposure (43 url-safe chars)."""
    return secrets.token_urlsafe(32)


class WorkoutSession(db.Model):
    """The canonical persisted workout-session (Sprint 7 PR3).

    The single server-owned source of truth for whether a workout session has
    actually started, remains active, can be safely resumed, or has terminated
    (completed via the PR2 completion authority / explicitly abandoned). A
    non-marker ``WorkoutLog`` row remains execution *evidence* only and never a
    resumable session; a client ``localStorage`` object is an untrusted cache —
    only a persisted ACTIVE row here is a resumable session.

    Identity/plan relationship is a MINIMAL SOFT reference (no TrainingPlan
    redesign, no stable plan-day ids — deferred): ``planned_training_plan_id`` is
    an intentionally un-FK'd soft pointer (so the row survives plan deletion and a
    missing plan is detectable), ``weekday_slot`` the normalized schedule slot,
    and ``plan_fingerprint`` a versioned digest of the intended workout's ordered
    exercise list (detects same-weekday regeneration). ``workout_date`` is the
    *start* local (Istanbul) date — CONTEXT, never silently rewritten at midnight;
    it is NOT the identity. The active-session invariant is (user_id, ACTIVE).
    """
    __tablename__ = "workout_session"

    id = db.Column(db.Integer, primary_key=True)
    # Opaque public identifier used in every API response/route — the sequential
    # PK is never exposed across users. No prior uuid/public_id convention in the
    # repo; PR3 introduces this one, scoped to session lifecycle.
    public_id = db.Column(db.String(64), nullable=False, default=_new_session_public_id)
    user_id = db.Column(
        db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    status = db.Column(
        db.String(12), nullable=False,
        default=WORKOUT_SESSION_ACTIVE, server_default=WORKOUT_SESSION_ACTIVE,
    )
    # User-local (Istanbul) start date — CONTEXT for stale/relationship checks.
    workout_date = db.Column(db.String(10), nullable=False)
    # Normalized weekday/schedule slot the session was started for (plan 'gun').
    weekday_slot = db.Column(db.String(20), nullable=True)
    # 'scheduled' | 'unscheduled' — did a matching planned workout exist at start?
    source = db.Column(db.String(20), nullable=False, default="scheduled")
    # SOFT reference to the TrainingPlan active at start. Intentionally NOT a hard
    # FK: the session must outlive plan deletion/regeneration so a now-missing plan
    # is detectable. NULL for unscheduled sessions or when no plan existed.
    planned_training_plan_id = db.Column(db.Integer, nullable=True)
    # Versioned digest ("v1:<sha256hex>") of the intended workout's canonical,
    # order-preserving exercise-name list. Server-computed, never client-supplied;
    # a version/algorithm mismatch is classified safely (indeterminate).
    plan_fingerprint = db.Column(db.String(80), nullable=True)
    started_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    # Heartbeat/observability timestamp only — never gates resume (no inactivity
    # threshold in PR3).
    last_activity_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime, nullable=True)
    abandoned_at = db.Column(db.DateTime, nullable=True)
    # Bounded reason code for a terminal transition (abandon / stale resolution).
    terminal_reason = db.Column(db.String(40), nullable=True)
    # Transition version — bumped on TERMINAL transitions for lost-update safety;
    # the heartbeat is a lock-free conditional update and does NOT use it.
    version = db.Column(db.Integer, nullable=False, default=1, server_default="1")
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow,
    )

    user = db.relationship(
        "User", backref=db.backref("workout_sessions", passive_deletes=True))

    __table_args__ = (
        # THE active-session uniqueness invariant: at most one non-terminal
        # (status='active') session per user, enforced at the DB level — the single
        # concurrency-safe atomic claim (mirrors uq_pump_check_day for completion).
        # A partial unique index on user_id WHERE active: terminal rows vacate the
        # slot so a new session may start. Both SQLite (>=3.8) and PostgreSQL
        # support partial indexes; the dialect-specific `where` is emitted for each.
        db.Index(
            "uq_workout_session_active_owner", "user_id", unique=True,
            sqlite_where=text("status = 'active'"),
            postgresql_where=text("status = 'active'"),
        ),
        db.Index("uq_workout_session_public_id", "public_id", unique=True),
        db.Index("ix_workout_session_user_status", "user_id", "status"),
        db.CheckConstraint(
            "status IN ('active', 'completed', 'abandoned')",
            name="ck_workout_session_status",
        ),
    )

    def __repr__(self):
        return f"<WorkoutSession {self.user_id} {self.status} {self.workout_date}>"


class DailyActivity(db.Model):
    id              = db.Column(db.Integer, primary_key=True)
    user_id         = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    steps           = db.Column(db.Integer, nullable=False, default=0)
    intensity       = db.Column(db.String(20), nullable=False, default="moderate")
    calories_burned = db.Column(db.Float, nullable=False, default=0)
    distance_km     = db.Column(db.Float, nullable=False, default=0)
    duration_min    = db.Column(db.Float, nullable=False, default=0)
    date_key        = db.Column(db.String(10), nullable=False, default=lambda: app_today().isoformat())
    created_at      = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    user = db.relationship("User", backref=db.backref("daily_activities", passive_deletes=True))

    # C4: "günde tam bir satır" invariantını DB de zorlasın diye kısıt intensity
    # İÇERMEZ — eski (user_id, date_key, intensity) kısıdı, farklı intensity'li
    # iki eşzamanlı isteğin ikisinin de sil-ekle yapıp İKİ satır bırakmasına izin
    # veriyordu (log_daily_activity'deki IntegrityError-upsert dalı hiç tetiklenmeden).
    __table_args__ = (
        db.UniqueConstraint("user_id", "date_key", name="uq_daily_activity"),
    )


class UserWearableConnection(db.Model):
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    provider   = db.Column(db.String(40), nullable=False)
    access_token_encrypted  = db.Column(db.Text, nullable=False)
    refresh_token_encrypted = db.Column(db.Text, nullable=True)
    token_expiry = db.Column(db.DateTime, nullable=True, index=True)
    scopes       = db.Column(db.Text, nullable=True)
    external_user_id = db.Column(db.String(120), nullable=True)
    status       = db.Column(db.String(20), nullable=False, default="connected", server_default="connected")
    last_sync_at = db.Column(db.DateTime, nullable=True)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at   = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = db.relationship("User", backref=db.backref("wearable_connections", passive_deletes=True))

    __table_args__ = (
        db.UniqueConstraint("user_id", "provider", name="uq_wearable_connection_user_provider"),
        db.Index("ix_wearable_connection_provider", "provider"),
    )


class WearableSleepLog(db.Model):
    id       = db.Column(db.Integer, primary_key=True)
    user_id  = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    provider = db.Column(db.String(40), nullable=False)
    source_id = db.Column(db.String(160), nullable=False)
    date_key  = db.Column(db.String(10), nullable=False, index=True)
    start_at  = db.Column(db.DateTime, nullable=True)
    end_at    = db.Column(db.DateTime, nullable=True)
    duration_min     = db.Column(db.Float, nullable=True)
    deep_sleep_min   = db.Column(db.Float, nullable=True)
    rem_sleep_min    = db.Column(db.Float, nullable=True)
    light_sleep_min  = db.Column(db.Float, nullable=True)
    awake_min        = db.Column(db.Float, nullable=True)
    sleep_efficiency = db.Column(db.Float, nullable=True)
    sleep_score      = db.Column(db.Float, nullable=True)
    resting_heart_rate = db.Column(db.Float, nullable=True)
    hrv_rmssd          = db.Column(db.Float, nullable=True)
    raw_payload = db.Column(db.JSON, nullable=True)
    created_at  = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at  = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = db.relationship("User", backref=db.backref("wearable_sleep_logs", passive_deletes=True))

    __table_args__ = (
        db.UniqueConstraint("user_id", "provider", "source_id", name="uq_wearable_sleep_source"),
        db.Index("ix_wearable_sleep_user_day", "user_id", "date_key"),
    )


class WearableActivityLog(db.Model):
    id       = db.Column(db.Integer, primary_key=True)
    user_id  = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    provider = db.Column(db.String(40), nullable=False)
    date_key = db.Column(db.String(10), nullable=False, index=True)
    source_id = db.Column(db.String(160), nullable=True)
    steps = db.Column(db.Integer, nullable=False, default=0)
    active_minutes = db.Column(db.Float, nullable=False, default=0)
    calories_burned = db.Column(db.Float, nullable=False, default=0)
    resting_heart_rate = db.Column(db.Float, nullable=True)
    hrv_rmssd = db.Column(db.Float, nullable=True)
    raw_payload = db.Column(db.JSON, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, index=True)

    user = db.relationship("User", backref=db.backref("wearable_activity_logs", passive_deletes=True))

    __table_args__ = (
        db.UniqueConstraint("user_id", "provider", "date_key", name="uq_wearable_activity_day"),
        db.Index("ix_wearable_activity_user_day", "user_id", "date_key"),
    )


class WearableWorkoutLog(db.Model):
    id       = db.Column(db.Integer, primary_key=True)
    user_id  = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    provider = db.Column(db.String(40), nullable=False)
    source_id = db.Column(db.String(160), nullable=False)
    date_key  = db.Column(db.String(10), nullable=False, index=True)
    sport_name = db.Column(db.String(120), nullable=True)
    start_at = db.Column(db.DateTime, nullable=True)
    end_at   = db.Column(db.DateTime, nullable=True)
    calories_burned = db.Column(db.Float, nullable=True)
    strain = db.Column(db.Float, nullable=True)
    average_heart_rate = db.Column(db.Float, nullable=True)
    max_heart_rate = db.Column(db.Float, nullable=True)
    distance_km = db.Column(db.Float, nullable=True)
    raw_payload = db.Column(db.JSON, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = db.relationship("User", backref=db.backref("wearable_workout_logs", passive_deletes=True))

    __table_args__ = (
        db.UniqueConstraint("user_id", "provider", "source_id", name="uq_wearable_workout_source"),
        db.Index("ix_wearable_workout_user_day", "user_id", "date_key"),
    )


class CustomMeal(db.Model):
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    meal_name  = db.Column(db.String(50), nullable=False)
    date_key   = db.Column(db.String(10), nullable=False)
    is_logged  = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user  = db.relationship("User", backref=db.backref("custom_meals", passive_deletes=True))
    items = db.relationship("CustomMealItem", backref="meal",
                            cascade="all, delete-orphan",
                            order_by="CustomMealItem.id")

    __table_args__ = (
        db.UniqueConstraint("user_id", "meal_name", "date_key",
                            name="uq_custom_meal_day"),
    )


class CustomMealItem(db.Model):
    id               = db.Column(db.Integer, primary_key=True)
    custom_meal_id   = db.Column(db.Integer, db.ForeignKey("custom_meal.id", ondelete="CASCADE"), nullable=False, index=True)
    food_name        = db.Column(db.String(200), nullable=False)
    grams            = db.Column(db.Float, nullable=False)
    calories         = db.Column(db.Float, nullable=False, default=0)
    protein          = db.Column(db.Float, nullable=False, default=0)
    carbs            = db.Column(db.Float, nullable=False, default=0)
    fat              = db.Column(db.Float, nullable=False, default=0)
    fatsecret_food_id = db.Column(db.String(50), nullable=True)
    per_100g_calories = db.Column(db.Float, nullable=True)
    per_100g_protein  = db.Column(db.Float, nullable=True)
    per_100g_carbs    = db.Column(db.Float, nullable=True)
    per_100g_fat      = db.Column(db.Float, nullable=True)
    serving_id          = db.Column(db.String(50), nullable=True)
    serving_description = db.Column(db.String(200), nullable=True)
    serving_quantity    = db.Column(db.Float, nullable=True)


class Notification(db.Model):
    # Sosyal bildirimler (Sprint 5 PR1). Satırlar tetikleyen eylemle AYNI
    # transaction'da yazılır (services/notifications.notify — commit etmez).
    # ntype kanonik İngilizce slug kalır; görünen metin istemcide i18n
    # "notif.<ntype>" anahtarından kurulur (i18n display-map kuralı).
    id          = db.Column(db.Integer, primary_key=True)
    user_id     = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)   # alıcı
    actor_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=True, index=True)    # tetikleyen; NULL = sistem
    ntype       = db.Column(db.String(30), nullable=False)   # 'pump_check_like','pump_check_comment','friend_request','friend_accept',...
    target_type = db.Column(db.String(20), nullable=True)    # 'pump_check','friendship' (PR2: 'feed_item', PR3: 'challenge')
    target_id   = db.Column(db.Integer, nullable=True)
    payload     = db.Column(JSONB().with_variant(db.JSON(), "sqlite"), nullable=True)
    is_read     = db.Column(db.Boolean, nullable=False, default=False, server_default="false")
    created_at  = db.Column(db.DateTime, default=datetime.utcnow, nullable=False, index=True)

    __table_args__ = (
        db.Index("ix_notification_user_read", "user_id", "is_read"),
    )

    user  = db.relationship("User", foreign_keys=[user_id],
                            backref=db.backref("notifications", passive_deletes=True))
    actor = db.relationship("User", foreign_keys=[actor_id])


class Challenge(db.Model):
    # Meydan okuma katalogu (Sprint 5 PR3). Statik seed (DailyQuest deseni).
    # code/category/metric/badge_code/challenge_type/period_type kanonik İngilizce
    # slug; title/description kanonik TR (görünen metin t_or ile çevrilir).
    # Genişletme tohumu: challenge_type ('global'|'featured'; ileride duel/team/
    # sponsored), period_type ('weekly'; ileride daily/seasonal).
    id            = db.Column(db.Integer, primary_key=True)
    code          = db.Column(db.String(50), nullable=False, unique=True)
    title         = db.Column(db.String(120), nullable=False)
    description   = db.Column(db.Text)
    category      = db.Column(db.String(30))
    metric        = db.Column(db.String(30), nullable=False, index=True)   # event_type
    target_value  = db.Column(db.Integer, nullable=False, default=1)
    xp_reward     = db.Column(db.Integer, nullable=False, default=100)
    badge_code    = db.Column(db.String(50), nullable=True)
    challenge_type = db.Column(db.String(20), nullable=False, default="global", server_default="global")
    period_type   = db.Column(db.String(20), nullable=False, default="weekly", server_default="weekly")
    is_active     = db.Column(db.Boolean, nullable=False, default=True, server_default="true")
    created_at    = db.Column(db.DateTime, default=datetime.utcnow)


class UserChallengeProgress(db.Model):
    id           = db.Column(db.Integer, primary_key=True)
    user_id      = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    challenge_id = db.Column(db.Integer, db.ForeignKey("challenge.id", ondelete="CASCADE"), nullable=False, index=True)
    period_key   = db.Column(db.String(10), nullable=False, index=True)   # 'YYYY-Www'
    progress     = db.Column(db.Integer, nullable=False, default=0, server_default="0")
    opted_in     = db.Column(db.Boolean, nullable=False, default=True, server_default="true")
    completed_at = db.Column(db.DateTime, nullable=True)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint("user_id", "challenge_id", "period_key", name="uq_user_challenge_period"),
        db.Index("ix_ucp_challenge_period", "challenge_id", "period_key"),
    )

    user      = db.relationship("User", backref=db.backref("challenge_progress", passive_deletes=True))
    challenge = db.relationship("Challenge", backref=db.backref("progress_entries", passive_deletes=True))


class UserBadge(db.Model):
    # Tek-seferlik rozet (UNIQUE user_id+badge_code); tekrar tamamlamada XP verilir,
    # rozet verilmez. source = izleme kaynağı, ör. "challenge:weekly_pump:2026-W29".
    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    badge_code = db.Column(db.String(50), nullable=False)
    source     = db.Column(db.String(80), nullable=True)
    earned_at  = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint("user_id", "badge_code", name="uq_user_badge"),
    )

    user = db.relationship("User", backref=db.backref("badges", passive_deletes=True))
