# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
from flask import (Blueprint, abort, current_app, jsonify, redirect,
                   render_template, request, session, url_for)
from flask_login import current_user, login_required, login_user, logout_user
from flask_limiter.util import get_remote_address
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.attributes import flag_modified
from werkzeug.security import check_password_hash

from app.config import COGNITO_ENABLED
from app.extensions import db, limiter, login_throttle_available
from app.models import User
from app.services import cognito_jwt, cognito_service, session_store
from app.services.cognito_service import CognitoServiceError
from app.services.cognito_jwt import TokenValidationError
from app.services.gamification import complete_quest_for_user
from app.services.referral import consume_referral, ensure_referral_code
from app.services.validators import _DUMMY_PW_HASH, validate_email, validate_password, validate_username
from app.i18n import AVAILABLE_LOCALES, set_locale, t


bp = Blueprint("auth", __name__)

# /login?err=<code> → kullanıcıya gösterilecek mesajın çeviri anahtarı (Cognito
# geri dönüş hatalarını güvenli, sabit bir kümeyle eşler; ham hata sızdırılmaz).
_AUTH_ERROR_KEYS = {
    "cognito": "auth.err_cognito",
    "link": "auth.err_link",
}

_PENDING_REFERRAL_KEY = "pending_referral_code"


def _consume_pending_referral(user):
    """Consume and clear a referral saved during unverified Cognito signup."""
    metadata = dict(user.user_metadata or {})
    code = metadata.get(_PENDING_REFERRAL_KEY)
    if not code:
        return False

    referred = bool(consume_referral(user, code))

    # consume_referral may commit or roll back its atomic claim. Reload the row,
    # then clear the one-time marker for valid and invalid referral codes alike.
    user = db.session.get(User, user.id)
    db.session.refresh(user)
    metadata = dict(user.user_metadata or {})
    metadata.pop(_PENDING_REFERRAL_KEY, None)
    user.user_metadata = metadata
    flag_modified(user, "user_metadata")
    db.session.commit()
    return referred


@bp.route("/set-language", methods=["POST"])
@limiter.limit("30 per hour", key_func=get_remote_address)
def set_language():
    """Anonim/giriş-öncesi TR/EN seçimi. Dili session'a yazar; girişliyse
    hesaba da kalıcılaştırır. CSRF: durum-değiştiren POST → _csrf_protect korur.
    Hafif rate-limit: @login_required değil ve girişliyken DB'ye yazıyor; anonim
    kötüye kullanımı sınırla (2.2)."""
    data = request.get_json(silent=True) or {}
    lang = (data.get("lang") or "").strip().lower()
    if not set_locale(lang):
        return jsonify({"error": t("auth.set_lang_invalid")}), 400
    if current_user.is_authenticated:
        current_user.language = lang
        db.session.commit()
    else:
        # Giriş-öncesi AÇIK seçim işareti: _login_fresh bunu görürse seçimi
        # hesaba taşır. Bayraksız session['lang'] (örn. önceki kullanıcıdan
        # artakalan) hesabı ezmez.
        session["lang_explicit"] = True
    return jsonify({"ok": True, "language": lang})


def _cognito_available():
    return False


def _login_fresh(user):
    """Oturum sabitlemeye (session fixation) karşı: giriş ÖNCESI mevcut oturumu
    temizle, sonra login_user ile taze, kimliği bağlı bir oturum kur. Çerez içeriği
    değiştiği için saldırganın sabitlediği ön-giriş çerezi yeniden kullanılamaz."""
    # Giriş ekranında AÇIKÇA seçilen dil (set-language → lang_explicit) hesabın
    # kayıtlı tercihini günceller — aksi halde kullanıcının az önceki TR/EN
    # seçimi girişte sessizce eski tercihe dönüyordu. Bayraksız session['lang']
    # (önceki oturumdan artakalan) hesabı EZMEZ.
    explicit_lang = session.get("lang") if session.get("lang_explicit") else None
    session.clear()
    login_user(user)
    if explicit_lang in AVAILABLE_LOCALES and explicit_lang != getattr(user, "language", None):
        user.language = explicit_lang
        db.session.commit()
    # Oturum temizlendi → kullanıcının dil tercihini geri yükle (anon istek
    # akışında g.locale tutarlı kalsın; resolve_locale zaten user.language okur).
    if getattr(user, "language", None) in AVAILABLE_LOCALES:
        session["lang"] = user.language


def _login_username_key():
    """Per-account login rate-limit key: the submitted username (lowercased).

    The default login limit is keyed by client IP, which does not throttle a
    *distributed* brute force that spreads guesses for one account across many
    IPs. Keying a second limit on the username closes that gap. Combined with
    `deduct_when` (only failed logins count), a legitimate user who signs in
    successfully is never throttled. Tradeoff: an attacker can still burn a
    victim's failure budget to cause a short, self-healing lockout window — an
    accepted cost of any account-scoped throttle. Falls back to the client IP
    when no username is supplied."""
    data = request.get_json(silent=True) or {}
    uname = (data.get("username") or "").strip().lower()
    return f"login-user:{uname}" if uname else get_remote_address()


@bp.route("/register", methods=["GET","POST"])
@limiter.limit("5 per hour", methods=["POST"])
def register():
    if request.method == "GET":
        return render_template("register.html", cognito_enabled=_cognito_available())
    data = request.get_json(silent=True) or {}
    username = data.get("username")
    email = (data.get("email") or "").strip()
    password = data.get("password")
    # Kayıt-öncesi seçilen dil: gövdeden gelir; yoksa session'daki seçime, o da
    # yoksa varsayılana düşer. Yeni kullanıcıya kalıcılaştırılır.
    chosen_lang = data.get("language")
    if chosen_lang not in AVAILABLE_LOCALES:
        chosen_lang = session.get("lang") if session.get("lang") in AVAILABLE_LOCALES else "tr"

    if not username or not email or not password:
        return jsonify({"error": t("auth.all_fields_required")}), 400

    password_error = validate_password(password)
    if password_error:
        return jsonify({"error": password_error}), 400

    username_error = validate_username(username)
    if username_error:
        return jsonify({"error": username_error}), 400

    email_error = validate_email(email)
    if email_error:
        return jsonify({"error": email_error}), 400

    # Username/email collision. Return one generic message for both checks so the
    # response can't be used to confirm whether a specific username OR e-mail is
    # already registered (account-enumeration hardening). Combined with the per-IP
    # rate limit on this route, this raises the cost of enumeration. Note that
    # usernames are inherently discoverable via the friend search and there is no
    # e-mail login / reset flow, so the residual exposure is low.
    if (User.query.filter_by(username=username).first()
            or User.query.filter_by(email=email).first()):
        return jsonify({"error": t("auth.user_or_email_taken")}), 400

    # Davet döngüsü: kayıt davet bağlantısından geldiyse (cookie veya body)
    # davetçi ile bağla ve iki tarafa da XP ver.
    ref_code = (data.get("ref") or request.cookies.get("fitx_ref") or "").strip()

    if COGNITO_ENABLED:
        # Native Cognito kaydı: kullanıcıyı Cognito'da oluştur (e-postaya DOĞRULAMA
        # KODU gider), `name` attribute'u Cognito'ya BURADA geçer. Kullanıcı /verify
        # sayfasında kodu girene kadar GİRİŞ YAPAMAZ (login Cognito'dan geçer; kod
        # girilmedikçe Cognito UserNotConfirmed döner).
        try:
            sub = cognito_service.sign_up(username=username, password=password,
                                          email=email, name=username)
        except CognitoServiceError as e:
            return jsonify({"error": e.message}), 400
        # Yerel kayıt: profil/davet verisi için hemen oluştur ama parolayı
        # KULLANILAMAZ yap — giriş yalnızca Cognito üzerinden (cognito_sub dolu →
        # yerel parola yolu hiç çalışmaz). app/services/cognito.py ile aynı desen.
        user = User(username=username, email=email, cognito_sub=sub or None,
                    full_name=username, language=chosen_lang)
        if ref_code:
            user.user_metadata = {_PENDING_REFERRAL_KEY: ref_code}
        ensure_referral_code(user)
        db.session.add(user)
        try:
            db.session.commit()
        except Exception as e:
            # Cognito kullanıcı OLUŞTU ama yerel kayıt başarısız → Cognito ORPHAN
            # (Cognito'da hesap var, yerelde yok). UNSIGNED public client admin-delete
            # yapamaz; ops temizliği/retry için AÇIKÇA logla — 500 ile sessizce yutma.
            # Retry: aynı kullanıcı adıyla yeniden kayıt Cognito'dan UsernameExists
            # alır; kullanıcı doğrulama+giriş yapınca get_or_create_user yerel kaydı
            # bağlar (cognito_sub eşleşmesiyle), yani kullanıcı kilitlenmez.
            db.session.rollback()
            current_app.logger.error(
                "[REGISTER] Cognito sign_up başarılı ama yerel commit başarısız "
                "(username=%s) — Cognito orphan olası, manuel temizlik/retry gerekir: %s",
                username, type(e).__name__)
            if isinstance(e, IntegrityError):
                return jsonify({"error": t("auth.user_or_email_taken")}), 409
            return jsonify({"error": t("auth.register_failed")}), 503
        session["lang"] = chosen_lang
        resp = jsonify({"message": t("auth.register_verify_sent"),
                        "needs_verification": True, "username": username,
                        "referred": False})
        if request.cookies.get("fitx_ref"):
            resp.delete_cookie("fitx_ref")
        return resp

    # Cognito kapalı → klasik yerel-yalnız kayıt (geriye dönük uyum).
    user = User(username=username, email=email, language=chosen_lang)
    user.set_password(password)
    ensure_referral_code(user)
    db.session.add(user)
    db.session.commit()
    referred = bool(consume_referral(user, ref_code))
    session["lang"] = chosen_lang

    resp = jsonify({"message": t("auth.register_done", username=username),
                    "referred": referred})
    if request.cookies.get("fitx_ref"):
        resp.delete_cookie("fitx_ref")
    return resp


@bp.route("/login", methods=["GET","POST"])
@limiter.limit("10 per minute; 50 per hour", methods=["POST"])
@limiter.limit("15 per 15 minutes", key_func=_login_username_key, methods=["POST"],
               deduct_when=lambda response: response.status_code == 401)
def login():
    if request.method == "GET":
        err_key = _AUTH_ERROR_KEYS.get(request.args.get("err", ""))
        auth_error = t(err_key) if err_key else None
        return render_template("login.html", cognito_enabled=_cognito_available(),
                               auth_error=auth_error)
    # Fail-closed: Redis (dağıtık brute-force throttle) erişilemiyorsa login'i
    # reddet. Aksi halde limiter bellek-yedeğine düşer ve dağıtık deneme sayımı
    # zayıflar; saldırgan throttle'ı çok-süreçli ortamda aşabilir. Diğer route'lar
    # fail-open kalır (kullanılabilirlik tercihi).
    if current_app.config.get("LOGIN_FAIL_CLOSED", True) and not login_throttle_available():
        current_app.logger.warning(
            "[LOGIN] Redis erişilemiyor — login fail-closed (503), brute-force "
            "throttle güvenilir değil.")
        return jsonify({"error": t("auth.login_unavailable")}), 503
    data = request.get_json(silent=True) or {}
    username = data.get("username")
    password = data.get("password")

    user = User.query.filter_by(username = username).first()

    # Cognito kullanıcısı (cognito_sub dolu): kimlik DOĞRULAMASI Cognito'dan yapılır.
    # Yerel parola hash'i kullanılamaz (rastgele) olduğundan yerel parola yedeği YOK
    # — böylece doğrulanmamış kullanıcı yerel yoldan sızamaz. E-posta doğrulanmamışsa
    # Cognito UserNotConfirmed döner → istemciyi /verify sayfasına yönlendiririz.
    if user and user.cognito_sub and COGNITO_ENABLED:
        try:
            result = cognito_service.authenticate(username, password or "")
        except CognitoServiceError as e:
            # M7 (kabul edilen tradeoff): UserNotConfirmedException, "kayıtlı ama
            # doğrulanmamış" bir hesabı diğer hatalardan (generic bad_credentials,
            # 401) ayırt ettirir → dar bir hesap-sayım (enumeration) sinyali. Bunu
            # bilerek koruyoruz çünkü (a) doğrulanmamış kullanıcıyı /verify sayfasına
            # yönlendiren meşru UX buna bağlı, (b) Cognito app client'ında
            # PreventUserExistenceErrors AÇIK olduğunda bu istisna yalnızca parola
            # DOĞRUYKEN döner (yani ipucu zaten başarılı parola kontrolünün
            # arkasında), (c) per-username rate limit (15/15dk) kaba taramayı kısar.
            if e.code == "UserNotConfirmedException":
                return jsonify({"error": e.message, "needs_verification": True,
                                "username": username}), 403
            return jsonify({"error": e.message}), 401
        tokens = result["tokens"]
        # Kimlik token'ını KRİPTOGRAFİK olarak doğrula (JWKS) — claim'lere manuel
        # güvenme; imza/issuer/audience/exp Cognito JWKS'e karşı sınanır.
        # S4: sub karşılaştırması validate_token'ın DÖNDÜRDÜĞÜ (doğrulanmış)
        # claim'lerden yapılır — authenticate'in doğrulamasız decode'una
        # (result["claims"]) güvenilmez; bir refactor doğrulamayı sessizce
        # anlamsızlaştırmasın.
        try:
            verified_claims = cognito_jwt.validate_token(tokens["id_token"], "id")
        except TokenValidationError:
            return jsonify({"error": t("auth.bad_credentials")}), 401
        # Kimlik bütünlüğü: giriş POZİTİF bir doğrulamadır — dönen sub DOLU
        # olmalı VE yerel kayıtla eşleşmeli. Boş claim (MFA/challenge/bozuk
        # token) asla başarı sayılmaz. (authenticate bu durumları zaten
        # CognitoServiceError ile reddeder; burası ikinci savunma katmanı.)
        if not verified_claims.get("sub") or verified_claims["sub"] != user.cognito_sub:
            return jsonify({"error": t("auth.bad_credentials")}), 401
        _login_fresh(user)
        # _login_fresh session.clear() yapar → cognito_sid'i SONRA yaz. Token'lar
        # sunucu tarafında şifreli saklanır; çerezde yalnızca opak session_id taşınır.
        session["cognito_sid"] = session_store.create(user, tokens, username)
        quest_result = complete_quest_for_user(user.id, "login")
        response = {"message": t("auth.welcome", username=user.username)}
        if quest_result:
            response["quest_awarded"] = quest_result
        return jsonify(response)

    # TODO(Sprint 3): remove legacy local-password login. Kept for users without a
    # cognito_sub until migration completes; Cognito is the auth identity.
    # Always run one password hash comparison, whether or not the username
    # exists, so the response time can't reveal which usernames are registered.
    if user:
        password_ok = user.check_password(password or "")
    else:
        check_password_hash(_DUMMY_PW_HASH, password or "")
        password_ok = False

    if not password_ok:
        return jsonify({"error": t("auth.bad_credentials")}), 401

    _login_fresh(user)
    quest_result = complete_quest_for_user(user.id, "login")
    response = {"message": t("auth.welcome", username=user.username)}
    if quest_result:
        response["quest_awarded"] = quest_result
    return jsonify(response)


@bp.route("/verify", methods=["GET"])
def verify_page():
    """E-posta doğrulama sayfası. Native Cognito kaydı (veya doğrulanmamış giriş
    denemesi) sonrası kullanıcı buraya yönlendirilir; e-postasına gelen kodu girer."""
    if not COGNITO_ENABLED:
        abort(404)
    username = (request.args.get("u") or "").strip()
    return render_template("verify.html", username=username)


@bp.route("/verify", methods=["POST"])
@limiter.limit("10 per 15 minutes", methods=["POST"])
def verify_confirm():
    """Kullanıcının girdiği doğrulama kodunu Cognito'da onayla."""
    if not COGNITO_ENABLED:
        abort(404)
    data = request.get_json(silent=True) or {}
    username = (data.get("username") or "").strip()
    code = (data.get("code") or "").strip()
    if not username or not code:
        return jsonify({"error": t("auth.verify_fields_required")}), 400
    try:
        cognito_service.confirm_sign_up(username, code)
    except CognitoServiceError as e:
        return jsonify({"error": e.message}), 400
    user = User.query.filter_by(username=username).first()
    referred = _consume_pending_referral(user) if user else False
    return jsonify({"message": t("auth.verify_done"), "referred": referred})


@bp.route("/verify/resend", methods=["POST"])
@limiter.limit("3 per 15 minutes", methods=["POST"])
def verify_resend():
    """Doğrulama kodunu yeniden gönder."""
    if not COGNITO_ENABLED:
        abort(404)
    data = request.get_json(silent=True) or {}
    username = (data.get("username") or "").strip()
    if not username:
        return jsonify({"error": t("auth.username_required")}), 400
    try:
        cognito_service.resend_code(username)
    except CognitoServiceError as e:
        return jsonify({"error": e.message}), 400
    return jsonify({"message": t("auth.resend_done")})


@bp.route("/login/cognito")
def cognito_login():
    """Hosted UI is intentionally disabled for the native Cognito migration."""
    abort(404)


@bp.route("/auth/cognito/callback")
def cognito_callback():
    """Hosted UI callback is intentionally disabled for Sprint 1."""
    abort(404)

@bp.route("/logout")
@login_required
def logout():
    # Logout CSRF guard. The logout links across the app are same-site <a>
    # navigations (GET), so this can't be POST-only without reworking every
    # template. Instead, reject cross-site triggers — e.g. an attacker page
    # embedding <img src="/logout"> to silently sign the user out. A genuine
    # same-site navigation reports Sec-Fetch-Site: same-origin/same-site/none;
    # for older browsers without that header we fall back to a Referer check.
    sec_site = request.headers.get("Sec-Fetch-Site")
    if sec_site:
        if sec_site not in ("same-origin", "same-site", "none"):
            abort(403, description=t("route.csrf_failed"))
    else:
        # SEC-1: Sec-Fetch-Site yoksa Referer host'una düş. Referer DE yoksa
        # default-DENY — eskiden kontrol düşüp logout devam ediyordu, böylece
        # her iki başlığı da göndermeyen (legacy/non-browser) istemcilerde CSRF
        # ile sessiz sign-out mümkündü. Meşru same-site <a> gezintisi normalde
        # en az birini taşır.
        referer = request.headers.get("Referer")
        if not referer:
            abort(403, description=t("route.csrf_failed"))
        from urllib.parse import urlparse
        if urlparse(referer).hostname != request.host.split(":")[0]:
            abort(403, description=t("route.csrf_failed"))
    # Cognito oturumu: GlobalSignOut (best-effort — süresi dolmuş token hata
    # verebilir, yut) + sunucu tarafı token satırını sil.
    sid = session.get("cognito_sid")
    if sid:
        access = session_store.current_access_token(sid)
        if access:
            try:
                cognito_service.global_sign_out(access)
            except CognitoServiceError:
                pass
        session_store.delete(sid)
    session.pop("cognito_sid", None)
    session.pop("via_cognito", None)
    logout_user()
    return redirect(url_for("auth.login"))
