# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
from flask import Blueprint, current_app, jsonify, request
from flask_login import current_user
from app.auth_middleware import require_auth

from app.config import FOOD_SEARCH_RATELIMIT
from app.extensions import _user_or_ip_key, limiter
from app.services.ai_coach import _coach_search_food
from app.services import barcode as barcode_svc
from app.services.fatsecret import _food_get_servings, _fs_relevant_candidates, _get_fatsecret_token
from app.services.foodcache import _cache_food_id, _get_cached_food_id, _get_cached_macros
from app.services.gamification import complete_quest_for_user
from app.services import meal_idempotency


bp = Blueprint("food", __name__)


@bp.route("/api/food/search")
@require_auth
@limiter.limit(FOOD_SEARCH_RATELIMIT, key_func=_user_or_ip_key)
def food_search():
    q = request.args.get("q", "").strip()
    if len(q) < 2:
        return jsonify({"results": []})

    # Koç araması 100g-bazlı yazar; aynı bazdan oku (eski kod düz _macro_cache.get(q)
    # ile iki-katmanlı sözlüğe baktığı için DAİMA ıskalıyordu — bkz foodcache.py).
    hits, _ = _get_cached_macros([q], "per_100g")
    cached = hits.get(q)
    if cached:
        cached_fid = _get_cached_food_id(q)
        current_app.logger.debug("food_search cache hit for '%s', food_id=%s", q, cached_fid or "(none)")
        return jsonify({"results": [{
            "name": q, "brand": "",
            "food_id": cached_fid,
            "serving": "", "is_per_serving": False,
            "macros": cached, "per_100g": cached
        }]})

    # Alaka-kapısı + TR→EN normalizasyonlu birleşik arama (koç ile aynı yol):
    # FatSecret Türkçe sorgulara ilgisiz jenerik besin döndürdüğü için ham
    # results[0]'a güvenmek yanlış makro veriyordu ('patates' → 'Soy Nuts').
    results = _coach_search_food(q)

    return jsonify({"results": results})


@bp.route("/api/food/barcode")
@require_auth
@limiter.limit(FOOD_SEARCH_RATELIMIT, key_func=_user_or_ip_key)
def food_by_barcode():
    """Barkod (EAN/UPC) → FatSecret ürünü + porsiyonlar. Barkod tarama akışı
    (static/nutrition.js) buradan besin çözer, sonra mevcut porsiyon modaline
    devreder — ayrı bir loglama yolu YOK."""
    code = request.args.get("code", "").strip()
    if not barcode_svc.normalize_barcode(code):
        return jsonify({"error": "invalid_barcode"}), 400
    product = barcode_svc.get_barcode_product(code)
    if not product:
        return jsonify(barcode_svc.not_found_response()), 404
    context = barcode_svc.get_user_barcode_context(
        current_user.id,
        meal_time=request.args.get("meal_time", "").strip(),
    )
    return jsonify(barcode_svc.build_lookup_response(product, context))


@bp.route("/api/food/barcode/add", methods=["POST"])
@require_auth
@limiter.limit(FOOD_SEARCH_RATELIMIT, key_func=_user_or_ip_key)
def barcode_add_to_diary():
    data = request.get_json(silent=True) or {}
    meal = (data.get("meal") or "").strip()
    if meal not in ("Kahvaltı", "Öğle", "Akşam", "Ara Öğün"):
        return jsonify({"error": "invalid_meal"}), 400

    idempotency_key = meal_idempotency.read_idempotency_key()
    existing = meal_idempotency.find_existing(current_user.id, idempotency_key)
    if existing:
        goal_impact = barcode_svc.goal_impact_for_add(current_user.id, {
            "calories": 0, "protein": 0, "carbs": 0, "fat": 0,
        })
        return jsonify({
            "message": "logged", "meal_log_id": existing.id,
            "nutrients": {
                "kalori": round(existing.kalori or 0, 1),
                "protein": round(existing.protein or 0, 1),
                "karb": round(existing.karb or 0, 1),
                "yag": round(existing.yag or 0, 1),
            },
            "goal_impact": goal_impact,
            "analytics_events": ["Added To Diary"],
        })

    food = data.get("food")
    if not isinstance(food, dict):
        product = barcode_svc.get_barcode_product(data.get("barcode", ""))
        food = product["food"] if product else None
    if not food:
        return jsonify(barcode_svc.not_found_response()), 404

    serving, added_preview = barcode_svc.scale_serving_macros(
        food,
        data.get("serving_id"),
        data.get("serving_quantity", 1),
    )
    if not serving or not added_preview or added_preview["calories"] <= 0:
        return jsonify({"error": "invalid_serving"}), 400
    goal_impact = barcode_svc.goal_impact_for_add(current_user.id, added_preview)

    result = barcode_svc.add_food_to_diary(
        current_user.id,
        food,
        meal,
        serving_id=data.get("serving_id"),
        quantity=data.get("serving_quantity", 1),
        idempotency_key=idempotency_key,
    )
    if not result:
        return jsonify({"error": "invalid_serving"}), 400
    entry, created = result

    quest_result = complete_quest_for_user(current_user.id, "meal_logged") if created else None
    response = {
        "message": "logged",
        "meal_log_id": entry.id,
        "nutrients": {
            "kalori": round(entry.kalori or 0, 1),
            "protein": round(entry.protein or 0, 1),
            "karb": round(entry.karb or 0, 1),
            "yag": round(entry.yag or 0, 1),
        },
        "goal_impact": goal_impact,
        "analytics_events": ["Added To Diary"],
    }
    if quest_result:
        response["quest_awarded"] = quest_result
    return jsonify(response)


@bp.route("/api/food/<food_id>/servings")
@require_auth
@limiter.limit(FOOD_SEARCH_RATELIMIT, key_func=_user_or_ip_key)
def food_servings(food_id):
    current_app.logger.info("food_servings called with food_id=%s", food_id)
    servings = _food_get_servings(food_id)
    if servings:
        current_app.logger.info("Servings OK for food_id=%s: %d options, first=%s",
                        food_id, len(servings), servings[0].get("serving_description", "?"))
        return jsonify({"servings": servings})
    else:
        current_app.logger.warning("No servings for food_id=%s", food_id)
        return jsonify({"servings": [], "debug": "no_servings_returned"})


@bp.route("/api/food/servings-by-name")
@require_auth
@limiter.limit(FOOD_SEARCH_RATELIMIT, key_func=_user_or_ip_key)
def food_servings_by_name():
    name = request.args.get("name", "").strip()
    if len(name) < 2:
        return jsonify({"servings": [], "food_id": ""})

    # Check food_id cache first (populated by previous FatSecret searches)
    cached_fid = _get_cached_food_id(name) or None
    if cached_fid:
        current_app.logger.info("servings-by-name: cache hit food_id=%s for '%s'", cached_fid, name)
        servings = _food_get_servings(cached_fid)
        if servings:
            return jsonify({"servings": servings, "food_id": cached_fid})

    # English translations for common Turkish food names (raw + EN arama terimi).
    _TR_TO_EN = {
        "yumurta": "egg", "tavuk": "chicken", "pirinc": "rice", "pilav": "rice pilaf",
        "ekmek": "bread", "sut": "milk", "süt": "milk", "peynir": "cheese",
        "yogurt": "yogurt", "yoğurt": "yogurt", "bal": "honey", "tereyagi": "butter",
        "tereyağı": "butter", "makarna": "pasta", "salata": "salad",
        "domates": "tomato", "patates": "potato", "havuc": "carrot", "havuç": "carrot",
        "elma": "apple", "muz": "banana", "portakal": "orange", "balik": "fish",
        "balık": "fish", "ton baligi": "tuna", "somon": "salmon",
        "brokoli": "broccoli", "ispanak": "spinach", "fasulye": "beans",
        "nohut": "chickpea", "mercimek": "lentil", "ceviz": "walnut",
        "badem": "almond", "findik": "hazelnut", "fındık": "hazelnut",
        "zeytin": "olive", "zeytinyagi": "olive oil", "zeytinyağı": "olive oil",
        "avokado": "avocado", "kayisi": "apricot", "kayısı": "apricot",
        "cilek": "strawberry", "çilek": "strawberry", "karpuz": "watermelon",
    }
    en = _TR_TO_EN.get(name.lower())
    english = en if (en and en.lower() != name.lower()) else ""

    # N3: FatSecret'in `max_results:1` sonucuna KÖRLEMESİNE güvenmek yanlış makro
    # veriyordu — eşleyemediği Türkçe sorgulara ilgisiz jenerik döndürüp ('mercimek
    # köftesi' → alakasız kayıt) hem kullanıcıya hem GLOBAL food_id cache'ine yanlış
    # besini yazıyordu. food_search'teki gibi alaka-kapısından geçir: adayları
    # _is_specific_match ile ele, en spesifik eşleşmeyi al, YALNIZCA doğrulanmış
    # eşleşmede _cache_food_id yaz.
    try:
        token = _get_fatsecret_token()
        candidates = _fs_relevant_candidates(name, english, token)
        if candidates:
            fid = candidates[0].get("food_id", "")
            current_app.logger.info("servings-by-name: relevant food_id=%s for '%s'", fid, name)
            if fid:
                servings = _food_get_servings(fid)
                if servings:
                    _cache_food_id(name, fid)  # yalnızca porsiyonlar da geldiyse önbelleğe al
                    return jsonify({"servings": servings, "food_id": fid})
                current_app.logger.warning("servings-by-name: food.get returned no servings for id=%s", fid)
        else:
            current_app.logger.info("servings-by-name: no relevant match for '%s'", name)
    except Exception as e:
        current_app.logger.warning("servings-by-name failed for '%s': %s", name, e)
    return jsonify({"servings": [], "food_id": ""})
