# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import math

from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from flask_login import current_user
from app.auth_middleware import require_auth
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import joinedload

from app.blueprints.supplements import CATEGORY_ICONS
from app.extensions import db
from app.i18n import t
from app.models import PumpCheck, Supplement, User, UserWearableConnection
from app.services import account_profile
from app.services.avatars import release_unreferenced_avatar, set_user_avatar
from app.services.pump_checks import release_pump_check_image, serialize_pump_check_card
from app.services.validators import validate_full_name, validate_username


bp = Blueprint("profile", __name__)


@bp.after_request
def prevent_profile_cache(response):
    if request.endpoint == "profile.edit_profile":
        response.headers["Cache-Control"] = "private, no-store"
    return response


_SETUP_REQUIRED = ["weight", "height", "age", "gender", "goal", "fitness_level", "current_activity"]


def _setup_target_weight(value):
    """Browser leniency, kept: an unusable optional target weight is dropped.

    `None` leaves the stored target untouched. What counts as unusable is the
    shared domain rule, so a value the service would refuse is dropped here
    instead of failing the whole onboarding.
    """
    if not value:
        return None
    try:
        weight = float(value)
    except (ValueError, TypeError, OverflowError):
        return None
    if not (math.isfinite(weight)
            and account_profile.BODY_WEIGHT_MIN_KG <= weight
            <= account_profile.BODY_WEIGHT_MAX_KG):
        return None
    return weight


_SETUP_TOKEN_FIELDS = frozenset({
    account_profile.GENDER, account_profile.FITNESS_LEVEL,
    account_profile.CURRENT_ACTIVITY,
})


def _setup_rejection(rejection):
    """The browser's existing i18n sentence for a domain rejection."""
    if rejection.field == account_profile.GOAL:
        return t("route.invalid_goal")
    if rejection.field in _SETUP_TOKEN_FIELDS:
        return t("route.invalid_value")
    if (rejection.field == account_profile.WEIGHT
            and rejection.reason == account_profile.REASON_RANGE):
        return t("route.weight_range")
    return t("route.body_numeric")


@bp.route("/setup", methods=["GET", "POST"])
@require_auth
def setup():
    if request.method == "GET":
        # Profili tamamlanmış kullanıcı için boş sihirbazı yeniden açma — mevcut
        # profil/planı yanlışlıkla sıfırlamasın diye panoya yönlendir. Bilinçli
        # yeniden kurulum için ?yeniden=1 ile gelinebilir. "Tamamlanmış" kanonik
        # kuraldır (account_profile.onboarding_state), ham bayrak değil.
        if (account_profile.onboarding_state(current_user).complete
                and not request.args.get("yeniden")):
            return redirect(url_for("tracking.home"))
        return render_template("setup.html", username=current_user.username)

    # Transport only: parse the browser's wire format, then hand a validated
    # domain profile to the ONE onboarding service (app/services/account_profile.py).
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        data = {}

    for field in _SETUP_REQUIRED:
        if not data.get(field):
            return jsonify({"error": t("coach.field_missing", field=field)}), 400

    try:
        weight = float(data["weight"])
        height = float(data["height"])
        age = int(data["age"])
    except (ValueError, TypeError, OverflowError):
        return jsonify({"error": t("route.body_numeric")}), 400

    # The browser form posts the stored goal literal; the service speaks tokens.
    goal = account_profile.goal_token(data["goal"])
    if goal is None:
        return jsonify({"error": t("route.invalid_goal")}), 400

    try:
        profile = account_profile.OnboardingProfile(
            weight=weight, height=height, age=age,
            gender=data["gender"], goal=goal,
            fitness_level=data["fitness_level"],
            current_activity=data["current_activity"],
            target_weight=_setup_target_weight(data.get("target_weight")),
        )
    except account_profile.ProfileRejected as rejection:
        return jsonify({"error": _setup_rejection(rejection)}), 400

    result = account_profile.complete_onboarding(current_user, profile)

    return jsonify({
        "message": t("route.profile_saved"),
        "bmr": round(result.bmr),
        "tdee": round(result.tdee),
        "target_calories": round(result.target_calories)
    })


@bp.route("/edit-profile", methods=["GET", "POST"])
@require_auth
def edit_profile():
    if request.method == "GET":
        supps = Supplement.query.filter_by(user_id=current_user.id)\
            .filter(Supplement.status.in_(["Active", "Low Stock"]))\
            .order_by(Supplement.created_at.desc()).all()
        wearable_connections = {
            row.provider: row for row in UserWearableConnection.query
            .filter_by(user_id=current_user.id).all()
        }
        return render_template("edit_profile.html",
            username=current_user.username,
            full_name=current_user.full_name or "",
            profile_picture=current_user.avatar_src or "",
            goal=current_user.goal or "",
            target_weight=current_user.target_weight,
            streak_count=current_user.streak_count or 0,
            supplements=supps,
            icons=CATEGORY_ICONS,
            wearable_connections=wearable_connections,
            is_premium=bool(current_user.is_premium),
        )

    data = request.get_json(silent=True) or {}

    if set(data) == {"profile_picture"}:
        old_key = current_user.profile_picture_key
        pic_error = set_user_avatar(current_user, data["profile_picture"])
        if pic_error:
            return jsonify({"error": pic_error}), 400
        uploaded_key = current_user.profile_picture_key
        try:
            db.session.commit()
        except Exception:
            db.session.rollback()
            release_unreferenced_avatar(current_user, uploaded_key)
            raise
        release_unreferenced_avatar(current_user, old_key)
        return jsonify({"message": t("editprofile.avatar_updated")})

    new_username = (data.get("username") or "").strip()
    new_full_name = (data.get("full_name") or "").strip()
    new_goal = (data.get("goal") or "").strip()

    username_error = validate_username(new_username)
    if username_error:
        return jsonify({"error": username_error}), 400

    if new_username != current_user.username:
        if User.query.filter_by(username=new_username).first():
            return jsonify({"error": t("route.username_taken")}), 400

    full_name_error = validate_full_name(new_full_name)
    if full_name_error:
        return jsonify({"error": full_name_error}), 400

    old_avatar_key = current_user.profile_picture_key
    uploaded_avatar_key = old_avatar_key
    if "profile_picture" in data:
        # S3 açıksa avatarı S3'e koyar (key saklar, base64'ü temizler); kapalıysa
        # eski base64 davranışına düşer. Validasyon (≤500KB + gerçek görsel) içeride.
        pic_error = set_user_avatar(current_user, data.get("profile_picture"))
        if pic_error:
            return jsonify({"error": pic_error}), 400
        uploaded_avatar_key = current_user.profile_picture_key

    valid_goals = ["kilo verme", "kas kazanma", ""]
    if new_goal not in valid_goals:
        return jsonify({"error": t("route.invalid_goal")}), 400

    current_user.username = new_username
    current_user.full_name = new_full_name if new_full_name else None
    if new_goal:
        current_user.goal = new_goal
        current_user.goal_type = "loss" if new_goal == "kilo verme" else "gain"

    new_target_weight = data.get("target_weight")
    if new_target_weight is not None:
        try:
            current_user.target_weight = float(new_target_weight) if new_target_weight else None
        except (ValueError, TypeError):
            pass

    try:
        db.session.commit()
    except IntegrityError:
        # Username benzersizlik kontrolü (yukarıda) ile commit atomik değil — iki
        # eşzamanlı istek aynı adı alabilir. DB unique kısıtı (models.py) gerçek
        # guard; çakışmada 500 yerine dostça "kullanımda" mesajı dön (2.4).
        db.session.rollback()
        if "profile_picture" in data:
            release_unreferenced_avatar(current_user, uploaded_avatar_key)
        return jsonify({"error": t("route.username_taken")}), 400
    except Exception:
        db.session.rollback()
        if "profile_picture" in data:
            release_unreferenced_avatar(current_user, uploaded_avatar_key)
        raise
    if "profile_picture" in data:
        release_unreferenced_avatar(current_user, old_avatar_key)
    return jsonify({"message": t("route.profile_updated")})


@bp.route("/pump-check-gallery")
@require_auth
def pump_check_gallery():
    return render_template(
        "pump_check_gallery.html",
        username=current_user.username,
        profile_picture=current_user.avatar_src,
    )


@bp.route("/pump-check-gallery/data")
@require_auth
def pump_check_gallery_data():
    try:
        page = max(int(request.args.get("page", 1) or 1), 1)
    except (TypeError, ValueError):
        page = 1
    try:
        per_page = min(max(int(request.args.get("per_page", 18) or 18), 1), 36)
    except (TypeError, ValueError):
        per_page = 18
    rows = PumpCheck.query.filter_by(user_id=current_user.id).options(
        joinedload(PumpCheck.user),
    ).order_by(
        PumpCheck.created_at.desc(),
        PumpCheck.id.desc(),
    ).offset(
        (page - 1) * per_page,
    ).limit(
        per_page + 1,
    ).all()
    items = rows[:per_page]
    return jsonify({
        "items": [
            serialize_pump_check_card(
                row,
                current_user.id,
                image_visibility_preauthorized=True,
            )
            for row in items
        ],
        "hasMore": len(rows) > per_page,
        "nextPage": page + 1 if len(rows) > per_page else None,
    })


@bp.route("/pump-check-gallery/<int:check_id>", methods=["DELETE"])
@require_auth
def pump_check_gallery_delete(check_id):
    check = PumpCheck.query.filter_by(id=check_id, user_id=current_user.id).first_or_404()
    image_key = check.image_key
    owner_id = check.user_id
    # Feed V2 (Sprint 5 PR2): bu pump check'e ATIFTA BULUNAN repost/quote'lar
    # (ref_id FK'siz) askıda kalmasın diye önce çocuklarıyla birlikte silinir.
    from app.models import FeedItem, FeedItemComment, FeedItemLike
    ref_items = [i for (i,) in db.session.query(FeedItem.id).filter(
        FeedItem.ref_type == "pump_check", FeedItem.ref_id == check.id).all()]
    if ref_items:
        FeedItemLike.query.filter(FeedItemLike.feed_item_id.in_(ref_items)).delete(synchronize_session=False)
        FeedItemComment.query.filter(FeedItemComment.feed_item_id.in_(ref_items)).delete(synchronize_session=False)
        FeedItem.query.filter(FeedItem.id.in_(ref_items)).delete(synchronize_session=False)
    # Sprint 5 PR3: silinen pump check'i ve reposts'larını HEDEF ALAN bildirimler
    # ölü kalmasın (tıklanınca "içerik yok") diye aynı transaction'da süpürülür —
    # pump_check_like/comment + repost/quote + feed_like/feed_comment. (COMMIT ETMEZ.)
    from app.services.notifications import purge_content_notifications
    purge_content_notifications(pump_check_ids=[check.id], feed_item_ids=ref_items)
    db.session.delete(check)
    db.session.commit()
    release_pump_check_image(owner_id, image_key)
    return jsonify({"ok": True})
