# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
from flask import Blueprint, jsonify, render_template, request
from flask_login import current_user
from app.auth_middleware import require_auth

from app.extensions import db
from app.i18n import t
from app.models import Supplement, User
from app.services.gamification import award_xp, complete_quest_for_user, log_activity
from app.services.validators import _to_float


bp = Blueprint("supplements", __name__)


@bp.route("/supplements")
@require_auth
def supplements_page():
    supps = Supplement.query.filter_by(user_id=current_user.id)\
        .order_by(Supplement.created_at.desc()).all()
    return render_template("manage_stack.html",
        username=current_user.username,
        profile_picture=current_user.avatar_src,
        supplements=supps,
        categories=SUPPLEMENT_CATEGORIES,
        statuses=SUPPLEMENT_STATUSES,
        icons=CATEGORY_ICONS)


@bp.route("/supplement/add", methods=["POST"])
@require_auth
def supplement_add():
    data = request.get_json(silent=True) or {}
    name = (data.get("product_name") or "").strip()
    brand = (data.get("brand") or "").strip()
    if not name or not brand:
        return jsonify({"error": t("manage_stack.required")}), 400

    category = data.get("category", "Other")
    if category not in SUPPLEMENT_CATEGORIES:
        category = "Other"
    status = data.get("status", "Active")
    if status not in SUPPLEMENT_STATUSES:
        status = "Active"

    def parse_rating(val):
        if val is None or val == "" or val == 0:
            return None
        try:
            v = int(val)
            return v if 1 <= v <= 5 else None
        except (ValueError, TypeError):
            return None

    supp = Supplement(
        user_id=current_user.id,
        product_name=name, brand=brand,
        category=category, status=status,
        rating_effect=parse_rating(data.get("rating_effect")),
        rating_taste=parse_rating(data.get("rating_taste")),
        rating_digestion=parse_rating(data.get("rating_digestion")),
        rating_price=parse_rating(data.get("rating_price")),
        review_text=(data.get("review_text") or "").strip() or None,
        price_paid=_to_float(data["price_paid"], None) if data.get("price_paid") else None,
        is_public=data.get("is_public", True),
    )
    # İlk supplement bonusu (25 XP) tam olarak BİR kez verilmeli. Eskiden count
    # kilitsiz okunuyordu; iki eşzamanlı "ilk supplement" POST'u (çift-dokunma/
    # retry) da prior_count==0 görüp çifte bonus verebiliyordu (BUG-2). Kararı
    # kullanıcı satırı kilidiyle serileştir: kilidi count'tan ÖNCE al ve supp
    # commit'ine kadar tut. FOR UPDATE ikinci eşzamanlı isteği ilk commit'lenene
    # kadar bloklar; o da count'u ilk satır GÖRÜNÜR olduktan sonra yapıp 1 görür.
    # (SQLite'ta no-op ama orada da tek yazar var.)
    db.session.query(User.id).filter_by(id=current_user.id).with_for_update().first()
    prior_count = Supplement.query.filter_by(user_id=current_user.id).count()
    db.session.add(supp)
    db.session.commit()

    if prior_count == 0:
        award_xp(current_user.id, 25)
        db.session.commit()

    # Activity yazısını HEMEN commit'le. Önceden yalnızca session'a eklenip
    # commit'i bir sonraki complete_quest_for_user'a bırakıyordu; o da görev zaten
    # claimliyse None dönüp commit ETMEDEN çıkıyor, böylece new_supplement satırı
    # pending kalıp alakasız bir sonraki istekte düşebiliyordu (1.2).
    log_activity(current_user.id, "new_supplement", f"{name} ({category}) stack'ine eklendi")
    db.session.commit()
    quest_result = complete_quest_for_user(current_user.id, "supplement_added")

    response = {"message": t("route.supp_added"), "id": supp.id}
    if quest_result:
        response["quest_awarded"] = quest_result
    return jsonify(response)


@bp.route("/supplement/edit/<int:sid>", methods=["POST"])
@require_auth
def supplement_edit(sid):
    supp = Supplement.query.filter_by(id=sid, user_id=current_user.id).first_or_404()

    data = request.get_json(silent=True) or {}

    if "product_name" in data:
        name = (data["product_name"] or "").strip()
        if name:
            supp.product_name = name
    if "brand" in data:
        brand = (data["brand"] or "").strip()
        if brand:
            supp.brand = brand
    if "category" in data and data["category"] in SUPPLEMENT_CATEGORIES:
        supp.category = data["category"]
    if "status" in data and data["status"] in SUPPLEMENT_STATUSES:
        supp.status = data["status"]

    def parse_rating(val):
        if val is None or val == "" or val == 0:
            return None
        try:
            v = int(val)
            return v if 1 <= v <= 5 else None
        except (ValueError, TypeError):
            return None

    for field in ["rating_effect", "rating_taste", "rating_digestion", "rating_price"]:
        if field in data:
            setattr(supp, field, parse_rating(data[field]))
    if "review_text" in data:
        supp.review_text = (data["review_text"] or "").strip() or None
    if "price_paid" in data:
        supp.price_paid = _to_float(data["price_paid"], None) if data["price_paid"] else None
    if "is_public" in data:
        supp.is_public = bool(data["is_public"])

    db.session.commit()
    return jsonify({"message": t("route.supp.updated")})


@bp.route("/supplement/delete/<int:sid>", methods=["POST"])
@require_auth
def supplement_delete(sid):
    supp = Supplement.query.filter_by(id=sid, user_id=current_user.id).first_or_404()
    db.session.delete(supp)
    db.session.commit()
    return jsonify({"message": t("route.supp_deleted")})


SUPPLEMENT_CATEGORIES = ["Protein", "Amino Acid", "Pre-Workout", "Vitamin/Health", "Creatine", "Other"]


SUPPLEMENT_STATUSES   = ["Active", "Low Stock", "Finished"]


CATEGORY_ICONS = {
    "Protein": "\U0001f964", "Amino Acid": "\U0001f4a7", "Pre-Workout": "⚡",
    "Vitamin/Health": "\U0001f48a", "Creatine": "\U0001f4aa", "Other": "\U0001f4e6",
}
