# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import json
from datetime import date, datetime
from flask import Blueprint, Response, g, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app.config import AI_RATELIMIT, BEDROCK_RATELIMIT
from app.extensions import _user_or_ip_key, db, limiter
from app.models import DailyActivity, User, UserDailyNutrition, UserSession, WeeklyCheckIn, WeeklyLog, WorkoutLog
from app.services.ai_coach import generate_checkin_feedback
from app.services.calculations import MET_CONFIG, calculate_activity_calories, calculate_bmr, calculate_target, calculate_tdee


bp = Blueprint("tracking", __name__)


@bp.route("/")
@login_required
def home():
    if not current_user.profile_complete:
        return redirect(url_for("profile.setup"))
    # Son kilo güncellemesi zamanı (kilo butonu "hatırlatma" parıltısı için —
    # cihazlar arası tutarlı olsun diye sunucudan, localStorage yerine).
    last_checkin = WeeklyCheckIn.query.filter_by(user_id=current_user.id)\
        .order_by(WeeklyCheckIn.created_at.desc()).first()
    last_weight_update = (last_checkin.created_at.isoformat() + "Z") if last_checkin else ""
    return render_template("index.html",
        username=current_user.username,
        profile_picture=current_user.profile_picture,
        streak_count=current_user.streak_count or 0,
        last_weight_update=last_weight_update,
    )


@bp.route("/log", methods=["POST"])
@login_required
def log_progress():
    data = request.get_json(silent=True) or {}
    weight = data.get("weight")
    note = data.get("note", "")

    if not weight:
        return jsonify({"error" : "Kilo zorunludur"}), 400
    
    try:
        weight = float(weight)
    except ValueError:
        return jsonify({"error" : "Kilo sayısal olmalıdır"}), 400
    
    entry = WeeklyLog(
        user_id = current_user.id,
        weight=weight,
        note=note
    )
    db.session.add(entry)
    db.session.commit()

    # Önceki kayıtlarla karşılaştırma
    previous = WeeklyLog.query.filter_by(user_id=current_user.id)\
    .order_by(WeeklyLog.created_at.desc())\
    .offset(1).first()

    message = f"{weight} kg kaydedildi."
    if previous:
        diff = round(weight - previous.weight , 1)
        if diff < 0:
            message += f"Geçen kayda göre {abs(diff)} kg verdin. 🔥"
        elif diff > 0:
            message = f"Geçen kayda göre {abs(diff)} kg aldın."
        else:
            message += "Geçen kayıtla aynı kilo. Tutarlısın."
    return jsonify({"message" : message})


@bp.route("/progress")
@login_required
def progress():
    logs = WeeklyLog.query.filter_by(user_id=current_user.id)\
    .order_by(WeeklyLog.created_at.asc())\
    .all()

    result = []
    for log in logs:
        result.append({
            "tarih" : log.created_at.strftime("%d.%m"),
            "kilo" : log.weight,
            "not" : log.note
        })
    return Response(
            json.dumps(result, ensure_ascii=False),
            mimetype="application/json"
        )


@bp.route("/checkin", methods=["POST"])
@login_required
@limiter.limit(AI_RATELIMIT, key_func=_user_or_ip_key)
@limiter.limit(BEDROCK_RATELIMIT, key_func=_user_or_ip_key)  # generate_checkin_feedback Sonnet'te: daha sıkı tavan
def checkin():
    data = request.get_json(silent=True) or {}

    weight = data.get("weight")
    if not weight:
        return jsonify({"error": "Kilo zorunludur"}), 400

    try:
        weight = float(weight)
    except ValueError:
        return jsonify({"error": "Kilo sayısal olmalıdır"}), 400

    yogunluk    = int(data.get("yogunluk", 3))
    fatigue     = int(data.get("fatigue", 3))
    overload    = data.get("progressive_overload", "kismen")
    if overload not in ("evet", "hayir", "kismen"):
        overload = "kismen"
    uyku        = int(data.get("uyku_kalitesi", 3))
    beslenme    = int(data.get("beslenme_uyumu", 3))
    note        = data.get("note", "")

    # Önceki check-in'i al
    previous = WeeklyCheckIn.query.filter_by(user_id=current_user.id)\
        .order_by(WeeklyCheckIn.created_at.desc())\
        .first()

    # Son oturum bilgilerini al
    last_session = UserSession.query.filter_by(user_id=current_user.id)\
        .order_by(UserSession.created_at.desc())\
        .first()

    goal = last_session.goal if last_session else "genel sağlık"

    # İlerleme hesapla
    prev_weight = previous.weight if previous else None
    days_passed = None
    if previous:
        days_passed = (datetime.utcnow() - previous.created_at).days

    # AI koç geri bildirimi
    coach_feedback = generate_checkin_feedback(
        current_user.username, weight, prev_weight, days_passed,
        goal, yogunluk, fatigue, overload, uyku, beslenme, note
    )

    entry = WeeklyCheckIn(
        user_id=current_user.id,
        weight=weight,
        yogunluk=yogunluk,
        fatigue=fatigue,
        progressive_overload=overload,
        uyku_kalitesi=uyku,
        beslenme_uyumu=beslenme,
        note=note,
        coach_feedback=coach_feedback
    )
    db.session.add(entry)
    db.session.commit()

    return jsonify({
        "message": "Check-in kaydedildi.",
        "coach_feedback": coach_feedback
    })


@bp.route("/checkin-history")
@login_required
def checkin_history():
    checkins = WeeklyCheckIn.query.filter_by(user_id=current_user.id)\
        .order_by(WeeklyCheckIn.created_at.asc())\
        .all()

    result = []
    for c in checkins:
        result.append({
            "tarih"     : c.created_at.strftime("%d.%m"),
            "kilo"      : c.weight,
            "yogunluk"  : c.yogunluk,
            "fatigue"   : c.fatigue,
            "overload"  : c.progressive_overload,
            "uyku"      : c.uyku_kalitesi,
            "beslenme"  : c.beslenme_uyumu,
            "feedback"  : c.coach_feedback
        })

    return Response(
        json.dumps(result, ensure_ascii=False),
        mimetype="application/json"
    )


@bp.route("/update-weight", methods=["POST"])
@login_required
def update_weight():
    data = request.get_json(silent=True) or {}
    weight = data.get("weight")

    if not weight:
        return jsonify({"error": "Kilo zorunludur"}), 400

    try:
        weight = float(weight)
    except ValueError:
        return jsonify({"error": "Kilo sayısal olmalıdır"}), 400

    current_user.weight = weight

    bmr             = calculate_bmr(weight, current_user.height, current_user.age, current_user.gender)
    tdee            = calculate_tdee(bmr, current_user.current_activity)
    target_calories = calculate_target(tdee, current_user.goal)

    last_sess = UserSession.query.filter_by(user_id=current_user.id)\
        .order_by(UserSession.created_at.desc()).first()
    if last_sess:
        last_sess.weight          = weight
        last_sess.bmr             = bmr
        last_sess.tdee            = tdee
        last_sess.target_calories = target_calories

    today_start = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
    today_checkin = WeeklyCheckIn.query.filter(
        WeeklyCheckIn.user_id == current_user.id,
        WeeklyCheckIn.created_at >= today_start
    ).first()
    if today_checkin:
        today_checkin.weight = weight
    else:
        db.session.add(WeeklyCheckIn(user_id=current_user.id, weight=weight))

    db.session.commit()

    return jsonify({
        "bmr": round(bmr),
        "tdee": round(tdee),
        "target_calories": round(target_calories)
    })


@bp.route("/api/activity/log", methods=["POST"])
@login_required
def log_daily_activity():
    data = request.get_json(silent=True) or {}
    steps = int(data.get("steps", 0))
    intensity = data.get("intensity", "moderate")

    if intensity not in MET_CONFIG:
        return jsonify({"error": "Geçersiz yoğunluk"}), 400
    if steps <= 0:
        return jsonify({"error": "Adım sayısı pozitif olmalı"}), 400

    weight = current_user.weight or 70
    height = current_user.height or 170
    calories, distance, duration = calculate_activity_calories(steps, intensity, weight, height)

    today_key = date.today().isoformat()
    existing = DailyActivity.query.filter_by(
        user_id=current_user.id, date_key=today_key, intensity=intensity
    ).first()

    if existing:
        existing.steps = steps
        existing.calories_burned = calories
        existing.distance_km = distance
        existing.duration_min = duration
    else:
        db.session.add(DailyActivity(
            user_id=current_user.id, steps=steps, intensity=intensity,
            calories_burned=calories, distance_km=distance,
            duration_min=duration, date_key=today_key
        ))

    db.session.commit()
    return jsonify({
        "message": f"{steps} adım kaydedildi.",
        "calories_burned": calories,
        "distance_km": distance,
        "duration_min": duration
    })


@bp.route("/api/activity/today")
@login_required
def today_activity():
    today_key = date.today().isoformat()
    activities = DailyActivity.query.filter_by(
        user_id=current_user.id, date_key=today_key
    ).all()

    total_calories = sum(a.calories_burned or 0 for a in activities)
    total_steps = sum(a.steps or 0 for a in activities)
    total_distance = sum(a.distance_km or 0 for a in activities)

    entries = [{
        "intensity": a.intensity, "steps": a.steps,
        "calories_burned": a.calories_burned,
        "distance_km": a.distance_km, "duration_min": a.duration_min,
    } for a in activities]

    return jsonify({
        "total_calories": round(total_calories, 1),
        "total_steps": total_steps,
        "total_distance": round(total_distance, 2),
        "entries": entries
    })


@bp.route("/progress-page")
@login_required  
def progress_page():
    return render_template("progress.html", username=current_user.username, profile_picture=current_user.profile_picture)


@bp.route("/history")
@login_required
def history():
    sessions = UserSession.query.filter_by(user_id = current_user.id)\
    .order_by(UserSession.created_at.desc())\
    .limit(5).all()

    result = []
    for s in sessions:
        result.append({
            "tarih" : s.created_at.strftime("%d.%m.%Y %H:%M"),
            "kilo" : s.weight,
            "hedef_kalori" : s.target_calories,
            "coach_reply" : s.coach_reply
        })
    return Response(
        json.dumps(result, ensure_ascii=False),
        mimetype="application/json"
    )


@bp.route("/last-session")
@login_required
def last_session():
    s = UserSession.query.filter_by(user_id=current_user.id)\
        .order_by(UserSession.created_at.desc())\
        .first()

    if not s:
        return jsonify({"exists": False})

    return jsonify({
        "exists"          : True,
        "weight"          : current_user.weight or s.weight,
        "height"          : s.height,
        "age"             : s.age,
        "gender"          : s.gender,
        "goal"            : s.goal,
        "fitness_level"   : s.fitness_level,
        "current_activity": s.current_activity,
        "bmr"             : s.bmr,
        "tdee"            : s.tdee,
        "target_calories" : s.target_calories,
        "target_weight"   : current_user.target_weight,
        "goal_type"       : current_user.goal_type,
        "tarih"           : s.created_at.strftime("%d.%m.%Y")
    })


@bp.route("/dashboard-nudges")
@login_required
def dashboard_nudges():
    from analytics_engine import get_nudges
    nudge_translations = {
        "NUDGE_MISSING_LOGS": "Son 48 saatte antrenman veya beslenme kaydın yok. Bugün hedeflerine bir adım daha yaklaş!",
        "NUDGE_NO_WORKOUT": "Son 48 saatte antrenman kaydı görünmüyor. Kısa bir antrenman bile fark yaratır.",
        "NUDGE_NO_NUTRITION": "Beslenme kaydını güncellemeyi unutma — veriler koçunun sana daha iyi yardım etmesini sağlar.",
        "NUDGE_STREAK_RISK": "Serin risk altında! Bugün giriş yaparak kesintisiz serinizi koruyun.",
        "NUDGE_PROTEIN_GOAL": "Haftalık protein hedefinin %90'ına ulaştın — harika gidiyorsun!",
        "NUDGE_WEEKLY_REPORT": "Bugün haftalık rapor günü. Koçundan performans özetini iste!",
    }
    try:
        models = {
            "WorkoutLog": WorkoutLog,
            "UserDailyNutrition": UserDailyNutrition,
            "UserSession": UserSession,
        }
        raw_nudges = get_nudges(User.query.get(current_user.id), db, models,
                                getattr(g, "prev_last_login", None))
        cleaned = []
        for n in (raw_nudges or []):
            key = n.split(":")[0].strip() if ":" in n else ""
            cleaned.append(nudge_translations.get(key, n))
        return jsonify({"nudges": cleaned})
    except Exception:
        return jsonify({"nudges": []})
