# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import json
import s3_helper
from datetime import date
from flask import Blueprint, current_app, jsonify, render_template, request
from flask_login import current_user, login_required

from app.config import AI_RATELIMIT, BEDROCK_RATELIMIT
from app.extensions import _user_or_ip_key, db, limiter
from app.models import DailyQuest, PumpCheck, TrainingPlan, UserQuestProgress, UserSession, WaterLog
from app.services.ai import _heavy_chat
from app.services.gamification import award_xp, complete_quest_for_user, get_level, get_title, log_activity
from app.services.menu_extract import validate_pump_check
from app.services.validators import validate_pump_check_image


bp = Blueprint("training", __name__)


@bp.route("/training")
@login_required
def training():
    return render_template("training.html", username=current_user.username, profile_picture=current_user.profile_picture)


@bp.route("/training-plan", methods=["POST"])
@login_required
@limiter.limit(AI_RATELIMIT, key_func=_user_or_ip_key)
@limiter.limit(BEDROCK_RATELIMIT, key_func=_user_or_ip_key)  # Sonnet üretimi: daha sıkı tavan
def training_plan_generate():
    data = request.get_json(silent=True) or {}

    last = UserSession.query.filter_by(user_id=current_user.id)\
        .order_by(UserSession.created_at.desc())\
        .first()

    if not last:
        return jsonify({"error": "Önce ana sayfadan planını oluştur."}), 400

    goal             = last.goal
    fitness_level    = last.fitness_level
    current_activity = last.current_activity
    tdee             = last.tdee

    gun_sayisi       = data.get("gun_sayisi", 3)
    ekipman          = data.get("ekipman", "spor_salonu")
    odak             = data.get("odak", "tum_vucut")
    sure             = data.get("sure", 45)
    kardiyo_tipi     = data.get("kardiyo_tipi", "yok")
    kardiyo_gun      = data.get("kardiyo_gun", 0)
    kardiyo_sure     = data.get("kardiyo_sure", 20)
    kardiyo_yogunluk = data.get("kardiyo_yogunluk", "orta")
    antrenman_tarzi  = data.get("antrenman_tarzi", "genel")
    odak_hedef       = data.get("odak_hedef", "genel")

    ekipman_labels = {
        "ev"          : "ev ortamı (vücut ağırlığı egzersizleri)",
        "spor_salonu" : "spor salonu (tam ekipman, barbell, dambıl, makineler)",
        "minimal"     : "minimal ekipman (dambıl ve direnç bandı)"
    }

    odak_labels = {
        "tum_vucut" : "tüm vücut",
        "ust_vucut" : "üst vücut (göğüs, sırt, omuz, kol)",
        "alt_vucut" : "alt vücut (bacak, kalça, baldır)",
        "core"      : "karın ve core bölgesi",
        "sirt"      : "sırt odaklı (latissimus, trapez, rhomboid, arka zincir — sırta ekstra hacim ver)"
    }

    kardiyo_labels = {
        "kosu"     : "koşu",
        "bisiklet" : "bisiklet",
        "yuzme"    : "yüzme",
        "ip_atlama": "ip atlama",
        "yuruyus"  : "tempolu yürüyüş",
        "karisik"  : "karışık (koşu, bisiklet, ip atlama kombinasyonu)",
        "yok"      : "kardiyo yok"
    }

    yogunluk_labels_kardiyo = {
        "dusuk"  : "düşük yoğunluk (LISS — konuşabilecek tempoda)",
        "orta"   : "orta yoğunluk (konuşması biraz zor)",
        "yuksek" : "yüksek yoğunluk (HIIT — interval)",
        "karisik": "karışık (bazı günler LISS, bazı günler HIIT)"
    }
    tarzi_labels = {
        "genel"        : "genel fitness (karışık antrenman)",
        "crossfit"     : "CrossFit tarzı (fonksiyonel, yüksek yoğunluk, WOD yapısı)",
        "calisthenics" : "kalistenik (vücut ağırlığı, beceri odaklı — muscle up, handstand)",
        "powerlifting" : "powerlifting (squat, bench, deadlift odaklı, düşük tekrar yüksek ağırlık)",
        "bodybuilding" : "vücut geliştirme (hipertrofi odaklı, split program, kas izolasyonu)",
        "fonksiyonel"  : "fonksiyonel antrenman (günlük hareket kalıpları, mobilite)"
    }

    hedef_labels = {
        "genel"      : "genel fitness ve sağlık",
        "guc"        : "maksimum güç artışı",
        "kondisyon"  : "kardiyovasküler kondisyon ve dayanıklılık",
        "kas_kutlesi": "kas kütlesi ve hipertrofi",
        "yag_yakimi" : "yağ yakımı ve vücut rekomposizyonu",
        "esneklik"   : "esneklik ve mobilite"
    }

    # Kardiyo metni
    if kardiyo_tipi != "yok" and kardiyo_gun > 0:
        kardiyo_text = (
            f"Kardiyo tercihleri:\n"
            f"- Kardiyo türü: {kardiyo_labels.get(kardiyo_tipi, kardiyo_tipi)}\n"
            f"- Haftada {kardiyo_gun} gün kardiyo\n"
            f"- Her kardiyo seansı: {kardiyo_sure} dakika\n"
            f"- Kardiyo yoğunluğu: {yogunluk_labels_kardiyo.get(kardiyo_yogunluk, kardiyo_yogunluk)}\n"
            f"\n"
            f"Kardiyo günlerini ağırlık antrenmanı günleriyle akıllıca birleştir veya ayrı günlere koy.\n"
            f"HIIT'i ağırlık günüyle aynı güne koyma — LISS ise aynı gün olabilir.\n"
            f"Her kardiyo seansı için tahmini kalori yakımını belirt.\n"
            f"Kardiyo günlerinin tipini 'kardiyo' olarak işaretle."
        )
    else:
        kardiyo_text = "Kardiyo istemiyor — sadece ağırlık antrenmanı planla."

    # Odak bölgeye ve gün sayısına göre split yapısı öner
    odak_raw = odak  # "sirt", "tum_vucut" vb.

    split_rehber_map = {
        ("sirt", 3): "Push-Pull-Legs: Gün1=SIRT+Biceps (en az 6 egzersiz), Gün2=Göğüs+Triceps+Omuz, Gün3=Bacak+Core",
        ("sirt", 4): "Gün1=SIRT+Biceps (en az 6 egzersiz), Gün2=Göğüs+Triceps, Gün3=Bacak, Gün4=Omuz+Core+Ek Sırt (Face Pull, Shrug)",
        ("sirt", 5): "Gün1=SIRT (6-7 egzersiz, sadece sırt), Gün2=Göğüs+Triceps, Gün3=Bacak, Gün4=Omuz+Ek Sırt, Gün5=Biceps+Triceps+Core",
        ("sirt", 6): "Gün1=SIRT+Biceps, Gün2=Göğüs+Triceps, Gün3=Bacak, Gün4=SIRT+Omuz (ikinci sırt günü), Gün5=Göğüs+Triceps, Gün6=Bacak+Core",
        ("tum_vucut", 3): "Gün1=Full Body A (squat+bench+row), Gün2=Full Body B (deadlift+press+pulldown), Gün3=Full Body C (lunge+dips+curl)",
        ("tum_vucut", 4): "Upper A (Göğüs+Sırt) / Lower A (Bacak ön) / Upper B (Omuz+Kol) / Lower B (Bacak arka+Core)",
        ("tum_vucut", 5): "Push / Pull (Sırt+Biceps) / Bacak / Upper (Göğüs+Omuz) / Core+Ek",
        ("tum_vucut", 6): "PPL tekrar: Push/Pull/Legs/Push/Pull/Legs",
        ("ust_vucut", 3): "Gün1=Göğüs+Triceps, Gün2=SIRT+Biceps (en az 5 egzersiz), Gün3=Omuz+Core",
        ("ust_vucut", 4): "Gün1=Göğüs+Triceps, Gün2=SIRT+Biceps, Gün3=Omuz+Core, Gün4=Göğüs+Sırt (compound odak)",
        ("ust_vucut", 5): "Gün1=Göğüs, Gün2=SIRT (tek başına 6 egzersiz), Gün3=Omuz, Gün4=Biceps+Triceps, Gün5=Full Upper",
        ("ust_vucut", 6): "Gün1=Göğüs+Triceps, Gün2=SIRT+Biceps, Gün3=Omuz, Gün4=Göğüs+Sırt, Gün5=Kol, Gün6=Full Upper",
        ("alt_vucut", 3): "Gün1=Bacak ön (Quadriceps), Gün2=Bacak arka (Hamstring+Glute), Gün3=Bacak+Baldır+Core",
        ("alt_vucut", 4): "Gün1=Squat odaklı, Gün2=Hip Hinge (deadlift), Gün3=Unilateral (lunge, split squat), Gün4=Glute+Core",
        ("alt_vucut", 5): "Gün1=Quad, Gün2=Posterior chain, Gün3=Güç (squat+deadlift), Gün4=Tek bacak, Gün5=Hipertrofi+Baldır",
        ("core", 3): "Gün1=Core compound (plank, rollout, hanging raise), Gün2=Core rotasyon+oblik, Gün3=Core stabilite+esneklik",
        ("core", 4): "Her güne core bloku ekle, 4. gün full core+mobilite",
        ("core", 5): "Her güne core ekle + 2 hafif kardiyo günü",
    }

    split_rehber = split_rehber_map.get(
        (odak_raw, gun_sayisi),
        f"Haftada {gun_sayisi} günlük dengeli split: her büyük kas grubu (sırt, göğüs, bacak, omuz) en az bir kez çalışılsın. Sırt mutlaka ayrı bir günde yer alsın."
    )

    # Kas grubu bazında geniş egzersiz referans listesi
    egzersiz_referans = """
SPOR SALONU EGZERSİZ REHBERİ (kas grubu başına çeşitli seçenekler):

SIRT (her programda bu egzersizlerden EN AZ 4-5 farklısını kullan):
  Yatay çekiş (compound): Barbell Bent Over Row, Dumbbell Row (tek kol), T-Bar Row, Cable Seated Row, Yatay Makine Çekiş
  Dikey çekiş (compound): Lat Pulldown (geniş tutuş), Lat Pulldown (dar tutuş), Pull-Up (barfiks), Chin-Up, Assisted Pull-Up
  İzolasyon/detail: Face Pull, Straight-Arm Pulldown, Cable Pullover, Rack Pull, Shrug (trapez), Rear Delt Fly
  Deadlift ailesi: Conventional Deadlift, Romanian Deadlift, Sumo Deadlift
  Sırt kalınlık: Meadows Row, Pendlay Row, Chest-Supported Row

GÖĞÜS: Bench Press (düz/eğimli/negatif), Dumbbell Fly, Cable Crossover, Pec Deck, Dips (göğüs), Push-Up, Incline Dumbbell Press

OMUZ: Overhead Press (barbell/dumbbell), Arnold Press, Lateral Raise, Front Raise, Rear Delt Fly, Face Pull, Upright Row, Shrug

BİCEPS: Barbell Curl, Dumbbell Curl, Hammer Curl, Incline Dumbbell Curl, Concentration Curl, Cable Curl, Preacher Curl

TRİCEPS: Triceps Pushdown (ip/düz), Skull Crusher, Close-Grip Bench Press, Overhead Triceps Extension, Dips (triceps), Kickback

BACAK ÖN (quadriceps): Squat, Leg Press, Hack Squat, Leg Extension, Bulgarian Split Squat, Lunge, Step-Up

BACAK ARKA (hamstring/glute): Romanian Deadlift, Leg Curl (yatay/oturarak), Hip Thrust, Sumo Squat, Good Morning, Cable Kickback

BALDUR: Standing Calf Raise, Seated Calf Raise, Donkey Calf Raise, Leg Press Calf Raise

KARIN (core): Crunch, Cable Crunch, Leg Raise, Plank, Russian Twist, Ab Rollout, Hanging Knee Raise, Oblique Crunch

EV / MİNİMAL EKİPMAN (barfiks, dambıl, direnç bandı):
  Sırt: Pull-Up, Chin-Up, Band Bent Over Row, Dumbbell Row, Band Pulldown, Superman Hold
  Göğüs: Push-Up (geniş/dar/eğimli), Dumbbell Press, Dumbbell Fly
  Bacak: Squat, Lunge, Glute Bridge, Romanian Deadlift (dambıl), Step-Up
"""

    prompt = (
        f"Sen 10+ yıllık deneyimli bir kişisel antrenörsün. Türkçe yaz, İngilizce egzersiz isimlerini kullanabilirsin.\n"
        f"\n"
        f"Kullanıcı bilgileri:\n"
        f"- Hedef: {goal}\n"
        f"- Fitness seviyesi: {fitness_level}\n"
        f"- Günlük aktivite: {current_activity}\n"
        f"- TDEE: {round(tdee)} kcal\n"
        f"\n"
        f"Antrenman tercihleri:\n"
        f"- Haftada {gun_sayisi} gün antrenman yapabilir\n"
        f"- Ekipman: {ekipman_labels.get(ekipman, ekipman)}\n"
        f"- Odak bölge: {odak_labels.get(odak, odak)}\n"
        f"- Antrenman süresi: {sure} dakika\n"
        f"- Antrenman tarzı: {tarzi_labels.get(antrenman_tarzi, antrenman_tarzi)}\n"
        f"- Öncelikli hedef: {hedef_labels.get(odak_hedef, odak_hedef)}\n"
        f"\n"
        f"{kardiyo_text}\n"
        f"\n"
        f"{egzersiz_referans}\n"
        f"\n"
        f"ÖNERİLEN SPLIT YAPISI ({gun_sayisi} gün için):\n"
        f"{split_rehber}\n"
        f"\n"
        f"PROGRAM KURALLARI:\n"
        f"1. Haftanın tam 7 günü için plan yap (Pazartesi'den Pazar'a).\n"
        f"2. Yukarıdaki split yapısına uy — sırt günü MUTLAKA programda yer alsın.\n"
        f"3. Sırt günü için EGZERSİZ REHBERİ'ndeki listeden EN AZ 5 FARKLI egzersiz seç:\n"
        f"   - En az 1 yatay çekiş (Row ailesi)\n"
        f"   - En az 1 dikey çekiş (Pulldown/Pull-up ailesi)\n"
        f"   - En az 1 izolasyon (Face Pull, Pullover, Shrug vb.)\n"
        f"   - Sırt günü 'odak' alanına 'Sırt ve Biceps' veya 'Sırt (Lat + Kalın Sırt)' yaz.\n"
        f"4. Aynı kas grubunu ard arda iki güne koyma.\n"
        f"5. Her egzersiz için gerçekçi set, tekrar ve dinlenme süresi yaz.\n"
        f"6. Her günün tahmini kalori yakımını gerçekçi hesapla (200-600 kcal arası).\n"
        f"7. 'not' alanına egzersiz için kısa teknik ipucu yaz.\n"
        f"8. Toplam antrenman günü tam olarak {gun_sayisi} olsun.\n"
        f"\n"
        f"SADECE geçerli JSON döndür, başka hiçbir şey yazma. Format:\n"
        f'{{"program": ['
        f'{{"gun": "Pazartesi", "tip": "antrenman", "odak": "Sırt ve Biceps", "sure_dk": {sure}, "tahmini_kalori": 380, '
        f'"egzersizler": ['
        f'{{"isim": "Bent Over Row", "set": 4, "tekrar": "8-10", "dinlenme": "90 sn", "not": "sırt düz tut, kürek kemiklerini sıkıştır"}}, '
        f'{{"isim": "Lat Pulldown", "set": 4, "tekrar": "10-12", "dinlenme": "75 sn", "not": "tam uzanım, tam çekiş"}}, '
        f'{{"isim": "Cable Seated Row", "set": 3, "tekrar": "10-12", "dinlenme": "75 sn", "not": "dirsekleri gövdeye yak"}}, '
        f'{{"isim": "Face Pull", "set": 3, "tekrar": "15-20", "dinlenme": "60 sn", "not": "omuz sağlığı için kritik"}}, '
        f'{{"isim": "Barbell Curl", "set": 3, "tekrar": "10-12", "dinlenme": "60 sn", "not": "sallanma yapma"}}]'
        f'}}, '
        f'{{"gun": "Salı", "tip": "dinlenme", "odak": "Aktif Toparlanma", "sure_dk": 0, "tahmini_kalori": 0, "egzersizler": []}}, '
        f'{{"gun": "Çarşamba", "tip": "antrenman", "odak": "Göğüs ve Triceps", "sure_dk": {sure}, "tahmini_kalori": 350, '
        f'"egzersizler": [{{"isim": "Bench Press", "set": 4, "tekrar": "8-10", "dinlenme": "90 sn", "not": "kürek kemiklerini bankaya bas"}}]}}], '
        f'"haftalik_ozet": {{"toplam_antrenman_gun": {gun_sayisi}, "toplam_tahmini_kalori": 1800, '
        f'"yogunluk_skoru": 8, "denge_skoru": 8, "uygunluk_skoru": 9}}}}'
    )

    try:
        raw = _heavy_chat(
            messages=[{"role": "user", "content": prompt}],
            system_prompt="Sen deneyimli bir kişisel antrenörsün. SADECE geçerli JSON döndür, başka hiçbir şey yazma. Markdown, açıklama veya yorum ekleme.",
            max_tokens=4000,
            temperature=0.4,
        ).strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start != -1 and end > start:
            raw = raw[start:end]
        plan = json.loads(raw)

        ozet     = plan.get("haftalik_ozet", {})
        yogunluk = ozet.get("yogunluk_skoru", 0)
        denge    = ozet.get("denge_skoru", 0)
        uygunluk = ozet.get("uygunluk_skoru", 0)

        # AI 0 döndürürse default 7 kullan
        if yogunluk == 0:
            yogunluk = 7
        if denge == 0:
            denge = 7
        if uygunluk == 0:
            uygunluk = 7

        overall  = round((yogunluk + denge + uygunluk) / 3, 1)

        if overall >= 8:
            score_label = "İyi"
        elif overall >= 6:
            score_label = "Orta"
        else:
            score_label = "Kötü"

        return jsonify({
            "program"      : plan["program"],
            "haftalik_ozet": ozet,
            "overall_score": overall,
            "score_label"  : score_label
        })

    except json.JSONDecodeError:
        return jsonify({"error": "Plan oluşturulamadı, tekrar dene."}), 500
    except Exception:
        current_app.logger.exception("Plan oluşturma hatası")
        return jsonify({"error": "Plan oluşturulamadı, lütfen tekrar dene."}), 500


@bp.route("/training-plan/save", methods=["POST"])
@login_required
def save_training_plan():
    data  = request.get_json(silent=True) or {}
    plan  = data.get("plan")
    score = data.get("score")

    if not plan:
        return jsonify({"error": "Plan verisi eksik"}), 400

    TrainingPlan.query.filter_by(user_id=current_user.id).delete()

    new_plan = TrainingPlan(
        user_id   = current_user.id,
        plan_data = json.dumps(plan, ensure_ascii=False), 
        score     = score
    )
    db.session.add(new_plan)
    db.session.commit()

    return jsonify({"message": "Antrenman planı kaydedildi."})


@bp.route("/workout/complete", methods=["POST"])
@login_required
@limiter.limit(AI_RATELIMIT, key_func=_user_or_ip_key)
def complete_workout():
    plan = TrainingPlan.query.filter_by(user_id=current_user.id)\
        .order_by(TrainingPlan.created_at.desc()).first()
    if not plan:
        return jsonify({"error": "Aktif antrenman planın yok."}), 400

    today_key = date.today().isoformat()
    quest = DailyQuest.query.filter_by(quest_type="workout_logged", is_active=True).first()
    if quest:
        existing = UserQuestProgress.query.filter_by(
            user_id=current_user.id, quest_id=quest.id, date_key=today_key
        ).first()
        if existing:
            return jsonify({"error": "Bugünkü antrenmanını zaten tamamladın!"}), 400

    # ── PUMP CHECK GATE ──────────────────────────────────────────────────────
    # Antrenman tamamlanmadan önce ortam fotoğrafı + konum AI ile doğrulanmalı.
    # Doğrulama geçerse fotoğraf S3'e (özel bucket) yüklenir ve kaydı tutulur.
    data = request.get_json(silent=True) or {}
    image_bytes, img_mime, img_err = validate_pump_check_image(data.get("image"))
    if img_err:
        return jsonify({"error": img_err}), 400

    location_type = (data.get("location_type") or "")[:50]
    description = (data.get("description") or "")[:200]

    check = validate_pump_check(image_bytes, location_type, description)
    if not check["valid"]:
        # Doğrulama başarısız (fail-open değil) → XP yok, kullanıcı yeniden denesin.
        return jsonify({"error": check["reason"]}), 422

    # Doğrulanan fotoğrafı S3'e yükle. S3 hatası antrenman tamamlamayı bloklamaz
    # (fail-open) — yalnızca görsel kaydı atlanır.
    pump_image_key = None
    try:
        if s3_helper.is_enabled():
            pump_image_key = s3_helper.upload_image(
                image_bytes, content_type=img_mime,
                prefix="pump-checks", user_id=current_user.id,
            )
    except Exception as e:
        current_app.logger.info(f"[S3] Pump Check yüklemesi başarısız: {type(e).__name__}: {e}")

    db.session.add(PumpCheck(
        user_id=current_user.id, image_key=pump_image_key,
        location_type=location_type, description=description,
        valid=True, fallback=check.get("fallback", False),
    ))
    # ─────────────────────────────────────────────────────────────────────────

    base_xp = 10
    pump_bonus = 25
    quest_result = complete_quest_for_user(current_user.id, "workout_logged")
    new_total = award_xp(current_user.id, base_xp + pump_bonus)
    log_activity(current_user.id, "workout_completed",
                 "Bugünkü antrenmanını tamamladı (Pump Check ✓)")
    db.session.commit()

    total_xp = base_xp + pump_bonus + (quest_result["xp"] if quest_result else 0)
    level = get_level(new_total)
    response = {
        "message": f"Bugünkü antrenmanı tamamladın! +{total_xp} XP! (Pump Check +{pump_bonus})",
        "points_awarded": total_xp,
        "pump_bonus": pump_bonus,
        "new_total": new_total,
        "level": level,
        "title": get_title(level)
    }
    if quest_result:
        response["quest_awarded"] = quest_result
    if pump_image_key:
        response["pump_image_url"] = s3_helper.generate_presigned_url(
            pump_image_key, expires_in=3600, expected_user_id=current_user.id)
    return jsonify(response)


@bp.route("/workout/status")
@login_required
def workout_status():
    # Bugünkü antrenman tamamlanmış mı? (cihazlar arası senkron için sunucudan)
    today_key = date.today().isoformat()
    quest = DailyQuest.query.filter_by(quest_type="workout_logged", is_active=True).first()
    completed = False
    if quest:
        completed = UserQuestProgress.query.filter_by(
            user_id=current_user.id, quest_id=quest.id, date_key=today_key
        ).first() is not None
    return jsonify({"completed": completed})


@bp.route("/training-plan/active")
@login_required
def get_active_training_plan():
    plan = TrainingPlan.query.filter_by(user_id=current_user.id)\
        .order_by(TrainingPlan.created_at.desc())\
        .first()

    if not plan:
        return jsonify({"exists": False})

    return jsonify({
        "exists"    : True,
        "plan"      : json.loads(plan.plan_data),
        "score"     : plan.score,
        "created_at": plan.created_at.strftime("%d.%m.%Y")
    })


@bp.route("/water", methods=["GET"])
@login_required
def get_water():
    today_key = date.today().isoformat()
    row = WaterLog.query.filter_by(user_id=current_user.id, date_key=today_key).first()
    return jsonify({"count": row.count if row else 0, "goal": WATER_GOAL})


@bp.route("/water", methods=["POST"])
@login_required
def set_water():
    data = request.get_json(silent=True) or {}
    try:
        count = int(data.get("count", 0))
    except (TypeError, ValueError):
        return jsonify({"error": "Geçersiz değer."}), 400
    count = max(0, min(count, WATER_GOAL))  # 0..8 arası kıs

    today_key = date.today().isoformat()
    row = WaterLog.query.filter_by(user_id=current_user.id, date_key=today_key).first()
    if row:
        row.count = count
    else:
        row = WaterLog(user_id=current_user.id, date_key=today_key, count=count)
        db.session.add(row)
    db.session.commit()
    return jsonify({"count": row.count, "goal": WATER_GOAL})


WATER_GOAL = 8  # bardak
