# Auto-generated by refactor: extracted verbatim from starter.py (factory + blueprints split).
import json
import s3_helper
from flask import Blueprint, current_app, jsonify, render_template, request
from flask_login import current_user
from app.auth_middleware import require_auth
from sqlalchemy.exc import IntegrityError, SQLAlchemyError

from app.config import AI_RATELIMIT, BEDROCK_RATELIMIT
from app.extensions import _user_or_ip_key, auth_write_limit, db, limiter
from app.i18n import current_locale, t
from app.observability import current_request_id
from app.models import DailyQuest, PumpCheck, TrainingPlan, UserQuestProgress, UserSession, WaterLog, WorkoutLog
from app.services.ai import _heavy_chat
from app.services.ai_gate import ai_concurrency_gate
from app.services.gamification import complete_quest_for_user
from app.services.menu_extract import validate_pump_check
from app.services.pump_checks import get_friend_ids, normalize_workout_score
from app.services.premium import premium_ai_plan_gate
from app.plan_presenter import build_plan_view
from app.services.plan_facts import gather_plan_facts
from app.services.today_facts import get_active_plan
from app.services.training_generation.response_validator import PlanValidationError
from app.services.training_generation.service import generate_training_plan_payload
from app.services.validators import validate_pump_check_image
from app.services.weekly_program import build_weekly_program, weekly_program_payload
from app.services.workout_completion import (
    CompleteWorkoutCommand,
    SessionCompletionConflict,
    already_completed_today,
    complete_workout as run_completion,
)
from app.services.workout_session import (
    SessionOutcome,
    abandon_session,
    checkpoint_session,
    get_current_session,
    resolve_for_completion,
    resume_session,
    start_session,
)
from app.services.workout_state import resolve_workout_state
from app.services.workout_state.snapshot import coherent_read_snapshot
from app.services.workout_state.serialization import (
    serialize_plan, serialize_today_plan, workout_state_payload)
from app.timeutil import app_today, display_dt


bp = Blueprint("training", __name__)

# Sprint 7 PR3: HTTP status for each deterministic session lifecycle outcome. 2xx =
# the operation succeeded or an idempotent equivalent; 409 = a deterministic
# conflict (stale/needs-resolution, a different active workout, an abandoned
# session); 404 = not owned / not found. The body always carries the machine
# ``outcome`` (and ``code`` on non-2xx) so clients branch on a stable value.
_SESSION_HTTP = {
    SessionOutcome.CREATED: 201,
    SessionOutcome.EXISTING_ACTIVE: 200,
    SessionOutcome.RESUMED: 200,
    SessionOutcome.CHECKPOINTED: 200,
    SessionOutcome.ABANDONED: 200,
    SessionOutcome.COMPLETED: 200,
    SessionOutcome.ALREADY_COMPLETED: 200,
    SessionOutcome.ALREADY_ABANDONED: 200,
    SessionOutcome.STALE_SESSION_REQUIRES_RESOLUTION: 409,
    SessionOutcome.CONFLICT: 409,
    SessionOutcome.INVALID_TRANSITION: 409,
    SessionOutcome.NOT_FOUND: 404,
}
_WEEKLY_PROGRAM_PATH = "/api/training/weekly-program"


@bp.after_request
def _weekly_program_private_no_store(response):
    """Prevent storage of per-user recommendations for the original API request."""
    if request.path == _WEEKLY_PROGRAM_PATH:
        response.headers["Cache-Control"] = "private, no-store"
    return response


def _weekly_program_state(recommendation):
    if not recommendation.has_data:
        return "neutral"
    if recommendation.baseline_weekly_volume is None:
        return "missing_baseline"
    return "populated"


def _weekly_program_error_class(error):
    if isinstance(error, SQLAlchemyError):
        return "upstream_error"
    return "unexpected_error"


def _parse_pump_visibility(data):
    raw_visibility = data.get("visibility")
    if raw_visibility is None:
        visibility = "feed"
    elif isinstance(raw_visibility, str):
        visibility = raw_visibility.strip().lower()
    else:
        return None, [], t("pump.visibility_invalid")
    if visibility not in {"feed", "friends", "private"}:
        return None, [], t("pump.visibility_invalid")
    raw_ids = data.get("shared_friend_ids")
    if raw_ids is None:
        raw_ids = []
    elif not isinstance(raw_ids, list):
        return None, [], t("pump.friend_ids_invalid")
    selected_ids = []
    seen_ids = set()
    for raw_id in raw_ids:
        if isinstance(raw_id, bool) or not isinstance(raw_id, int):
            return None, [], t("pump.friend_ids_invalid")
        if raw_id not in seen_ids:
            seen_ids.add(raw_id)
            selected_ids.append(raw_id)
    if visibility == "friends" and not selected_ids:
        return None, [], t("pump.friend_required")
    if visibility != "friends":
        selected_ids = []
    return visibility, selected_ids, None


@bp.route("/training")
@require_auth
def training():
    # UIUX Sprint 1 PR3: full-template swap IN the route (never a mixed tree),
    # mirroring the PR2 Today swap. Flag OFF → the legacy /training page renders
    # byte-identically; ON → the server-authoritative Plan v2 surface, which reads
    # only canonical data (no clock-based "today", no rest-day inference, no
    # completion-from-storage). The flag is read only here, only from server config
    # (never a query param/cookie/header/browser storage). Independent of
    # WEEKLY_PROGRAM_UI_ENABLED, which Plan v2 also honors for its weekly section.
    weekly_enabled = current_app.config.get("WEEKLY_PROGRAM_UI_ENABLED", False)
    if current_app.config.get("UIUX_PLAN_V2_ENABLED", False):
        plan_view = build_plan_view(
            gather_plan_facts(current_user.id), weekly_enabled=weekly_enabled)
        return render_template("plan.html", plan=plan_view)

    # Kayıtlı sakatlık verisini forma ön-doldur (yapışkan alan). None-güvenli.
    _meta = getattr(current_user, "user_metadata", None) or {}
    injuries = _meta.get("injuries") or ""
    # Sprint 6 PR6.1: the ONLY thing this route knows about the weekly program is
    # whether its UI mount point should exist. Deliberately the narrowest possible
    # boundary — a single server-owned boolean, not a context processor and not a
    # client-side flag framework, so no other config can leak into the page. The
    # route stays free of build_weekly_program / WorkoutLog / the planner: PR6.1
    # renders a shell, it does not consume data (docs/WEEKLY_PROGRAM.md).
    return render_template("training.html", username=current_user.username,
                           profile_picture=current_user.avatar_src,
                           injuries=injuries,
                           weekly_program_ui_enabled=weekly_enabled)


@bp.route("/training-plan", methods=["POST"])
@require_auth
@limiter.limit(AI_RATELIMIT, key_func=_user_or_ip_key)
@limiter.limit(BEDROCK_RATELIMIT, key_func=_user_or_ip_key)  # Sonnet üretimi: daha sıkı tavan
@premium_ai_plan_gate("training")  # non-premium: haftada 1 üretim
@ai_concurrency_gate  # A1: bloklayıcı AI çağrıları tüm thread'leri doldurmasın
def training_plan_generate():
    data = request.get_json(silent=True) or {}

    last = UserSession.query.filter_by(user_id=current_user.id)\
        .order_by(UserSession.created_at.desc())\
        .first()

    if not last:
        return jsonify({"error": t("plan.no_session")}), 400

    try:
        return jsonify(generate_training_plan_payload(
            current_user,
            last,
            data,
            chat_fn=_heavy_chat,
            language=current_locale(),
            logger=current_app.logger,
        ))
    except (json.JSONDecodeError, PlanValidationError):
        return jsonify({"error": t("plan.gen_failed")}), 500
    except Exception:
        current_app.logger.exception("Plan oluşturma hatası")
        return jsonify({"error": t("route.plan_failed")}), 500


@bp.route("/training-plan/save", methods=["POST"])
@require_auth
def save_training_plan():
    data  = request.get_json(silent=True) or {}
    plan  = data.get("plan")
    score = data.get("score")

    if not plan:
        return jsonify({"error": t("route.plan_data_missing")}), 400

    TrainingPlan.query.filter_by(user_id=current_user.id).delete()

    new_plan = TrainingPlan(
        user_id   = current_user.id,
        plan_data = json.dumps(plan, ensure_ascii=False), 
        score     = score
    )
    db.session.add(new_plan)
    db.session.commit()

    return jsonify({"message": t("route.training_plan_saved")})


@bp.route("/workout/complete", methods=["POST"])
@require_auth
@limiter.limit(AI_RATELIMIT, key_func=_user_or_ip_key)
@limiter.limit(BEDROCK_RATELIMIT, key_func=_user_or_ip_key)  # validate_pump_check Sonnet görü: daha sıkı tavan
@ai_concurrency_gate  # A1: bloklayıcı Bedrock görü çağrısı tüm thread'leri doldurmasın
def complete_workout():
    plan = TrainingPlan.query.filter_by(user_id=current_user.id)\
        .order_by(TrainingPlan.created_at.desc()).first()
    if not plan:
        return jsonify({"error": t("route.no_active_training_plan")}), 400

    data = request.get_json(silent=True) or {}

    # Sprint 7 PR3 (optional, flag-gated): an OPTIONAL persisted session may be
    # supplied by opaque public id. Resolve ownership → internal id BEFORE the
    # expensive Bedrock/S3 work so a terminal/not-owned session fails fast. Absent
    # (or flag OFF) ⇒ the unchanged legacy completion path — no session fabricated.
    session_internal_id = None
    if _workout_sessions_enabled():
        session_public_id = (data.get("session_id") or "").strip()[:64] or None
        if session_public_id:
            session_internal_id, sess_err = resolve_for_completion(
                current_user.id, session_public_id)
            if sess_err is not None:
                # Terminal/not-found session → deterministic conflict, no completion.
                return _session_response(sess_err)

    # M3 + Sprint 7 PR2: günlük idempotency artık kanonik tamamlanma sınırının
    # salt-okunur preflight'ıdır (app/services/workout_completion). Bugün zaten bir
    # Pump Check varsa antrenman tamamlanmış sayılır → pahalı Bedrock görü + S3
    # yüklemesi AŞAĞIDAKİ bloklardan ÖNCE atlanır. Yarış-güvenli asıl iddia
    # uq_pump_check_day; bu preflight yalnızca maliyet/gecikme optimizasyonudur.
    if already_completed_today(current_user.id, app_today()):
        # Sprint 7 PR3: a session-linked replay must still terminalize the owned
        # ACTIVE session (no new artifacts, no Bedrock/S3) — correction #3.
        if session_internal_id is not None:
            try:
                run_completion(CompleteWorkoutCommand(
                    user_id=current_user.id, today=app_today(),
                    session_id=session_internal_id, entry_path="route",
                ))
            except SessionCompletionConflict:
                return jsonify({"error": "session_conflict",
                                "code": "session_conflict"}), 409
            except Exception as e:  # noqa: BLE001 — never leak; reconcile is best-effort
                current_app.logger.warning(
                    "[WORKOUT] session reconcile failed: %s: %s", type(e).__name__, e)
        return jsonify({"error": t("route.workout_already_done"),
                        "code": "already_completed"}), 400

    # ── PUMP CHECK GATE ──────────────────────────────────────────────────────
    # Antrenman tamamlanmadan önce ortam fotoğrafı + konum AI ile doğrulanmalı.
    # Doğrulama geçerse fotoğraf S3'e (özel bucket) yüklenir ve kaydı tutulur.
    image_bytes, img_mime, img_err = validate_pump_check_image(data.get("image"))
    if img_err:
        return jsonify({"error": img_err}), 400

    location_type = (data.get("location_type") or "")[:50]
    description = (data.get("description") or "")[:200]
    visibility, selected_friend_ids, visibility_error = _parse_pump_visibility(data)
    if visibility_error:
        return jsonify({"error": visibility_error}), 400
    if visibility == "friends":
        accepted_ids = get_friend_ids(current_user.id)
        if any(fid not in accepted_ids for fid in selected_friend_ids):
            return jsonify({"error": t("pump.friend_ids_invalid")}), 400

    check = validate_pump_check(image_bytes, location_type, description)
    if not check["valid"]:
        # Doğrulama başarısız (fail-open değil) → XP yok, kullanıcı yeniden denesin.
        return jsonify({"error": check["reason"]}), 422

    # Doğrulanan fotoğrafı S3'e yükle. S3 hatası antrenman tamamlamayı bloklamaz
    # (fail-open) — yalnızca görsel kaydı atlanır.
    pump_image_key = None
    try:
        if s3_helper.is_enabled():
            pump_image_key = s3_helper.upload_image(
                image_bytes, content_type=img_mime,
                prefix="pump-checks", user_id=current_user.id,
            )
    except Exception as e:
        current_app.logger.info(f"[S3] Pump Check yüklemesi başarısız: {type(e).__name__}: {e}")

    # Kanonik tamamlanma mutasyonu (Sprint 7 PR2): PumpCheck + marker + XP + görev +
    # challenge + activity'nin TEK atomik transaction'ının sahibi
    # app/services/workout_completion. Bu route yalnızca transport + doğrulama +
    # medya + yanıt biçimlendirmesinden sorumlu; rakip tamamlanma semantiği TUTMAZ
    # (AI koç gym-photo aracı da aynı sınırı paylaşır → tek kaynak).
    photo_bonus = 25
    try:
        result = run_completion(CompleteWorkoutCommand(
            user_id=current_user.id,
            today=app_today(),
            session_id=session_internal_id,  # Sprint 7 PR3: None ⇒ legacy path
            image_key=pump_image_key,
            location_type=location_type,
            description=description,
            workout_score=normalize_workout_score(plan.score),
            visibility=visibility,
            shared_friend_ids=tuple(selected_friend_ids),
            valid=True,
            fallback=check.get("fallback", False),
            base_xp=10,
            photo_bonus=photo_bonus,
            activity_text="Bugünkü antrenmanını tamamladı (foto eklendi)",
            entry_path="route",
        ))
    except SessionCompletionConflict:
        # The linked session was abandoned before it could be completed — a
        # deterministic conflict, rolled back with no artifacts (correction #3).
        return jsonify({"error": "session_conflict", "code": "session_conflict"}), 409
    except Exception as e:
        # Servis beklenmeyen hatada rollback edip yeniden fırlatır (uq_pump_check_day
        # DIŞINDAKİ IntegrityError dahil). Kanonik dostça 500; iç hata istemciye sızmaz.
        current_app.logger.warning("[WORKOUT] tamamlanma başarısız: %s: %s", type(e).__name__, e)
        return jsonify({"error": t("route.generic_error_retry")}), 500
    if result.already_completed:
        return jsonify({"error": t("route.workout_already_done"),
                        "code": "already_completed"}), 400

    response = {
        "message": t("training.workout_done", xp=result.xp_awarded, bonus=photo_bonus),
        "points_awarded": result.xp_awarded,
        "pump_bonus": photo_bonus,
        "pump_check_id": result.pump_check_id,
        "new_total": result.new_total,
        "level": result.level,
        "title": result.title,
        "visibility": visibility,
        "shared_friend_ids": selected_friend_ids,
    }
    if session_internal_id is not None:
        # The linked session was terminalized COMPLETED atomically with this
        # completion (Sprint 7 PR3) — signal it without a second query.
        response["session_completed"] = True
    if result.quest_result:
        response["quest_awarded"] = result.quest_result
    if pump_image_key:
        response["pump_image_url"] = s3_helper.generate_presigned_url(
            pump_image_key, expires_in=3600, expected_user_id=current_user.id)
    return jsonify(response)


@bp.route("/workout/status")
@require_auth
def workout_status():
    # Sprint 7 PR1: the canonical workout-state resolver is the single owner of
    # current workout-state. This route no longer infers state inline — it reads
    # one deterministic snapshot (docs/WORKOUT_STATE.md).
    #
    # `completed` is preserved for back-compat and DERIVED from the snapshot:
    # snapshot.completed_today is today's PumpCheck (Istanbul day) — byte-identical
    # to the previous inline query, which mirrored complete_workout's idempotency
    # guard. The additive `state` object exposes the full contract; existing
    # consumers that only read `completed` are unaffected. The resolver performs
    # NO writes and no external calls.
    #
    # UIUX Sprint 1 PR2 note: Today V2's server-side completion read reuses THIS
    # canonical owner (app/services/today_facts delegates to resolve_workout_state)
    # rather than re-querying — so the page and this endpoint can never disagree.
    snapshot = resolve_workout_state(current_user.id)
    return jsonify(workout_state_payload(snapshot))


def _active_plan_payload(plan, plan_data=None):
    if plan is None:
        return {"exists": False}
    parsed = json.loads(plan.plan_data) if plan_data is None else plan_data
    return {
        "exists": True,
        "plan": parsed,
        "score": plan.score,
        "created_at": display_dt(plan.created_at, "%d.%m.%Y"),
    }


@bp.route("/training/bootstrap")
@require_auth
def training_bootstrap():
    """Return one coherent, fail-closed Training presentation snapshot."""
    user_id = None
    try:
        # Capture request/auth facts before resetting Flask-SQLAlchemy's scoped
        # session.  Nothing below the boundary may dereference current_user.
        user_id = current_user.id
        today = app_today()
        sessions_enabled = _workout_sessions_enabled()
        with coherent_read_snapshot():
            plan = get_active_plan(user_id)
            plan_data = json.loads(plan.plan_data) if plan is not None else None
            snapshot = resolve_workout_state(
                user_id, today=today, plan=plan,
                sessions_enabled=sessions_enabled, strict_reads=True,
            )
            response = jsonify({
                "workout": workout_state_payload(snapshot),
                "plan": _active_plan_payload(plan, serialize_plan(plan_data)),
                "today_plan": serialize_today_plan(plan_data, today),
            })
    except Exception as exc:  # noqa: BLE001 - coherent response must fail closed
        current_app.logger.warning(
            "[TRAINING_BOOTSTRAP] unavailable user_id=%s detail=%s",
            user_id, type(exc).__name__,
        )
        response = jsonify({
            "error": t("route.generic_error_retry"),
            "code": "bootstrap_unavailable",
        })
        response.status_code = 500
    response.headers["Cache-Control"] = "private, no-store"
    return response


# ── Persisted workout-session lifecycle (Sprint 7 PR3) ───────────────────────
# All session routes are gated by FITX_WORKOUT_SESSIONS_ENABLED (default OFF): when
# OFF they are INERT (404), so enabling PR1/PR2 behavior stays byte-identical. The
# flag is a presentation/rollout gate, NOT an authorization gate — every route is
# @require_auth and the service always re-enforces ownership from current_user.id
# (no client-supplied user_id / status / timestamps / version is ever trusted).
def _workout_sessions_enabled() -> bool:
    return bool(current_app.config.get("FITX_WORKOUT_SESSIONS_ENABLED", False))


def _session_disabled_404():
    # Feature OFF ⇒ the route is indistinguishable from a non-existent one. Stable
    # machine envelope (no localized copy — there is no UI consumer yet; the UI
    # rollout is a later, out-of-scope PR).
    return jsonify({"error": "not_found", "code": "not_found"}), 404


def _session_response(result):
    """Serialize a :class:`SessionResult` to the stable envelope + deterministic
    HTTP status. Includes the completion reward fields when a completion result is
    attached (session completed through the PR2 authority)."""
    status = _SESSION_HTTP.get(result.outcome, 200)
    body = {
        "outcome": result.outcome.value,
        "session": result.session.to_dict() if result.session is not None else None,
    }
    if status >= 400:
        body["code"] = result.outcome.value
        body["error"] = result.outcome.value
    completion = getattr(result, "completion", None)
    if completion is not None:
        body["completion"] = {
            "outcome": completion.outcome.value,
            "xp_awarded": completion.xp_awarded,
            "new_total": completion.new_total,
            "level": completion.level,
            "title": completion.title,
        }
    return jsonify(body), status


@bp.route("/workout/session/start", methods=["POST"])
@require_auth
def workout_session_start():
    if not _workout_sessions_enabled():
        return _session_disabled_404()
    # No client body is trusted: the user, Istanbul date, plan snapshot and
    # fingerprint are all derived server-side. The insert is the atomic claim.
    return _session_response(start_session(current_user.id))


@bp.route("/workout/session/current", methods=["GET"])
@require_auth
def workout_session_current():
    if not _workout_sessions_enabled():
        return _session_disabled_404()
    return _session_response(get_current_session(current_user.id))


@bp.route("/workout/session/<public_id>/resume", methods=["POST"])
@require_auth
def workout_session_resume(public_id):
    if not _workout_sessions_enabled():
        return _session_disabled_404()
    return _session_response(resume_session(current_user.id, public_id[:64]))


@bp.route("/workout/session/<public_id>/checkpoint", methods=["POST"])
@require_auth
def workout_session_checkpoint(public_id):
    if not _workout_sessions_enabled():
        return _session_disabled_404()
    return _session_response(checkpoint_session(current_user.id, public_id[:64]))


@bp.route("/workout/session/<public_id>/abandon", methods=["POST"])
@require_auth
def workout_session_abandon(public_id):
    if not _workout_sessions_enabled():
        return _session_disabled_404()
    data = request.get_json(silent=True) or {}
    reason = (data.get("reason") or "").strip()[:40] or None
    return _session_response(
        abandon_session(current_user.id, public_id[:64], reason=reason))


@bp.route("/training-plan/active")
@require_auth
def get_active_training_plan():
    # Kanonik "aktif plan" seçicisi app/services/today_facts.get_active_plan'da
    # (UIUX Sprint 1 PR2): en son oluşturulan plan. Today V2 ile bu uç aynı
    # kuralı paylaşsın diye tek yerden okunur; yanıt AYNI kalır.
    plan = get_active_plan(current_user.id)

    return jsonify(_active_plan_payload(plan))


@bp.route("/api/training/weekly-program")
@require_auth
def get_weekly_program():
    """Read-only weekly-program recommendation for the signed-in user (Sprint 6 PR5).

    The single runtime surface of `app/services/weekly_program/` — deliberately thin:
    one service call, one pure projection, no decision of its own. AdaptivePlan stays
    the sole planning authority; nothing here reads WorkoutLog, recomputes a trend, or
    interprets a signal (`docs/WEEKLY_PROGRAM.md`).

    `weeks`/`end_day` are pinned to the service defaults rather than taken from the
    query string: the response must be deterministic for a given user and day, and a
    caller-tunable window would be a planning knob this layer has no authority to
    offer. Empty history yields the neutral recommendation, never an error.

    Failure semantics differ from the PR4 coach consumer *on purpose*. PR4 catches a
    planner failure and substitutes its neutral contract because the coach must keep
    answering; here the neutral recommendation is a legitimate user state ("not enough
    history"), so returning it on a DB/planner failure would report infrastructure
    breakage as valid data. The failure propagates as a structured JSON 500 instead,
    matching the other JSON routes in this blueprint rather than the HTML error page.
    No `db.session.rollback()` is needed: unlike PR4 the request ends here, and
    Flask-SQLAlchemy's teardown removes the session per request.
    """
    try:
        recommendation = build_weekly_program(current_user.id, weeks=4, end_day=None)
    except Exception as e:
        current_app.logger.warning(
            "[TRAINING][WEEKLY_PROGRAM] request_id=%s state=error error_class=%s",
            current_request_id(), _weekly_program_error_class(e))
        return jsonify({"error": t("route.generic_error_retry")}), 500

    # Minimum useful observability: tells "neutral because no history" apart from
    # "populated recommendation" apart from "upstream failure" (logged above) without
    # emitting history, volumes, or the payload itself.
    current_app.logger.info(
        "[TRAINING][WEEKLY_PROGRAM] request_id=%s state=%s",
        current_request_id(), _weekly_program_state(recommendation))
    return jsonify(weekly_program_payload(recommendation))


@bp.route("/water", methods=["GET"])
@require_auth
def get_water():
    today_key = app_today().isoformat()
    row = WaterLog.query.filter_by(user_id=current_user.id, date_key=today_key).first()
    return jsonify({"count": row.count if row else 0, "goal": WATER_GOAL})


@bp.route("/water", methods=["POST"])
@require_auth
@auth_write_limit
def set_water():
    data = request.get_json(silent=True) or {}
    try:
        count = int(data.get("count", 0))
    except (TypeError, ValueError):
        return jsonify({"error": t("route.invalid_value")}), 400
    count = max(0, min(count, WATER_GOAL))  # 0..8 arası kıs

    today_key = app_today().isoformat()
    row = WaterLog.query.filter_by(user_id=current_user.id, date_key=today_key).first()
    prev_count = row.count if row else 0
    if row:
        row.count = count
        db.session.commit()
    else:
        row = WaterLog(user_id=current_user.id, date_key=today_key, count=count)
        db.session.add(row)
        try:
            db.session.commit()
        except IntegrityError:
            # Yarış: günün ilk iki eşzamanlı isteği de "satır yok" gördü;
            # uq_user_water_day ikinci INSERT'i reddetti. Rollback edip mevcut
            # satırı çekerek güncelle (500 yerine tutarlı sonuç).
            db.session.rollback()
            row = WaterLog.query.filter_by(user_id=current_user.id, date_key=today_key).first()
            if row is None:
                raise
            prev_count = row.count  # yarışı kazanan isteğin huni ateşi sayılır
            row.count = count
            db.session.commit()

    # Su takibi güncellenince "Su Hedefi" görevini ver (günde bir kez claim edilir;
    # complete_quest_for_user zaten claimliyse None döner). Önceden seed'leniyordu
    # ama hiç claim edilmiyordu (ölü görev — 1.1).
    # Huni yalnız günün 0→pozitif geçişinde ateşlenir: weekly_water challenge'ı
    # "5 gün" der; her bardak POST'unda ateşlemek olayları gün sayardı
    # (triage 2026-07-19 #1). active_day deseni: dedup çağıranda.
    resp = {"count": row.count, "goal": WATER_GOAL}
    if count > 0 and prev_count == 0:
        quest_result = complete_quest_for_user(current_user.id, "water_logged")
        if quest_result:
            resp["quest_awarded"] = quest_result
    return jsonify(resp)


WATER_GOAL = 8  # bardak
